### ISSUE TITLE
cannot find a shell for gdb.attach

### ISSUE THREAD

**Issue by vaioco** [Gallopsled/pwntools#1010]
running gdb.attach() or gdb.debug() I got error: "error cannot find shell".
I am running latest pwntools, any suggestion?

thanks

**Comment by ghost** [comment]
Hi vaioco,

are you by any chance running _terminator_ as you default terminal emulator? If so, I also encountered this problem. Something is messed up with terminator's `x-terminal-emulator` script... try to set the following *before* calling `gdb.attach()`: `context.terminal = ["terminator", "-e"]`

HTH

**Comment by zachriggle** [comment]
See the docs for `context.terminal` and `run_in_new_terminal`.

http://docs.pwntools.com/en/stable/context.html#pwnlib.context.ContextType.terminal

http://docs.pwntools.com/en/stable/util/misc.html#pwnlib.util.misc.run_in_new_terminal
