### ISSUE TITLE
Override KeyboardInterrupt in pwnlib

### ISSUE THREAD

**Issue by MumbaiHH** [Gallopsled/pwntools#1011]
# Pwntools Issue Template

Hello, I was curious if it was possible to modify the KeyboardInterrupt fuction in pwnlib without modifying the source itself? I'd attempted placing except KeyboardInterrupt within the code, but pwntools overrides the fuctionality. I was attempting to do this the interactive fuction, to stop the shell from being killed, similiar a "hack" of stty raw -echo with netcat :D would this be possible?

**Comment by zachriggle** [comment]
We do not stop you from catching `KeyboardInterrupt` except when in `tube.interactive()`, in which case execution just resumes on the next line.
