### ISSUE TITLE
using gdb.attach, no shell is opened, even if pwntools say it

### ISSUE THREAD

**Issue by dummys** [Gallopsled/pwntools#1016]
Hi,

I'm trying to spawn a gdb in a new terminal. I'm using urxvtc, but tested same problem with xterm or lxterminal.

Here is my code:

```python
#!/usr/bin/env python2
from pwn import *
context.terminal = "urxvtc"

r = process("./test")
gdb.attach(r)
```
As I understand, it should popup a new shell with gdb already connected right ?
I'm using latest pwntools with Archlinux and AwesomeWM.

**Comment by zachriggle** [comment]
It should, but I’ve got no idea how urxvtc works or it’s command line
flags. I’d recommend reading the man page to see what flags you need to
pass to it to get it to execute a command.

**Comment by bennofs** [comment]
I know what the issue is here. It has to do with the urxvtc parses the commands, and I have a really ugly wrapper script for it here: https://github.com/bennofs/dotfiles/blob/6ead59762afe9f4015fde823467b35f5d52f7fa9/bin/launch-terminal

If you set `context.terminal` to that script and replace `urxvt` by `urxvtc` it should work fine.

I am not 100% sure on the details, but IIRC `urxvtc -e "foo a b c"` does not work and (urxvt will try to execute a binary literally named `foo a b c` and not execute `foo` with `a`, `b` and `c` as arguments as intended) pwntools currently doesn't support calling it as `urxvtc -e foo a b c`

**Comment by zachriggle** [comment]
Sounds like you need to set `context.terminal = ['urxvtc', '-e', 'sh', '-c']`.

**Comment by dummys** [comment]
Hi again,
@zachriggle 
Now urxvtc popup but i get this error:

```python
In [1]: from pwn import *

In [2]: context.terminal = ['urxvtc', '-e', 'sh', '-c']

In [3]: r = process("./test")
[x] Starting local process './test'
[+] Starting local process './test': pid 18654

In [4]: gdb.attach(r)
[*] running in new terminal: /usr/bin/gdb -q  18654
[x] Waiting for debugger
```
Then in the new window:
```
18654: No such file or directory.
gdb-peda$
```
It looks like that pwntools should use `/usr/bin/gdb -q  -p 18654` instead of `/usr/bin/gdb -q  18654`

When using -p now I get these error:
```Attaching to process 22196
warning: process 22196 is a zombie - the process has already terminated
```

With a while(1) in the test binary, I can attach.

```
int main (){

    printf("JE suis untest\n");
    while(1) {
    int i;
    }

}
```

Without it, pwntools seems to fail to stop at the beginning of the binary.

**Comment by dummys** [comment]
@zachriggle there ?

**Comment by 4hiziri** [comment]
Hi @dummys .
I think `process('./test')` executes ./test, so ./test is finished before gdb attaches.
But missing -p option should be bug.

**Comment by dummys** [comment]
ok, was wondering if pwntools stop the execution at beginning of the
binary...

**Comment by zachriggle** [comment]
If that’s what you want, use gdb.debug()

Check out the docs, they are helpful:
http://docs.pwntools.com/en/stable/gdb.html

**Comment by dummys** [comment]
ok, and did you think than -p missing is a bug ?

**Comment by zachriggle** [comment]
There is no need to specify -p

**Comment by 4hiziri** [comment]
Hi, @zachriggle 
I have same trouble.
I think gdb needed -p option when gdb was given pid.
When gdb.attach(some-process), pwntools gives pid to gdb without -p.
So gdb tried open pid as file name and failed.
Why is there no need to specify -p?

**Comment by devneal** [comment]
It seems to work if you use `urxvt` as the terminal rather than `urxvtc`. I got it to work by setting `context.terminal = ['urxvt', '-e', 'sh', '-c']`.
