### ISSUE TITLE
Look for package maintainer on AUR

### ISSUE THREAD

**Issue by jerry73204** [Gallopsled/pwntools#1039]
I'm currently the maintainer of `python2-pwntools` and `python2-pwntools-git` on AUR. I cannot always keep them up-to-date for reasons. I'd like to ask if the pwntools community has interests in package maintenance. Thanks.
Here are the AUR links:
https://aur.archlinux.org/packages/python2-pwntools/
https://aur.archlinux.org/packages/python2-pwntools-git/

**Comment by zachriggle** [comment]
What does the AUR package modify, versus the vanilla distribution?

**Comment by jerry73204** [comment]
They're almost the same except minor changes.
The setup is done by:
`python2 setup.py install --root=${pkgdir}/ --optimize=1 --only-use-pwn-command`
and remove files potentially conflicting with other packages.
`rm ${pkgdir}/usr/lib/python*/site-packages/*.{txt,md}`

You can checkout the PKGBUILD (go to aur link, click "View PKGBUILD" on the right) to find out the detailed installation steps. They're quite short. All what we have to do is to update the version number and depends occasionally.

You may see instructions about PKGBUILD on ArchWiki.
https://wiki.archlinux.org/index.php/PKGBUILD

**Comment by jerry73204** [comment]
The maintainer is now Firmy. The issue could be closed. Thanks.

**Comment by firmianay** [comment]
I'm now the current maintainer, welcome to use Arch Linux and install pwntools from AUR : )

**Comment by zachriggle** [comment]
Yay! Can this issue be closed?

**Comment by jerry73204** [comment]
That's fine.
