### ISSUE TITLE
ssh_process.elf can return incorrect ELF, when ssh_process.executable is included in the ssh cache path

### ISSUE THREAD

**Issue by cpupower** [Gallopsled/pwntools#1047]
When getting the target process' ELF using the `ssh_process.elf` property, a wrong ELF is returned, when the path of the target binary on the remote system is included in the path of the local cache:

Example:
`target.libs()` returns:

```python
{'/somepath/target/target1/somehost.org/lib32/libc.so.6': 4158791680, 
 '/somepath/target/target1/somehost.org/target/target1': 0, 
 '/somepath/target/target1/somehost.org/lib/ld-linux.so.2': 4160602112}
```

while `target.executable` is `/target/target1`.
So `/target/target1` is included in the cache path.

Therefore the condition evaluates to true (just checks whether the string is contained): https://github.com/Gallopsled/pwntools/blob/df7c1fef9d51b4f5fe4fe13c3394168b30e9d7a4/pwnlib/tubes/ssh.py#L343-L345

Maybe the condition should check 
```py
lib.endswith(self.executable)
```
instead. However I am not 100% sure, whether this covers all cases.

**Comment by zachriggle** [comment]
Good catch!  

I'm not sure how to resolve this perfectly, since it's also possible for a binary to rely on another ELF with the same `basename`.  In the meantime, using `basename` is probably as good as we can do -- would you mind submitting a pull request? ❤️ 

Thanks!
