### ISSUE TITLE
DynELF._find_linkmap bug

### ISSUE THREAD

**Issue by a1exdandy** [Gallopsled/pwntools#1056]
https://github.com/Gallopsled/pwntools/blob/b53e58a840c890340fa755a2229c3ff774c5f81e/pwnlib/dynelf.py#L450

Bug after commit bb25140807a4d
Must be:

```python
w.status("r_debug.linkmap %#x" % linkmap)
```

**Comment by zachriggle** [comment]
Merged to `stable`, this should be in the `3.10` release
