### ISSUE TITLE
Feature request for pwnlib.rop.rop.ROP.search(): badbytes parameter

### ISSUE THREAD

**Issue by cgsecurity** [Gallopsled/pwntools#1062]
Some gadget addresses may contains bad chars, ie 0x0a for a ROP used in fgets().
Please consider adding a badbytes parameter to pwnlib.rop.rop.ROP.search().

**Comment by zachriggle** [comment]
You should use `search_iter` for this so that you can do any filtering you'd like.

I added code to `search_iter` to [respect the `badchars` setting of ROP](http://docs.pwntools.com/en/dev/rop/rop.html#pwnlib.rop.rop.ROP) in 76aa34f43d7376eb991398ec7f4b00d39f884496
