### ISSUE TITLE
non-gdb frontend

### ISSUE THREAD

**Issue by bannsec** [Gallopsled/pwntools#1071]
Is there any support for non-``gdb`` front-ends for ``gdb`` debugging module? If not, how would you see it working/where would code mods go in for it?

The ``gdbserver`` backend is almost universally used, however you don't need to have the ``gdb`` front-end to connect to it. I was able to manually connect up to the gdb server using ``radare2``, and I know you can also use it for ``IDA`` and likely other debuggers (Binary Ninja?). Since the front-end in this is partitioned off from the backend, it should be reasonable to make it modular.

**Comment by zachriggle** [comment]
Sure, go nuts.  Create a pull request that modifies [`pwnlib.gdb.binary()`](https://github.com/Gallopsled/pwntools/blob/3.10.0/pwnlib/gdb.py#L423) to check for a `pwntools-gdb` binary first.

You can then define `pwntools-binary` as a shell script in `$PATH` that does anything you want.
