### ISSUE TITLE
User agents sources at useragentstring.com not available anymore

### ISSUE THREAD

**Issue by tandriamil** [Gallopsled/pwntools#1087]
Hi,

The script located in `pwntools/pwnlib/data/useragents/download-useragents.py` fetches the different sources of user agents from various websites.

One of them is useragentstring.com, more precisely `http://www.useragentstring.com/pages/All/` but this link is not anymore available (404 not found).

Thanks

**Comment by zachriggle** [comment]
Thanks for pointing this out!

We only regenerate the user-agents once every 100 years or so, but this is good to know!

If you'd like to submit a Pull Request to fix the script, it'd be greatly appreciated!

**Comment by ZetaTwo** [comment]
Shouldn't this be closed then?

**Comment by tandriamil** [comment]
Yep, I think we can close this now.

**Comment by Arusekk** [comment]
Closed in #1107
