### ISSUE TITLE
Force qemu

### ISSUE THREAD

**Issue by naweiss** [Gallopsled/pwntools#1089]
Is there a way to force `pwntools `to run a process using `qemu `even though I could run on my system?
In spesific, I try to run i386 on x86_64 system, and instead of launching `qemu`, `pwntools` jsut tries to run on my system and fails (I can't install i386 support because I'm not root).

**Comment by zachriggle** [comment]
Yes, the same way you launch any program with command line arguments.

```py
process(['echo', 'foo'])

process(['qemu-x86_64-user', './path/to/your/binary'])
```

Separately, i386 Linux is **entirely unsupported** by Pwntools.  If anything works, it is a happy accident.

**Comment by naweiss** [comment]
* Unsupported?
But isn't 32bit i386 linux is the default context?!

* I ment without explistly writentg the `qemu `command, the same way you can run:
`p = process('./some-arm-exc')
`And `pwntools `automaticly detects that it should run `qemu-arm`
(Why i386 ELF is detected on 64 machine by **default** as **non requiring qemu**?)

**Comment by zachriggle** [comment]
As a target; yes.

As a host OS; no.

32-bit Python is unsupported.

**Comment by naweiss** [comment]
No, the host OS is 64-bit ubuntu.
But `Pwntools` runs 32-bit ELFs on the host, and not using `qemu` for some reason.
