### ISSUE TITLE
[Bug] pwntools select incorrect gadget while doing ROP in x64 binary

### ISSUE THREAD

**Issue by bruce30262** [Gallopsled/pwntools#1118]
#### Environment
* Ubuntu Linux 16.04 64 bit
* pwntools version: 3.12.0

#### Details
![default](https://user-images.githubusercontent.com/4478350/36717178-02ed9e20-1bd8-11e8-95af-5835d65db2db.PNG)

As we can see in the picture, pwntools failed to select the correct gadget address for setting the `rdx` and the `rsi` register. It should be `0x116d69` ( making the gadget become `pop rdx; pop rsi; ret` ), not `0x116d67`. Including the `syscall` instruction might crash the program during the ROP attack.

**Comment by zachriggle** [comment]
Good catch! Can you upload that specific copy of libc? Just rename it to `.jpg` and Github will let you drag and drop it.

**Comment by bruce30262** [comment]
@zachriggle here's the file. It's actually libc-2.24 from Ubuntu 17.04 64 bit .
![libc so 6](https://user-images.githubusercontent.com/4478350/36770939-4c28133a-1c88-11e8-85e3-c7d20fc9bdcc.jpg)

**Comment by bruce30262** [comment]
@zachriggle any update on this ?  

Also If you don't mind I would like to ask about the release date of pwntools 3.13  
It seems it has been delayed for about 2 months now  
Is everything OK ?

**Comment by zachriggle** [comment]
Development cycles are pretty sparse currently. Tests are broken because
Travis made a bunch of changes, and neither I nor @idolfhatler have time to
dedicate — we’d love to see some new contributors step up and fill the void.

**Comment by bruce30262** [comment]
@zachriggle I think I found the root cause:

https://github.com/Gallopsled/pwntools/blob/20cb04984ae9687de3f192c76e1cfa405b00665b/pwnlib/rop/rop.py#L509-L517

The `setRegisters` method use the following rules to choose the best gadget for the `touched` registers:  
1. `if old is gadget`: If we have a new gadget for the touched registers  
2. `old.move > gadget.move`: If the new gadget requires less stack space than the old gadget  

However these rules do not handle the following case:  

For touched registers `(rdx, rsi)`, it will first choose `syscall; pop rdx; pop rsi; ret` as its best gadget. Then when it comes to gadget `pop rdx; pop rsi; ret`, it will ignore this gadget because **both gadget require same stack space ( `gadget.move` are both `0x18` )**

-----------------------------------

I'm working on a patch right now. Here are the rules I would like to apply to `setRegisters`:  
1. If we have a new gadget for the touched registers, choose it.  
2. If the new gadget requires less stack space than the old gadget, choose it.  
3. **If both gadgets require same stack space, choose the one with less instructions**.

The priority is 1 > 2 > 3, since we usually care more about the stack space than the instruction length.  

What do you think ?

**Comment by zachriggle** [comment]
Thanks for looking into this, @bruce30262!

I think that's a good optimization in general, since less instructions will generally be preferred, and it should work around the "syscall" issue.

Separately, I think `setRegisters` should just discard any instruction sequences that include "syscall" or "int XX" instructions.  We don't want those in `setRegisters`.

**Comment by bruce30262** [comment]
@zachriggle the PR is ready, which branch should I create against to ?
(edit : after I check the PULL_REQUEST_TEMPLATE.md, I think I'll create a PR against the stable branch.)

**Comment by bruce30262** [comment]
PR created ( #1156 ), please take a look !

**Comment by bruce30262** [comment]
Since the PR has been merged I'm closing the issue
