### ISSUE TITLE
gdb.debug error on 64bit when it handles 32bit elf.

### ISSUE THREAD

**Issue by combab0** [Gallopsled/pwntools#1126]
gdb.debug handle 64bit properly but there is gdb error when it handles 32bit binary.

```python
from pwn import gdb
io = gdb.debug('./memcpy')
```
test server : Ubuntu 16.04.4 LTS 64bit
test code: http://pwnable.kr/bin/memcpy.c
gcc -o memcpy memcpy.c -m32 -lm : it works
gcc -o memcpy memcpy.c -lm : it doesn't work

gdb error
```
/tmp/pwnTCtlDj.gdb:3: Error in sourced command file
```

**Comment by zachriggle** [comment]
Debugging works for me.  I expect something on your system is configured non-standard.

Can you take a look at the issue [template](https://github.com/Gallopsled/pwntools/blob/dev/.github/ISSUE_TEMPLATE.md)?  Try in the Docker image for sure, but I at least need the debug output to know what went into the gdb script.

**Comment by heapcrash** [comment]
This is two years old, closing this issue since I can't reproduce
