### ISSUE TITLE
in pwnlib.term.term, the definition of function `goto` causes SyntaxError

### ISSUE THREAD

**Issue by j178** [Gallopsled/pwntools#1128]
https://github.com/Gallopsled/pwntools/blob/1cb05021574d17be33ec3738e4ed19b793199536/pwnlib/term/term.py#L167

**Comment by zachriggle** [comment]
You’re using Python3.

Pwntools does not support Python3

**Comment by Arusekk** [comment]
Actually this was already solved in #1119
