### ISSUE TITLE
docker gdb attach

### ISSUE THREAD

**Issue by letitbezh** [Gallopsled/pwntools#1140]
I have make a docker about pwntools.
But,when i use gdb.attach it always wait for debugger . i have install tmux and set context.terminal = ['tmux', 'splitw', '-h']
[+] Starting local process './srop_test': pid 323
[*] '/root/ctf/srop_test'
    Arch:     i386-32-little
    RELRO:    Partial RELRO
    Stack:    No canary found
    NX:       NX enabled
    PIE:      No PIE (0x8048000)
[*] running in new terminal: /usr/bin/gdb -q  "./srop_test" 323 -x "/tmp/pwnV4AQFq.gdb"
[*] Waiting for debugger

can you give me some question ？

**Comment by letitbezh** [comment]
sorry ， some suggestion。。。

**Comment by Arusekk** [comment]
Maybe you are using `pwntools` outside of `tmux`?
Also, could you attach the output of the script with `context.loglevel` set to `'DEBUG'`. This would be helpful.

**Comment by vmayoral** [comment]
@letitbezh I stumbled on the same issue and my problem was that i wasn't running the python script **within** `tmux`.

Try the following:
```
docker run --privileged -v /Users/blah/basic_cybersecurity:/tutorial -it pwnbox:latest # your container
tmux
<your-script>
```

I got it that way (thanks @Arusekk).
<img width="1199" alt="captura de pantalla 2018-04-22 a las 20 12 43" src="https://user-images.githubusercontent.com/1375246/39098344-9589ded6-4669-11e8-930d-d2f87c0f4fec.png">

**Comment by zachriggle** [comment]
Debugging requires ptrace.

Docket requires --privileged to use ptrace.
