### ISSUE TITLE
GDB Warning: not running or target is remote

### ISSUE THREAD

**Issue by Acebond** [Gallopsled/pwntools#1149]
Hello,

This issue is only on Ubuntu 18.04 LTS as far as I can tell. When debugging a process with `pwn.gdb.debug`, gdb reports `Warning: not running or target is remote` and does not display the registers, disassembly and stack. 
![image](https://user-images.githubusercontent.com/6915160/39899687-b1012b56-5500-11e8-8480-93eb4a9b81e9.png)

Test script I'm using. This happens when debugging any executable. That problem only exists on debug() and not attach(). 
```
#!/usr/bin/env python2
import pwn

pwn.context.terminal = ['tmux','splitw','-h']
p = pwn.gdb.debug('ps')
p.interactive()
```
Example of executing the above script. 
![image](https://user-images.githubusercontent.com/6915160/39899752-07e2b2d2-5501-11e8-9976-16d1b6d86926.png)

I expect my gdb to look like this: I've used attache() instead of debug().
![image](https://user-images.githubusercontent.com/6915160/39899931-e816e5d0-5501-11e8-98fa-e02511df6a3e.png)

**Comment by zachriggle** [comment]
Does it work if you remove your gdbinit / disable PEDA?

**Comment by Acebond** [comment]
Hi,

Thanks for the suggestion. It was just peda thinking the target was remote. I've hacked together a fix by making the peda function is_target_remote() always return false.

It was because `info program` returned `Debugging a target over a serial line.` which peda uses to determine in the program is remote. 
```
gdb-peda$ info program
Debugging a target over a serial line.
Program stopped at 0x804858c.
It stopped after being stepped.
Type "info stack" or "info registers" for more information.
```

Thanks.
