### ISSUE TITLE
Spawned GDB attach can't view memory mappings

### ISSUE THREAD

**Issue by syndrill** [Gallopsled/pwntools#1153]
```python
from pwn import *

r = process('./bf')

context.terminal = ['terminator', '--new-tab', '-x']

gdbcmd = '''
b *0x08048774
'''

gdb.attach(r, gdbcmd)
...
```
As you can see this actually works and spawn a new tab in terminator, but in gdb I can't read/write anything to memory.
# Can't view memory mappings
```
(gdb) c
Continuing.

Breakpoint 1, 0x08048774 in main ()
(gdb) x/wx 0x804a080
0x804a080 <p>:	Cannot access memory at address 0x804a080
(gdb) info proc mappings
process 14456
Mapped address spaces:

	Start Addr   End Addr       Size     Offset objfile
(gdb) 
```
Maybe, somewhat helpful to note, I just changed my linux vm distro to Ubuntu 18.04 recently, this doesn't happen before.

**Comment by syndrill** [comment]
This actually works now. I don't know whats happening, but I've updated using `apt update && apt upgrade` this morning and the problem still exists, Update once again this night and it's working as is while there isn't even any updated package while doing `apt upgrade`.

**Comment by zachriggle** [comment]
Glad everything worked out! Let us know if there are any more issues ❤️
