### ISSUE TITLE
How can I simulate the ctrl+d？

### ISSUE THREAD

**Issue by SoWhereAreYou** [Gallopsled/pwntools#1161]
Hello，I am a chinese，so I am sorry my english is not good.
I‘m doing a CTF challenge and I want to leak a address.However ，I found what my enter would destory a pointer in memory.So I want to send ctrl+d.But I find \x04 is not work.
I had seen your old answer,using pty.However it seem not work .
The code like this
---------------------------------------------------------
io = process('./secretgarden',stdin=PTY,raw=False)
raise_flower(0x400,chr(tty.CEOF),'9999')
---------------------------------------------------------
Python said the PTY is not found.

**Comment by zachriggle** [comment]
By default, Pwntools creates a PTY and disables all terminal control code emulation (a "raw" PTY) when invoking `process()`.  The default arguments are:

```py
process(..., stdout=PTY, stderr=STDOUT, raw=True)
```

You will want to change `raw` to be `False`.  More information is available in the [documentation](http://docs.pwntools.com/en/stable/tubes/processes.html) although there's not very much about those features.

The caveat here is that by enabling `raw=True` you will have issues sending characters like `\x08` which is **backspace**.

**Comment by SoWhereAreYou** [comment]
Thank you ,you are so kind but can I use 'raw =false' then in next line change  it to 'raw=true'
