### ISSUE TITLE
v3.12.1 release

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#1170]
We should cut this release because #1168 (fixed on `stable`) is causing lots of issues for people

**Comment by zachriggle** [comment]
I've updated the changelog in b7609ae4 for this specific bugfix release

**Comment by zachriggle** [comment]
We are very behind on releases, which is a separate issue of time / effort -- but I think we can cut this single point-release.

**Comment by bruce30262** [comment]
@zachriggle @Idolf any update on this ? It's been very quite here lately :/
