### ISSUE TITLE
Add support for coredumpctl?

### ISSUE THREAD

**Issue by jonasbb** [Gallopsled/pwntools#1178]
I would like to use the corefile functions of pwntools on Fedora. Fedora uses coredumpctl to save the corefiles. I guess this could work like the existing apport support.

I could create a pull request, if there is interest to support this.

**Comment by zachriggle** [comment]
Sure, but I'd expect the Pull Request to come with supporting documentation since I'm unfamiliar with the mechanism and how it works.

**Comment by jonasbb** [comment]
The pull request for this is merged, so this can be closed now.
