### ISSUE TITLE
Getting an installation error after installing pwntools in Debian.

### ISSUE THREAD

**Issue by nonsens3** [Gallopsled/pwntools#1192]
Hey, today I followed the instructions to get pwntools in my debian-based kali linux rolling. Now i'm getting a library error somewhere and I'm not able to solve it by myself. I tried to get help via IRC but was unsucessful.

asciinema error : https://asciinema.org/a/9tcTP7b3osrcPo4i084vmcDPp
pip install --upgrade pwntools: http://prntscr.com/kpsygf

PS: Month ago I had a Kali Linux rolling working fine with pwntools and pwndbg. I'm very confused right now.

**Comment by ChristosSoteriou** [comment]
I have the same exact issue. I have been using Kali for a few months. Yesterday I made a new VM with Kali and this excact problem showed up.

https://prnt.sc/kpzojn

So I desided to try and install pwntools on my Ubuntu Server VM. I got the same error.

http://prntscr.com/kpzjtf

**Comment by nonsens3** [comment]
Get solved by simply following this issue https://github.com/Gallopsled/pwntools/issues/1189
