### ISSUE TITLE
coredumps: Handle zeroed memory more efficiently

### ISSUE THREAD

**Issue by Mic92** [Gallopsled/pwntools#1211]
At the moment pwntools tries to allocate memory that follows a segment https://github.com/Gallopsled/pwntools/blob/c89bed2555990d35f9cc4804bdedb4a007af5802/pwnlib/elf/elf.py#L937
If a process large virtual memory allocations following the file mapping this fails in python with a MemoryError. This could be worked around by either also create an anonymous memory mapping of the same size or replace the python list by a custom data structure that returns just zero for data beyond the file bounds.

**Comment by Mic92** [comment]
My dirty solution that works for at the moment is to ignore errors in those cases:

```python
try:
    data   += b'\x00' * zeroed
except MemoryError as e:
   pass
```

**Comment by heapcrash** [comment]
We would need a coredump that exhibits this issue to make any fixes.  Closing this out until we have something actionable.

I'm not sure how we can handle ran-out-of-memory situations, if the Corefile takes up more memory than we have I'm not sure silently ignoring it is the right answer.

A Pull Request with tests would be welcomed!

**Comment by Mic92** [comment]
I was not proposing my hack as the solution. A better way would be to memory map the coredump or make the data structure sparse.

**Comment by Arusekk** [comment]
The data structure was made sparse last month. Note that, however, reading a sparse file with read() makes no sense anyway. You can read portions of virtual memory using elf.unpack() and friends.
