### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Alphabay495** [Gallopsled/pwntools#1212]
so ive tried to install it using the instructions

$ git clone https://github.com/Gallopsled/pwntools
$ pip install --upgrade --editable ./pwntools

but it comes up with a massive error and wont install

**Comment by Inndy** [comment]
Are you using macOS Moajve and does the error come from libcapstone? If so, check this issue: https://github.com/aquynh/capstone/issues/1235 and try this solution: https://gist.github.com/Inndy/cc9f725c22f23fe87182fd895e7e7ff3

**Comment by Alphabay495** [comment]
I’m using parrot os

**Comment by Inndy** [comment]
I think you should provide detailed error message so we can help to diagnose what happened.
