### ISSUE TITLE
Remote Debugging

### ISSUE THREAD

**Issue by clark-ja** [Gallopsled/pwntools#1213]
Hello,

it might be, that I'm just not seeing something here but I have been on this since a long while now and tried it on several machines so it appears to me that it is a issue of pwntools itself. I''m sorry if I'm mistaken...

gdb.attach() doesnt seem to work as expected when passing it a socket as an argument:

`io = remote(host, port)`
`gdb.attach(io)`

When the host is not localhost then the following error message is returned:
"[ERROR] could not find remote process (host:port) on this machine"

This problem also affects the `pwn template` command.

cheers,
yakamoz147

**Comment by zachriggle** [comment]
Yes, when the host is not localhost you can't debug the process.

Could you explain where the process is running, and how you set up the
debugger without pwntools?
