### ISSUE TITLE
hosting problems

### ISSUE THREAD

**Issue by Boxvictor** [Gallopsled/pwntools#1215]
Dunno if that are the way to report a broken link on the pwntools docs or u have a problem with the hosting, but  
https://pwntools.readthedocs.io/en/stable/dynelf.html?highlight=dynelf --> works 
http://docs.pwntools.com/en/stable/dynelf.html?highlight=dynelf --not work
some links using the search on the readthedocs.io  point to pwntools.com , like dynelf

![captura de pantalla -2018-10-25 13-32-25](https://user-images.githubusercontent.com/40866784/47497655-13c37400-d85b-11e8-94b4-07c36564b376.png)

Regards

**Comment by zbeekman** [comment]
pwntools.com is completely down AFAICT

**Comment by buckle2000** [comment]
Yeah, it is down now.

**Comment by zachriggle** [comment]
The domain expired while I was on vacation due to a billing issue.  I've fixed it and it should be back up in a few minutes.
