### ISSUE TITLE
Can't correcly execute pwntools

### ISSUE THREAD

**Issue by stvreumi** [Gallopsled/pwntools#1231]
Hello, I got a very weird issue about pwntools.
I recently want to install the tool to do my homework, but it always give me error when I run script:
```
Traceback (most recent call last):
  File "pwn.py", line 1, in <module>
    from pwn import *
  File "/home/pwntools/pwn.py", line 2, in <module>
    r = remote("XXX", X)
NameError: name 'remote' is not defined
```
I have try install and launch it on ubuntu 14  & 16 docker container. I also ty the docker image you give in the issue template. It also blame the same error message.
This tool can only work on my DigitalOcean **ubuntu 16.06 droplet machine**. All other platform I have tired can't work.(I have tried freebsd, ubuntu 16&18 on the DigitalOcean)
If I just using the interactive mode after install, the tools may still work correctly. But after I write the code into script and run. It will blame me the message. And when I back to interactive mode and run, the tool can't work. When I import `pwn` it will give me the message above.

My test script in the first two lines like this:
```python
from pwn import *
r = remote("XXX", X)
```

I using **MacOS Mojave** to test all above. I have tried to install this on my laptop, but it didn't work. So I try other platform and container. But it still don't work.
Is this relevant to my OS or my code?

**Comment by Arusekk** [comment]
Rename your script to whatever else name. Currently `from pwn import *` imports itself.

**Comment by zachriggle** [comment]
@Arusekk is correct

**Comment by stvreumi** [comment]
Thanks @Arusekk , I didn't consider this....
Sorry for asking a silly question...

**Comment by fc8** [comment]
@stvreumi You're not alone - -|||
