### ISSUE TITLE
'from pwn import *' fails when one of the command line args is a Base64 string (or has more than one equal sign)

### ISSUE THREAD

**Issue by toomanybananas** [Gallopsled/pwntools#1249]
The argument parsing functionality invoked by `from pwn import *` causes an error when one of the command line arguments has more than one equal sign:
`echo "from pwn import *\nprint('hello world')" > test.py`
`python test.py afdsa==`

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from pwn import *
  File "/usr/local/lib/python2.7/site-packages/pwn/__init__.py", line 6, in <module>
    pwnlib.args.initialize()
  File "/usr/local/lib/python2.7/site-packages/pwnlib/args.py", line 197, in initialize
    arg, value = arg.split('=')
ValueError: too many values to unpack
```

https://github.com/Gallopsled/pwntools/blob/dev/pwnlib/args.py#L197 probably just needs to be changed to `if arg.count("=") == 1:`

**Comment by zachriggle** [comment]
First, the case of multiple `=` signs creating an exception is an actual bug, thank you for the report.  I'll create a fix for this soon.

However, if the bug were not there, the current functionality would be that `pwnlib.args['asdf'] == '='` would be `True` and that item would be removed from `sys.argv`.

This is a unfortunate limitation of using the "kitchen sink" `from pwn import *` mechanism with the current `args` implementation.

You can avoid this mechanism by using `import pwnlib.foo.bar` explicitly for each item you want to use, e.g. 

```py
from pwnlib.tubes.remote import remote`
```

Separately, you can do any necessary processing on `sys.argv` *before* you `from pwn import *`.

A third option might be to create a pull request to add support to `args.py` to stop looking when it encounters e.g. `--` or is disabled entirely when e.g. `PWNLIB_NO_ARGS=1` is set in the environment.

A final "HACKHACKHACK" work-around solution would be to do:

```
import pwnlib.args
pwnlib.args.initialize = lambda: None
from pwn import *
```

**Comment by zachriggle** [comment]
This is fixed in `stable` and will be addressed in the next bug-fix.
