### ISSUE TITLE
Pull request #1223 broke `dupio`

### ISSUE THREAD

**Issue by RobertLarsen** [Gallopsled/pwntools#1256]
#1223 uses the `loop` instruction for calling `dup2` three times on file descriptor 2, 1 and 0, however this won't work since `loop` will decrement `ecx` which doubles as the file descriptor by one and jump to the beginning of the loop UNLESS `ecx` has reached zero. This means that only file descriptor 2 and 1 will be duplicated.

The following `strace` output shows `findpeersh` which fails:

```
[pid  7391] read(4, "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"..., 4294967256) = 419
[pid  7391] getpeername(0, 0xfffa53c4, 0xfffa53c8) = -1 ENOTSOCK (Socket operation on non-socket)
[pid  7391] getpeername(1, 0xfffa53c4, 0xfffa53c8) = -1 ENOTSOCK (Socket operation on non-socket)
[pid  7391] getpeername(2, 0xfffa53c4, 0xfffa53c8) = -1 ENOTSOCK (Socket operation on non-socket)
[pid  7391] getpeername(3, 0xfffa53c4, 0xfffa53c8) = -1 EBADF (Bad file descriptor)
[pid  7391] getpeername(4, {sa_family=AF_INET, sin_port=htons(36612), sin_addr=inet_addr("16.0.0.0")}, [16]) = 0
[pid  7391] dup2(4, 2)                  = 2
[pid  7391] dup2(4, 1)                  = 1
[pid  7391] execve("/bin///sh", ["sh"], NULL) = 0
```

Since stdin has not been duplicated the shell will have no input and it will exit immediately. #1223 should be rolled back before a new release will be out.

**Comment by zachriggle** [comment]
Reverted in 431cbddc
