### ISSUE TITLE
`disasm()` creates excess lines when `byte=0` on long instructions

### ISSUE THREAD

**Issue by Arusekk** [Gallopsled/pwntools#1263]
This can be seen in very long instructions, like this one:

```py
>>> print(disasm(unhex('656664676665400F18A4000000000051'), byte=0, arch='amd64'))
   0:   gs data16 fs data16 rex nop/reserved BYTE PTR gs:[eax+eax*1+0x0]
   7:   
   e:   
   f:   push   rcx
```

This can be fixed by passing `--no-show-raw-insns` to `objdump`. A pull request on its way.

**Comment by zachriggle** [comment]
Thanks!  I'm curious how you came across this, it's likely a use-case we didn't consider fully.

**Comment by Arusekk** [comment]
So I guess the PR should go against dev, as it is just an enhancement? Or should it be a bug fix on stable?
