### ISSUE TITLE
Can't use any command in pwndbg which rely on pwntools

### ISSUE THREAD

**Issue by odoo-slnee** [Gallopsled/pwntools#1269]
https://github.com/Gallopsled/pwntools/blob/5fa4fcd051ee75fe9df548ea1adced44ed579ec8/pwnlib/term/term.py#L168

I can't execute any pwntools commands thru pwndbg tool because of this bug.

File "/usr/local/lib/python3.6/dist-packages/pwnlib/term/term.py", line 167
    def goto((r, c)):
                   ^
SyntaxError: invalid syntax

I propose to change it to:

def goto(args):
    r, c = args

BTW, I'm using python3

**Comment by Arusekk** [comment]
Please try the dev3 branch: https://github.com/Gallopsled/pwntools/tree/dev3
