### ISSUE TITLE
pwn template support for ida server

### ISSUE THREAD

**Issue by Trolldemorted** [Gallopsled/pwntools#1270]
Right now I am manually editing the generated templates to start an ida server when running locally. What do you think of an IDA parameter (like GDB), which starts the appropriate ida server with the correct params?

**Comment by heapcrash** [comment]
I think this is something that Pwntools will not ever support, we have good support for GDB and recommend that to everybody.

If you're willing to donate a Linux IDA Pro license for testing via continuous integration, then we can reopen this.
