### ISSUE TITLE
gdb.debug() - `exe` parameter is not respected 

### ISSUE THREAD

**Issue by elklepo** [Gallopsled/pwntools#1273]
Given executable:
```
$ cat main.c
int main()
{
    while(1);
}
$ gcc main.c -o a.out
```
I'd like to run and debug this binary with **modified argv[0]**. First, I've tried:
```
from pwn import *
t = process(executable='./a.out', argv=['fake_argv[0]', 'argv[1]'])
gdb.attach(p)
t.interactive()
```
and everything works great - argv[0] is properly replaced in process.

Due to process of real binary I want to debug ends before `gdb.attach()` has time to be called I tried to use `gdb.debug()`:
```
from pwn import *
t = gdb.debug(exe='./a.out', args=['fake_argv[0]', 'argv[1]'])
t.interactive()
```

but I get error:
> Traceback (most recent call last):
>   File "./exp.py", line 4, in <module>
>     t = gdb.debug(exe='./a.out', args=['fake_argv[0]', 'argv[1]'])
>   File "/usr/local/lib/python2.7/dist-packages/pwnlib/context/__init__.py", line 1395, in setter
>     return function(*a, **kw)
>   File "/usr/local/lib/python2.7/dist-packages/pwnlib/gdb.py", line 454, in debug
>     port = _gdbserver_port(gdbserver, ssh)
>   File "/usr/local/lib/python2.7/dist-packages/pwnlib/gdb.py", line 258, in _gdbserver_port
>     gdbserver.pid   = int(process_created.split()[-1], 0)
> ValueError: invalid literal for int() with base 0: 'found'

Further investigation showed that `gdb.debug()` still tries to execute binary form `args[0]`, in this example `"fake_argv[0]"`. It seems that `exe` parameter is not respected.

I need some kind of temporary solution while this issue occurs - is there any option to yield process created with `process()` to attach to it before this process starts execution?

**Comment by goreil** [comment]
What is the issue with Pull request #2024?

If noone is working on it I have a few ideas that I want to test.

**Comment by peace-maker** [comment]
I think it doesn't keep the environment variables in the specified order for python versions not keeping the insert order on dicts from Arusekk's comment, but lets discuss this in that PR please. If @giladreti doesn't have time to work on it anymore, you're more than welcome to open your own PR!

**Comment by giladreti** [comment]
I don't think I will have time to work on it anytime soon. I do agree with the response on my PR that we should probably use the same process customization method as with normal exec's (via a python script exec'ing our program at the end), as it will give us more feature support for free.
