### ISSUE TITLE
Pwntools dependencies out of date?

### ISSUE THREAD

**Issue by flyn-org** [Gallopsled/pwntools#1280]
I maintain the Fedora package of pwntools (python2-pwntools). I have recently found that an upgrade to Fedora's python2-sortedcontainers package leaves pwntools with an unrealized depedency; pwntools requires sortedcontainers<2.0 in requires.txt, but Fedora provides 2.1.0.

Fedora has also dropped python2-tox. Thus the requirement of tox>=1.8.1 also causes a problem. After looking through the source code, I did not see where pwntools makes use of the tox package. Fedora still provides python3-tox, and it also provides the tox program.

This can all be resolved using PIP. However, I would like to continue providing a proper Fedora packages.

A cursory run of checksec and an import of the pwn module into a running Python interpreter works fine with sortedcontainers 2.1.0 and without python2-tox.

**Comment by ZetaTwo** [comment]
"sortedcontainers<2.0" has been changed to just "sortedcontainers" in the dev3 branch.

The remaining question is then "is tox required?"

**Comment by soltysek** [comment]
As far as I noticed tox looks like abandoned. If you try to run test via tox they will fail. So probably this dependency can and should be removed.

**Comment by Arusekk** [comment]
Would you mind submitting a pull request with simplified dependencies?

**Comment by soltysek** [comment]
No problem, I'll try to do it still today.
