### ISSUE TITLE
Wrong gdbscript generation when using `gdb.debug()`

### ISSUE THREAD

**Issue by mzr** [Gallopsled/pwntools#1294]
### Description

This issue is explained [here](https://github.com/pwndbg/pwndbg/issues/623), as a pwndbg issue, because I'm not really sure whether it's pwntools or pwndbg bug.

**Comment by Arusekk** [comment]
This was fixed in pwndbg/pwndbg#624

**Comment by mzr** [comment]
@Arusekk How about second `file` command? Is it on purpose? I'm worried this could potentially cause some other issues in the future (eg with other gdb extensions, different thatn pwndbg).

```
[DEBUG] Wrote gdb script to '/tmp/pwnSyBMn1.gdb'                         
    file /home/mzr/debug/bin                                             
    target remote 127.0.0.1:35135                                        
    file /home/mzr/debug/bin  
```

**Comment by Arusekk** [comment]
Well, I don't know if it is on purpose, but I guess it doesn't break anything under proper settings
