### ISSUE TITLE
gdb.attach loses symbols' address in PIE binary

### ISSUE THREAD

**Issue by qaqmander** [Gallopsled/pwntools#1314]
I'm weak in English, and apologize for that first.

When I use gdb.attach in process which was created by PIE binary, I would get all symbols in wrong position. I make some effort to solve it and find gdb command "file [filename]" causes it.

relative code(line 725, pwnlib/gdb.py):
```
if exe:
    # The 'file' statement should go first
    pre = 'file %s\n%s' % (exe, pre)
```

In my situation, the filename already in gdb command, namely ```/use/bin/gdb -q filename pid -x command_file```, so it's unnecessary to use gdb's ```file``` command. In one word, it's good for me if user can choose whether add ```file [filename]``` to the first of pre or not.

I have checked the code in recommanded docker environment, used apt install vim and gdb, and add code to print cmd in gdb.py, I got 'file ./a.out' so it seems like it has not been improved.

I read gdb's documentation but found good solutions to it. And did some search in stackoverflow and find some relative question but nothing helpful for me. I'm sorry for I don't understand gdb's command ```file``` well so I have to try to fix it in pwntools.

Thank you so much.

**Comment by zachriggle** [comment]
We still have to `file` the local file for remote debugging, because not all `gdbserver` are fully-featured.

For example, `qemu-arm` cross-debugging generally does not support the RemoteIO subsystem required for pulling the file down, and generally gets the filename incorrect anyway (since GDB thinks it's debugging `qemu-arm` itself and not the target binary).

**Comment by bet4it** [comment]
We can use the `file` command, but must do it before `target remote`. My pull request #1323 only remove the `file` command after `target remote`.
And we have already put the executable path in the `gdb` command, which seems to have same effects with `file`. So we may delete all the `file` command.

**Comment by qaqmander** [comment]
Thank you so much. Maybe it's better to discuss this in pr [#1323](https://github.com/Gallopsled/pwntools/pull/1323).
