### ISSUE TITLE
[Dev3] Python 3 requires excessive .encode() & .decode()  to perform IO ops

### ISSUE THREAD

**Issue by TAbdiukov** [Gallopsled/pwntools#1315]
Warning: Issue found on Ubuntu 1**8**.04 LTS (Python 3.6) and Debian 6.0.10 (Python 3.7.3)

Whenever I need to perform IO operations with PY3, I always need to wrap code in .decode(ENCODING) and .encode(ENCODING). For example
```
buf = io.recvline().decode(encoding)
io.sendline(result.encode(encoding))
```
At times, the statements go as far as to
```
soup = io.recvuntil("}".encode(encoding)).decode(encoding)
```

I wonder, is such behaviour expected, and most importantly, intended in PY3? Thanks

**Comment by Arusekk** [comment]
You can use:
```py
soup = io.recvuntil(b"}")
```

and then the result will by a `bytes` object, suitable for use everywhere else.

Just try not to use `str` at all and instead use `bytes` when `str` is not absolutely necessary. (for literals it is `b'foobar'` instead of `'foobar'`)

**Comment by zachriggle** [comment]
This is something I’d like to hide from the user via attempting to auto-decode as latin-1 where possible.  Eventually.

**Comment by Arusekk** [comment]
Actually, these functions can return only one type at a time (either bytes or str), and I peraonally think that we can introduce something like context.encoding to have the automatic str->bytes translation only done with a utility function using it. It can then default to, say `'auto'`, where it would try latin1, and utf8 when failing (another valid default could be utf8 with errors=surrogateescape, so it could handle environment and commandline arguments from native python). We should though still emphasize in the documentation that bytes are preferred over str. I have more free time now, so I can implement it.

**Comment by TAbdiukov** [comment]
Apologies for lateness

@Arusekk 

I also think that indeed, the encoding and the variable type (bytes or str) should belong to the ~~Nords~~ context() . The oddness of the issue is that as for PY2, one can freely send and receive strings as they are, without any conversions to/from bytes. A few times before I did need to send bytes as-is, but for this purpose there exists "send_raw()", which works flawlessly. So it makes me wonder if 'sending bytes' should be part of the default behaviour of the non-raw send and receive functions

@zachriggle 
> This is something I’d like to hide from the user via attempting to auto-decode as latin-1 where possible.  Eventually.

Off the topic, but you might be solving the problem incorrectly. latin-1 'obscures' code for user, but its clearly not designed to secure what you send/receive. You probably want to do something cryptographic

**Comment by zachriggle** [comment]
@Arusekk Sounds good to me!

**Comment by TAbdiukov** [comment]
Should issue be closed now? Also what is the new syntax?

**Comment by Arusekk** [comment]
tube.recv() and stuff should be used and operate on bytes. But if you really really know what you are doing, you can use tube.recvS() and friends. They return str.
