### ISSUE TITLE
[BUG] TypeError at str(rop)

### ISSUE THREAD

**Issue by 2peopledesu** [Gallopsled/pwntools#1335]
![image](https://user-images.githubusercontent.com/20368824/63226279-0d035480-c213-11e9-97e6-8547331363b8.png)

This is error message
```
TypeError: unsupported operand type(s) for &: 'str' and 'int'
```

**Comment by ysf** [comment]
try
```
payload = 'A' * 32
payload += rop.chain()
```

**Comment by 2peopledesu** [comment]
Thank you for comment

> try
> 
> ```
> payload = 'A' * 32
> payload += rop.chain()
> ```

Thank you for comment, but is it not worked and print same error

**Comment by ysf** [comment]
Can you provide the whole python file, i'd like to look into it.

**Comment by Arusekk** [comment]
Or could you provide last frames of the traceback? I don't know which files you are using. Also, which version of pwntools is that?

**Comment by Arusekk** [comment]
Closing it for now, if it happens with the latest stable pwntools (`pip install git+https://github.com/Gallopsled/pwntools.git@stable`), please reopen.
