### ISSUE TITLE
How to process and attach to a MIPS program using pwntools

### ISSUE THREAD

**Issue by haowayne** [Gallopsled/pwntools#1344]
I can successfully run a MIPS program and attach to it using the following commands in seperate two shells:
qemu-mips-static -L /usr/qemu-linux-mips -g 1234 ./mips_elf

gdb-multiarch ./mips_elf   (then I can remote to localhost:1234 to attach to the program)

How can I do this in python through pwntools ？

Many thanks

**Comment by zachriggle** [comment]
You should use `gdb.attach` after setting the correct context.

```
context.binary = 'mips_elf'
io = gdb.debug(context.binary.path)
io.send(...)
```

You can see more information in the documentation here: https://docs.pwntools.com/en/stable/gdb.html

**Comment by haowayne** [comment]
Many thanks for the answer!
But this simply works for the statically-linked MIPS binary. When I try to run a dynamically-linked MIPS binary, it said /lib/ld.so.1 missing. One way to the solution is to copy relevant MIPS library to the directory. But can I pass some parameters to pwntools to let it know where the library is? As "qemu-mips-static -L /usr/mips-linux-gnu ./mips_elf" tells qemu-mips-static to find the library in the directory "/usr/mips-linux-gnu".

Best regards!

**Comment by zachriggle** [comment]
I recommend reading my ReverseEngineering StackOverflow post to get your
binary to run at all, then under a debugger.

https://reverseengineering.stackexchange.com/questions/8829/cross-debugging-for-arm-mips-elf-with-qemu-toolchain

*Zach Riggle*
