### ISSUE TITLE
Process fileno is invalid

### ISSUE THREAD

**Issue by naweiss** [Gallopsled/pwntools#1354]
The issue occurs on 64-bit Ubuntu 14.04, with pwntools 3.12.2.

The code is:
```python
>>> from pwn import *
>>> p = process('ls')
[x] Starting local process '/bin/ls' argv=['ls']
[+] Starting local process '/bin/ls' argv=['ls'] : pid 2463
>>> p.fileno()
[*] Process '/bin/ls' stopped with exit code 0 (pid 2463)
[ERROR] A stopped process does not have a file number
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/tubes/process.py", line 768, in fileno
    self.error("A stopped process does not have a file number")
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/log.py", line 417, in error
    raise PwnlibException(message % args)
pwnlib.exception.PwnlibException: A stopped process does not have a file number
```
The process can not be used in select.select and considered stopped although no data had been received.

**Note:** The doc at http://docs.pwntools.com/en/stable/tubes/processes.html#pwnlib.tubes.process.process.fileno states:
Returns the file number used for **reading**.
And the stdout fileno is still valid and not empty.

**Comment by ZetaTwo** [comment]
I don't quite get this one. Isn't all resources associated with the process deallocated when the process stops? Why would this work?

**Comment by naweiss** [comment]
I might be tootally wring about this one.
But, I tried to use select with pwnlib processes like so:
```python
from pwn import *
import select

inputs = [process('ls'), process('sleep 100', shell=True), ...]
readables, _, _ = select.select(inputs, [], [])
for proc in inputs:
    print proc.recv()
```
but
`pwnlib.exception.PwnlibException: A stopped process does not have a file number`
is raised

**Comment by ZetaTwo** [comment]
Yes, the `ls` process immediately runs and finishes. When Python reached the line `readables, _, _ = select.select(inputs, [], [])` the process is already gone and the pid released. Why are you trying to run select() on a process that immediately exits? Note that you still can get all the output from the process as shown in this example below.

```
>>> from pwn import *
>>> r=process('ls')
[x] Starting local process '/usr/bin/ls'
[+] Starting local process '/usr/bin/ls': pid 5605
>>> print(r.recvall().decode('ascii'))
[x] Receiving all data
[x] Receiving all data: 0B
[*] Process '/usr/bin/ls' stopped with exit code 0 (pid 5605)
[x] Receiving all data: 188B
[+] Receiving all data: Done (188B)
CHANGELOG.md	 extra		       pwnlib		 TESTING.md
CONTRIBUTING.md  LICENSE-pwntools.txt  README.md	 tox.ini
docs		 MANIFEST.in	       requirements.txt  travis
examples	 pwn		       setup.py
```

Sorry if I'm missing something but why would this work at all? What is the expected behaviour?

**Comment by peace-maker** [comment]
As stated before, you cannot access resources of a stopped process anymore since it doesn't exist anymore. Please rephrase your question and state what you expect to happen if this is still a problem!
