### ISSUE TITLE
Latest version of gdbserver on Kali Linux (debian) is incompatible with latest pwntools

### ISSUE THREAD

**Issue by SakiiR** [Gallopsled/pwntools#1358]
# Pwntools Issue Template

The following snippets does not open  gdb on a tmux side pane :(

```python
#!/usr/bin/env python
# @SakiiR

import pwn

pwn.context.terminal = ["tmux", "splitw", "-h"]


def main():

    payload = ""

    s = pwn.gdb.debug(["bash", "-c", "sleep 3"])

    s.interactive()


if __name__ == "__main__":
    main()
```

**Comment by SakiiR** [comment]
The following gdbserver version fixes the issue:

https://packages.debian.org/jessie/amd64/gdbserver/download
http://ftp.fr.debian.org/debian/pool/main/g/gdb/gdbserver_7.7.1+dfsg-5_amd64.deb

**Comment by Arusekk** [comment]
Please reopen if the issue persists.
