### ISSUE TITLE
LD_PRELOAD not working on Ubuntu18.04

### ISSUE THREAD

**Issue by haowayne** [Gallopsled/pwntools#1360]
I try to run a dynamic-linked program with another libc on my Ubuntu18.04 . So I use the command:
`io = process("./myprogram", env = {'LD_PRELOAD' : 'path of the libc'})` . 
However, the program cannot start properly with error message :
`[*] Process './babystack' stopped with exit code -4 (SIGILL) (pid 16383)` . 
But it actually works on my Ubuntu16.04. So how can I fix it on Ubuntu18.04?

Many thanks!

**Comment by Arusekk** [comment]
The libc you are using might use some CPU instructions not supported by your hardware. What happens of you start it under gdb?

**Comment by Arusekk** [comment]
Please see if #1371 fixes this issue
