### ISSUE TITLE
Respect XDG Base Directory Spec

### ISSUE THREAD

**Issue by alichtman** [Gallopsled/pwntools#1370]
I've noticed `~/.pwntools-cache` files appearing. These should be stored in the XDG Cache directory by default, not in the `$HOME` directory. It'd be nice if there were a way to configure this.

**Comment by Arusekk** [comment]
Would you mind submitting a pull request for this? The default paths are generated by a function in `pwnlib/context/__init__.py`.

**Comment by alichtman** [comment]
https://github.com/Gallopsled/pwntools/blob/faab6ea3dd8806ce693681ca4b7cfb451a335c8c/pwnlib/context/__init__.py#L1232

This is the line that needs to be modified. Don't have time at the moment, but if this hits the top of my priority list at some point in the future, I'll submit a patch.
