### ISSUE TITLE
input() is overwritten with python 2 like input() in python 3

### ISSUE THREAD

**Issue by mateuszdrwal** [Gallopsled/pwntools#1373]
When running a python 3 script that uses pwntools from file, the `input` builtin is overwritten with a function that mimics the python 2 behavior of `input()`, namely running `safeeval.const(input())`. I suppose this is left over from python 2. the issue seems to originate from here: 

https://github.com/Gallopsled/pwntools/blob/5bba036c545cba802b0137de67e3ae90252b647b/pwnlib/term/readline.py#L457

it looks like that whole part of the file is still written for python 2, as `raw_input` is also set while not existing in python 3. this currently breaks some of my scripts since they expect to see a string passed into stdin but it is instead evaled and throws an error.

**Comment by Arusekk** [comment]
On top of my pwntools TODO-list for now
