### ISSUE TITLE
Serialtube Python 3 port, bytes on newline handling

### ISSUE THREAD

**Issue by ZetaTwo** [Gallopsled/pwntools#1397]
The serialtube module is not (properly) ported to Python 3.
Running the following:

```
from pwn import *
r = serialtube(\"/dev/ttyACM0\", baudrate=9600)
r.interactive()
```

Will crash like this:

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/zetatwo/.local/lib/python3.7/site-packages/pwnlib/tubes/tube.py", line 859, in interactive
>     self.send(data)
>   File "/home/zetatwo/.local/lib/python3.7/site-packages/pwnlib/tubes/tube.py", line 754, in send
>     self.send_raw(data)
>   File "/home/zetatwo/.local/lib/python3.7/site-packages/pwnlib/tubes/serialtube.py", line 66, in send_raw
>     data = data.replace('\n', '\r\n')
> TypeError: a bytes-like object is required, not 'str'
> 

`data = data.replace('\n', '\r\n')` needs to work with bytes. I will do a PR on this shortly but posting this already as a reminder to myself.

**Comment by Arusekk** [comment]
Thank you very much!

I must have skipped this by some accident; please keep in mind that the core tubes model is operating on binary data only, and should not need to be aware of str anywhere.
