### ISSUE TITLE
Getting update message again, despite explicitly disabling it

### ISSUE THREAD

**Issue by heinrich5991** [Gallopsled/pwntools#1414]
See also #1348.

I created `~/.pwntools-cache-3.7/update` with the content `never`. Now I'm seeing update messages again. It seems to check `~/.pwntools-cache-3.8/update` now.

Please add a way to permanently opt out of update messages (or get rid of them).

**Comment by Arusekk** [comment]
Please check if [`Arusekk/pwntools@dev`](https://github.com/Arusekk/pwntools) works for you.

**Comment by Arusekk** [comment]
ping @heinrich5991

**Comment by heinrich5991** [comment]
Installed the update, tested it, works fine.

Forgot about providing feedback, sorry about that. :/

**Comment by heinrich5991** [comment]
Thanks for the quick response and patch!
