### ISSUE TITLE
recvuntilS and family of similar functions return bytes not string

### ISSUE THREAD

**Issue by rcslaney** [Gallopsled/pwntools#1438]
As far as I can tell from the function documentation this is meant to decode the string from it's bytes automatically dependent on the given encoding in context.encoding, however it does not in the latest version of pwntools.

Changing https://github.com/Gallopsled/pwntools/blob/904872edc863f610b636eddac1f5abfef0c86284/pwnlib/tubes/tube.py#L1376 to have ._decode instead of ._encode seems to fix the problem.

**Comment by cameronotw** [comment]
hi @rcslaney, I want to help but I am new to contribution here :) Have you some specific use case when string (python3) are better in pwning not bytes? Some byte data cannot be converted without malforming to string, because of variety of encodings afaik. What you think?

**Comment by zachriggle** [comment]
All byte data can be represented as a string with the latin-1 encoding,
which is a 1:1 mapping between bytes and characters.

*Zach Riggle*

**Comment by rcslaney** [comment]
Yeah I'm not saying it's necessarily better but as far as I can tell the whole point of the recvuntilS instead of the recvuntil function is to return a string directly rather than then having to call decode afterwards.

**Comment by Arusekk** [comment]
Closed in #1452
