### ISSUE TITLE
rop.call does not work correctly with complex/nested arguments

### ISSUE THREAD

**Issue by qeirik** [Gallopsled/pwntools#1444]
pwn.rop.rop does not correctly build a chain with nested AppendedArguments

Repeating the example from the docs (context.arch='amd64')
```
>>> rop = ROP(binary, base=0x7fffe000)
>>> rop.call('execve', ['/bin/sh', [['/bin/sh'], ['-p'], ['-c'], ['ls']], 0])
>>> print(rop.dump())
0x7fffe000:          0x26542 pop rdi; ret
0x7fffe008:       0x7fffe030 [arg0] rdi = AppendedArgument(['/bin/sh'], 0x0) (+0x28)
0x7fffe010:         0x12bdc9 pop rdx; pop rsi; ret
0x7fffe018:              0x0 [arg2] rdx = 0
0x7fffe020:       0x7fffe038 [arg1] rsi = AppendedArgument([AppendedArgument(['/bin/sh'], 0x0), AppendedArgument(['-p'], 0x8), AppendedArgument(['-c'], 0x10), AppendedArgument(['ls'], 0x18)], 0x0) (+0x18)
0x7fffe028:          0xe1950 execve
0x7fffe030:   b'/bin/sh\x00'
0x7fffe038:       0x7fffe050 (+0x18)
0x7fffe040:       0x7fffe058 (+0x18)
0x7fffe048:       0x7fffe060 (+0x18)
0x7fffe050:       0x7fffe068 (+0x18)
0x7fffe058:   b'/bin/sh\x00'
0x7fffe060:   b'-p\x00$$$$$'
0x7fffe068:   b'-c\x00$$$$$'
0x7fffe070:   b'ls\x00$$$$$'
```

As it can be seen, pointers in the array have wrong offset by 0x8 bytes.

I was able to correct it in this case with a simple hack of removing the "unnecessary" offset of context.bytes in pwnlib/rop/rop.py 

```
 857             elif isinstance(slot, AppendedArgument):                             
 858                 stack[i] = stack.next                                            
 859                 stack.extend(slot.resolve(stack.next + len(slot) - context.bytes))
```

Without substracting _context.bytes_ the example above works correctly. But I'm not sure if this a proper way since  it may still be required in the other cases.

On a probably related note, AppendedArgument itself does not work as described in the docstring:
```
>>> u = AppendedArgument([[[[[[[[['pointers!']]]]]]]]], 1000)            
>>> u.resolve()                                                          
[1008, 1016, 1024, 1032, 1040, 1048, 1056, 1064, 'pointers!\x00$$$$$$'
```
the actual result:
```
>>> u = AppendedArgument([[[[[[[[['pointers!']]]]]]]]], 1000)            
>>> u.resolve()                                                          
[1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, b'pointers!\x00$$$$$$'
```

Edit: I think I was able to trace the problem more correctly. The issue is still around

`859                stack.extend(slot.resolve(stack.next + len(slot) - context.bytes))`

len(slot) equals AppendedArgument.size, which gives wrong address offset. The correct offset would be calculated based on the total number of pointers that predate the data, something like

`859                stack.extend(slot.resolve(stack.next + len(slot.values) * context.bytes))`

The above still works only for "flat" arguments, i.e.

`[ ['arg1'], ['arg2'],  ['arg3'] ]`

but still wouldn't not work for deeper nested levels, i.e.

`[ ['arg1'], [ ['arg2.1'], ['arg2.2']], ['arg3'] ]`

**Comment by Arusekk** [comment]
Probably closed by #1755.
