### ISSUE TITLE
SSH channel shell() seems to have memory leak

### ISSUE THREAD

**Issue by mcw0** [Gallopsled/pwntools#1445]
Maybe I'm doing something wrong, but this little code seems to have memory leak.

```py
#!/usr/bin/env python3
import sys
import resource
from pwn import *

try:
	test = ssh(user='user', password='password', host='127.0.0.1', port=22, timeout=5, cache=False)
	while True:
		shell = test.shell()
		time.sleep(0.1)
		shell.close()
		log.info("Memory usage: {}".format(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss))
except (Exception, KeyboardInterrupt, SystemExit) as e:
	print(e)
	sys.exit(False)

sys.exit(True)
```

**Comment by Arusekk** [comment]
Probably related #1290

**Comment by zachriggle** [comment]
Does this memory leak still happen if you use this?

```py
with test.shell() as sh:
  time.sleep(0.1)
```

This might be a core Paramiko error, since all that Pwntools does with the `pwnlib.ssh` module is a wrapper around Paramiko.

**Comment by mcw0** [comment]
Yep, same thing.

I also suspect Paramiko actually, not freeing up the closed ssh channel completely.

Not a big deal for me anymore, my fuzzing ended long time ago, but wanted to let you know what I've noticed.

**Comment by zachriggle** [comment]
Thanks, I'll close this out then.  I'm not sure how to troubleshoot memory leaks in Python, so I'm not sure I can even track this down and report upstream.  Luckily, most users won't encounter this as the number of connections spawned in any given Python instance's lifetime is likely < 10.
