### ISSUE TITLE
phd should use a pager if stdout is a TTY, and the output does not fit on one screen

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#1456]
The `phd` command-line tool should check if the number of lines of hexdump'ed data is taller than the current window size (environment variable `$LINES`) is shorter, and should feed its output to a pager (default `less -R`) of `stdout` is a TTY.

**Comment by Arusekk** [comment]
If we plan to support this, we want to use [`shutil.get_terminal_size()`](https://docs.python.org/dev/library/shutil.html#shutil.get_terminal_size)
