### ISSUE TITLE
Binutils Recipes for macOS use 2.25

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#1466]
Binutils is 2.34 is available, with 2.25 being released in 2015.  We should likely update the pwntools-binutils Homebrew recipes (https://github.com/Gallopsled/pwntools-binutils/tree/master/osx) to use the later version.

There is already a Pull Request to update to v2.29.1 here: https://github.com/Gallopsled/pwntools-binutils/pull/4/commits

The effective change needed is to update the URL and update the SHA sum (which is identical in each file).

I would contribute these changes myself, but my employer prevents me from contributing to FOSS.

**Comment by zachriggle** [comment]
We may also want to update the "alternate OSes" section of `binutils.rst` (https://github.com/Gallopsled/pwntools/blob/dev/docs/source/install/binutils.rst) to use the latest version.

**Comment by eljeffeg** [comment]
I created a pull request for the latest binutils 2.34 into chauanchan1116's fork.
https://github.com/chuanchan1116/pwntools-binutils/pull/1/commits/439837a9f7dd7eebd6c653a4160929da4ceb6daf

**Comment by heapcrash** [comment]
The binutils recipes don't seem to matter much anymore since Ubuntu 18.04 and later include pretty much everything that Pwntools supports.

**Comment by Arusekk** [comment]
Closed in Gallopsled/pwntools-binutils#5
