### ISSUE TITLE
A bug in pwntools sys.argv

### ISSUE THREAD

**Issue by H4lo** [Gallopsled/pwntools#1475]
Cannot output something when command line argument is all uppercase,for example:

```
pwntools@7d35983a10b9:~$ cat test.py
from pwn import *

print(sys.argv)

pwntools@7d35983a10b9:~$ python test.py 123 AAA aaa
['test.py', '123', 'aaa']
```

**Comment by Arusekk** [comment]
This is fully intentional, though possibly not opt-in enough. See https://docs.pwntools.com/en/stable/args.html
