### ISSUE TITLE
readuntil() failing/hanging forver on simple binary

### ISSUE THREAD

**Issue by macrl2000** [Gallopsled/pwntools#1480]
actual pwntools on kali (pip install --upgrade pwntools)
kali: Linux kali 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux

```py
from pwn import *

context.log_level = 'debug'

p = process("./test")
p.readuntil("name")
p.interactive()
```

of a simple pwn challenge (only the two printf intresting for the bug)

```c
#include <stdio.h>
#include <stdlib.h>

void welcome(){
        char name[100];
        printf("enter you name : ");
        scanf("%100s", name);
//.....
}

int main(){
        printf("Toddler's Secure Login System 1.0 beta.\n");
        welcome();
        //......
}
```

behaves normal in standard terminal, when using pwntools (python2) it hangs

```
[+] Starting local process './test
': pid 17709
[DEBUG] Received 0x28 bytes:
    "Toddler's Secure Login System 1.0 beta.\n"
```

hangs forever waiting for "name"

any idea ? 

[test.zip](https://github.com/Gallopsled/pwntools/files/4469735/test.zip)

**Comment by zachriggle** [comment]
You need to set `stdin` to be a PTY, otherwise libc will line-buffer the output.

```c
printf("enter you name : "); //<---- No newline
```

```py
>>> p=process('./a.out')
[x] Starting local process './a.out'
[+] Starting local process './a.out': pid 23254
>>> p.clean()
b"Toddler's Secure Login System 1.0 beta.\n"
>>> p=process('./a.out', stdin=PTY)
[x] Starting local process './a.out'
[+] Starting local process './a.out': pid 23357
>>> p.clean()
b"Toddler's Secure Login System 1.0 beta.\nenter you name : "
```

Here are some resources:

https://github.com/zachriggle/pwntools-glibc-buffering
http://docs.pwntools.com/en/stable/tubes/processes.html

See also #798

**Comment by Arusekk** [comment]
You can also see what stdbuf(1) is. (might be possibly unusable with setuid binaries)

**Comment by macrl2000** [comment]
officially sorry for stealing your time !
i read all docs i found and tested a lot before opening this issue, but i did not see 
the solution, thank you for explaining !
