### ISSUE TITLE
Shellcraft: Should have templates for swapping between 32/64-bit on Linux

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#1485]
Currently there are no templates to manage setting `cs` in order to switch between 32- and 64-bit address spaces (and the corresponding syscall tables).

These would be useful for some CTF challenges.

**Comment by Arusekk** [comment]
There already is `shellcraft.i386.linux.i386_to_amd64`, but there is no `amd64_to_i386` counterpart.

**Comment by Arusekk** [comment]
Closed by #1756
