### ISSUE TITLE
macOS qemu-x86_64 missing

### ISSUE THREAD

**Issue by eljeffeg** [Gallopsled/pwntools#1489]
I think this may just be an issue of documentation for macOS in installing components.  I'm running into this issue:
`[!] Neither 'qemu-x86_64' nor 'qemu-x86_64-static' are available`

I've install the prerequisites binutils as described https://docs.pwntools.com/en/stable/install/binutils.html#mac-os-x

I've also did `brew install qemu`.  Not sure what is missing.

**Comment by zachriggle** [comment]
I also see this on my macOS installation.

```
>>> ELF.from_assembly(shellcraft.sh()).process().interactive()
[!] Neither 'qemu-i386' nor 'qemu-i386-static' are available
```

It looks like the `qemu` package does not actually install user-mode emulation binaries, it only installs e.g. `qemu-system-x86_64` for emulating a whole kernel  / VM.  It's not clear if there is a way to get e.g. `qemu-i386` on macOS at all.
