### ISSUE TITLE
Python3: Weird behavior from ROP.raw with short arguments

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#1494]
I'm not sure what's causing this issue, but it looks like `ROP.raw()` does something weird when given one-byte arguments.

This happens on both Python2 and Python3.

## Correct

```py
>>> r=ROP([])
>>> r.raw(32)
>>> print(r.dump())
0x0000:             0x20
>>> r.raw(pack(32))
>>> print(r.dump())
0x0000:             0x20
0x0004:  ' \x00\x00\x00' ' \x00\x00\x00'
>>> print(hexdump(str(r)))
00000000  20 00 00 00  20 00 00 00                            │ ···│ ···│
00000008
```

## Incorrect

```py
>>> r=ROP([])
>>> r.raw('a')
>>> r.raw('b')
>>> print(r.dump())
0x0000:             'aa' 'a'
0x0002:             'ba' 'b'
>>> print(hexdump(str(r)))
00000000  61 61 62 61                                         │aaba│
00000004
```

**Comment by layderv** [comment]
I'll work on this. To confirm, what's the expected output of your second example?

**Comment by zachriggle** [comment]
In both Python2 and Python3, the expected output of `hexdump(str(r))` should be that exactly two bytes are printed out.

In Python2, there are extra `a` bytes.

In Python3, there are extra `a` bytes, as well as `b'` for the `bytes`-prefix.

```
~/g/pwntools ❯❯❯ cat script.py
from pwn import *
r=ROP([])
r.raw('a')
r.raw('b')
print(r.dump())
print(hexdump(str(r)))

~/g/pwntools ❯❯❯ python2 script.py
0x0000:             'aa' 'a'
0x0002:             'ba' 'b'
00000000  61 61 62 61                                         │aaba│
00000004

~/g/pwntools ❯❯❯ python3 script.py
0x0000:            b'aa' 'a'
0x0002:            b'ba' 'b'
00000000  62 27 61 61  62 61 27                               │b'aa│ba'│
00000007
```

**Comment by layderv** [comment]
From:
```
        >>> rop = ROP([])
        >>> rop.raw('AAAAAAAA')
        >>> rop.raw('BBBBBBBB')
        >>> rop.raw('CCCCCCCC')
        >>> print(rop.dump())
```
Do we still expect:
```
        0x0000:          b'AAAA' 'AAAAAAAA'
        0x0004:          b'AAAA'
        0x0008:          b'BBBB' 'BBBBBBBB'
        0x000c:          b'BBBB'
        0x0010:          b'CCCC' 'CCCCCCCC'
        0x0014:          b'CCCC'
```
Or
```
        0x0000:          'AAAA' 'AAAAAAAA'
        0x0004:          'AAAA'
        0x0008:          'BBBB' 'BBBBBBBB'
        0x000c:          'BBBB'
        0x0010:          'CCCC' 'CCCCCCCC'
        0x0014:          'CCCC'
```

**Comment by zachriggle** [comment]
Yes, that looks expected with `context.bits = 32` on Python3.

## Python3 32-bit

```
>>> context.bits=32
>>> rop = ROP([])
>>> rop.raw('AAAAAAAA')
>>> rop.raw('BBBBBBBB')
>>> rop.raw('CCCCCCCC')
>>> print(rop.dump())
0x0000:          b'AAAA' 'AAAAAAAA'
0x0004:          b'AAAA'
0x0008:          b'BBBB' 'BBBBBBBB'
0x000c:          b'BBBB'
0x0010:          b'CCCC' 'CCCCCCCC'
0x0014:          b'CCCC'
```

## Python3 64-bit

```
>>> context.bits=64
>>> rop = ROP([])
>>> rop.raw('AAAAAAAA')
>>> rop.raw('BBBBBBBB')
>>> rop.raw('CCCCCCCC')
>>> print(rop.dump())
0x0000:      b'AAAAAAAA' 'AAAAAAAA'
0x0008:      b'BBBBBBBB' 'BBBBBBBB'
0x0010:      b'CCCCCCCC' 'CCCCCCCC'
```

**Comment by layderv** [comment]
Thanks. I've updated the pull request.
Maybe the commit name is a bit misleading. Feel free to adjust it or ask me to.

**Comment by Arusekk** [comment]
@zachriggle
> In both Python2 and Python3, the expected output of `hexdump(str(r))` should be that exactly two bytes are printed out.
> 
> In Python2, there are extra `a` bytes.
> 
> In Python3, there are extra `a` bytes, as well as `b'` for the `bytes`-prefix.

This is because you use `str(b)` instead of `bytes(b)` or whatever else. I personally tend to use `python3 -b` or even `python3 -bb` to make sure no such mistakes are made (easy to miss, hard to find; such bugs are so common that I recognize this pattern almost in a reflex action).

When you really mean `repr()` instead of `str()` (which is what you accidentally did), just use `repr()` instead (or `ascii()` which is just `repr()` but different).
We might want to use `-bb` flag on our CI, too.

**Comment by zachriggle** [comment]
Today I learned about -b and -bb!  Neat stuff :)

*Zach Riggle*
