### ISSUE TITLE
Need new release for py3 issues

### ISSUE THREAD

**Issue by bannsec** [Gallopsled/pwntools#1497]
I'm running into issues utilizing pwntools with py3. These issues have been solved in the dev branch, however there's no good way at the moment to require pwntools as a package in my library and have it function.

The main issue is the `file()` call in term/keys that was fixed a few months back. The fix works, but normal package requiring does not.

Some workarounds I've tried:
 - using `patch` command to patch the keys file after install (messy and prone to breaking)
 - using "@<url>" in requires line in setup.py (works only when installing locally, as by default pip will not allow package installs from sites external to pypi if you are installing from pypi)
 - subprocess("pip install <pwntools_beta_url>") also prone to breaking based on how it's being installed.

It would be very helpful to have a more current push, even if it's marked alpha or something.

**Comment by Arusekk** [comment]
I apologise for this, I have had quite a busy time and have been planning on cutting a release for a while now. As soon as I have a few hours, I will do it.

Pwntools is now heavily understaffed for so big a project (number of SLOC is impressive).

**Comment by Arusekk** [comment]
Done. I am currently making sure the release process gets more automated. GitHub actions usage is quite arcane though, and **has no easy way to test workflows locally** (I support the view of https://noyaml.com and especially feel like in [this link](https://tinyurl.com/lessons-in-over-engineering)).

Sorry for the frustration, it is widely unrelated to this issue. I am just stunned that some feel like inventing a brand new ill-considered language and not providing at least a lint tool for it.

**Comment by bannsec** [comment]
Feel ya. I spent quite a while getting my own github actions to work. I
tend to just make a separate branch for figuring out and getting it to work
turn squashing it to just one commit. It's a pain.
