### ISSUE TITLE
sorry to ask

### ISSUE THREAD

**Issue by mcw0** [Gallopsled/pwntools#1498]
Dear pwntools developers,

I've been trying to search a lot before this message, but cannot find anything about what I want to ask below.

For some reason, I don't want to have the first SSH channel with execve() and all python code that normally ssh() calls will create by default with 'sh -c stty raw -ctlecho -echo; for py in python2.7 python2 python;.... etc'

Is there any simple argument to not start this SSH channel, or another call to close this down as I need all SSH channels?

Many thanks for awesome code, extremely useful! =)

**Comment by Arusekk** [comment]
I think with the current design it would be impossible without modifying pwntools code. But if you have an idea, feel free to contribute your changes.

**Comment by mcw0** [comment]
Ok, thanks for your time, will look into that. All the best, bashis.

**Comment by mcw0** [comment]
Adding "python.close()" did the trick for me.

File: ssh.py, line: 1057
[...]
            except Exception:
                h.failure("Process creation failed")
                self.warn_once('Could not find a Python2 interpreter on %s\n' % self.host \
                               + "Use ssh.run() instead of ssh.process()")
                python.close() # MCW
                return None
[...]
