### ISSUE TITLE
GH Actions build status is not reflected in README

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#1509]
It looks like the Travis CI builds are failing:
https://travis-ci.org/github/Gallopsled/pwntools

**Comment by zachriggle** [comment]
It looks like the specific build that failed is https://travis-ci.org/github/Gallopsled/pwntools/builds/665281456 which is for the GH actions Pull Request.

We might want to update the README.md to show the build status of a specific branch, probably `dev`, so that it doesn't show failing builds for one-offs.

**Comment by Arusekk** [comment]
I dropped Travis CI (turned off notifying Travis in repo settings) and use GH Actions now, but I have not updated the badge yet (needs to be done). Sorry for this, but I am having too little time now.

**Comment by Arusekk** [comment]
Closed in baed2d5bb
