### ISSUE TITLE
Logging modules should attempt to convert log statement to text type, if it is bytes

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#1510]
On Python3, we occasionally pass in bytes objects to the logging mechanism.  We should opportunistically convert these to text strings, since the logs are intended to be text.

```
>>> info('asdf')
[*] asdf
>>> info(b'asdf')
[*] b'asdf' # <--- Should get auto-converted instead of repr()'ing
```

**Comment by Arusekk** [comment]
This could be unified with what happens in `tube.send` and `tube._fillbuffer`.
