### ISSUE TITLE
ELF.functions not updated after ELF.address change

### ISSUE THREAD

**Issue by peace-maker** [Gallopsled/pwntools#1512]
When setting a new base address using `ELF.address` the `ELF.functions` list isn't updated to reflect that change opposed to what [the documentation is saying](http://docs.pwntools.com/en/stable/elf/elf.html#pwnlib.elf.elf.ELF.address).

```python
from pwn import *
e = ELF('./vuln')
print(hex(e.symbols.main)) # 0x8048a0f
print(hex(e.functions.main.address)) # 0x8048a0f
e.address = 0x1234
print(hex(e.symbols.main)) # 0x1c43
print(hex(e.functions.main.address)) # 0x8048a0f

print(e.functions.main.disasm())
[ERROR] Address 0x8048a0f is not contained in ELF('./vuln')
```

**Comment by zachriggle** [comment]
Thanks @peace-maker, would you mind submitting a Pull Request for this?

The way we update everything else is pretty straightforward: https://github.com/Gallopsled/pwntools/blob/dev/pwnlib/elf/elf.py#L587-L606

It should probably be a one-line change
