### ISSUE TITLE
Feature Request: Allow more flexible SSH connection

### ISSUE THREAD

**Issue by saleemrashid** [Gallopsled/pwntools#1519]
At the moment, `pwnlib.tubes.ssh.ssh` will:

1. Parse the `~/.ssh/config` and pull out any key files
2. Load the `~/.ssh/known_hosts`

There are lots of reasons why you might not want to use the environment like this (e.g. ephemeral host keys, not wanting to present your own SSH keys), and it would convenient if `pwnlib` could be configured not to.

A simple solution could be to add a `def from_ssh_client(client: paramiko.SSHClient) -> pwnlib.tubes.ssh.ssh` method?

**Comment by Arusekk** [comment]
Great idea. Would you mind submitting a pull request for this?
