### ISSUE TITLE
ROP: Should have a ROP.jmp_esp / ROP.jmp_rsp gadget

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#1528]
This is an easy gadget for us to detect, and helps out a lot with older challenges that have NX disabled.

**Comment by saullocarvalho** [comment]
Is there some reason to disable JOP engine search on ROPGadget as occur at https://github.com/Gallopsled/pwntools/blob/f1628b80fe03b6af620aa396961f2e555259ec84/pwnlib/rop/rop.py#L1158? Maybe speed?

If pwntools should have a ROP.jmp_esp / ROP.jmp_rsp gadget, maybe JOP engine search should be enabled.

**Comment by zachriggle** [comment]
We disable JOP since we currently only auto-recognize ROP gadgets.  The ROP module is very limited in the gadgets it will accept (we had a GSOC project to do symbolic execution a few years ago, but it never landed).

JOP would just take extra time to scan the binary.  If all we care about is `jmp esp` we can find that much easier than filtering all JOP gadgets.

**Comment by saullocarvalho** [comment]
I see. I have not thought about only looking for its bytes in the executable sections while loading. It is a simpler and faster solution.
