### ISSUE TITLE
ELF: Search should have an `executable=` argument like `writable=`

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#1529]
This makes searching for one-off gadgets a bit easier.  See #1528 for more context.

**Comment by saullocarvalho** [comment]
This feature has already been added.

**Comment by Arusekk** [comment]
Closed in #1576.
For future, automagick happens only when GH detects one of these: https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
