### ISSUE TITLE
Upload release 3.9.3 to PyPi

### ISSUE THREAD

**Issue by heapcrash** [Gallopsled/pwntools#1535]
I have fixed the issue with pyelftools for the legacy Py2 release in 15049b9b30d916d6646857c0ec60cd9973aba288

This should be uploaded to PyPi for users to download if they want to keep to the old version

**Comment by Arusekk** [comment]
Done in f9ac7cc and uploaded to [PyPI](https://pypi.org/project/pwntools/3.9.3/).
