### ISSUE TITLE
remote / listen tubes disagree on default IP stack for localhost

### ISSUE THREAD

**Issue by heapcrash** [Gallopsled/pwntools#1552]
I ran across this while trying to test the UDP stack of `tubes`, the `listen()` binds to IPv4, but `remote()` attempts `::1` for `localhost`.

This is probably not a real issue, but I could see it causing issues for people trying to connect to `localhost` for some challenge that sets up a server.  For TCP we try each interface, but since UDP has no connection handshake, there is no way to detect failure.

Not sure how to / if we can solve this.

```py
>>> l = listen(0, typ='udp')
[x] Trying to bind to 0.0.0.0 on port 0
[x] Trying to bind to 0.0.0.0 on port 0: Trying 0.0.0.0
[+] Trying to bind to 0.0.0.0 on port 0: Done
[x] Waiting for connections on 0.0.0.0:56945
>>> r = remote('localhost', l.lport, typ='udp')
[x] Opening connection to localhost on port 56945
[x] Opening connection to localhost on port 56945: Trying ::1
[+] Opening connection to localhost on port 56945: Done
>>> r.send('asdf')
# nothing
>>> r = remote('127.0.0.1', l.lport, typ='udp')
[x] Opening connection to 127.0.0.1 on port 56945
[x] Opening connection to 127.0.0.1 on port 56945: Trying 127.0.0.1
[+] Opening connection to 127.0.0.1 on port 56945: Done
>>> r.send('asdf')
[+] Waiting for connections on 0.0.0.0:56945: Got connection from 127.0.0.1 on port 59155
```

**Comment by Arusekk** [comment]
Maybe it should just listen on both?

**Comment by zachriggle** [comment]
We might be able to do that, but it would require lots of work since it's not possible to listen on both with the same socket object

**Comment by Arusekk** [comment]
Apparently it might be possible: https://stackoverflow.com/a/1618259/3869724

**Comment by heapcrash** [comment]
It looks like that isn't portable from Linux, e.g. all BSD and macOS by extension don't have that.

We can probably do some tricks with a separate listener thread but it'll be a big refactor.  We should probably just ensure that in doctests we set the correct `fam` argument.
