### ISSUE TITLE
Tag automation should double-check the version fields

### ISSUE THREAD

**Issue by heapcrash** [Gallopsled/pwntools#1567]
We have some cool CI that automatically uploads to PyPi when a new tag is released.

We should add a check such that we are sure `setup.py` and `pwnlib/version` contain the correct field (i.e. whatever the name of the tag is).

**Comment by Arusekk** [comment]
Oh, we do need it. Should be as simple as some `grep "'$GITHUB_REF'" setup.py pwnlib/version.py`
