### ISSUE TITLE
qemu debugging support doesn't load target file

### ISSUE THREAD

**Issue by CptGibbon** [Gallopsled/pwntools#1625]
When launching GDB via `gdb.debug()` when the target is a native binary, it seems to quite happily locate and download the target, printing something like:
```
Downloading '<somefile>' from the remote server: OK
```

However, when the target is a program compiled for a foreign architecture and pwntools uses the qemu gdb stub, gdb-multiarch is unable to do the same, printing the following:
```
warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.
```

It looks like f727b66475dc8eb779e2d0af56250892f7642fa9 removed the `file` command from the gdbscript generated by `gdb.py` to address #1323 
Perhaps gdb-mutiarch doesn't cope with this situation in the same way as gdb? Adding the `file <target>` command to the generated gdbscript allows things to work as normal.

The setup I've encountered this with is Ubuntu 18.04 LTS with the `qemu` package installed and the appropriate symlinks in `/etc/qemu-binfmt/` to allow running ARM, MIPS etc. programs as if they were native.

**Comment by Arusekk** [comment]
Does #1630 do the job for you?

**Comment by CptGibbon** [comment]
That works, although the reason I was hesitant to just add the `file` command back in like this was that #1323 suggests there is a better approach, I'm just not familiar enough with GDB to understand whether that's actually the case.
