### ISSUE TITLE
Multiple files missing six import

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#1638]
It looks like there are a bunch of files that use code from `six` but do not import it.

If you look for references to `six.xxx` which are not on an import line, then cross-reference which modules actually import `six`, you can see there are several of these.  This is related to #1637 

```
$ git grep -l -E -e 'six\.' --and --not -e import -- '*.py' '*.asm' | xargs git grep -L -e 'import six'
pwnlib/adb/bootloader.py
pwnlib/memleak.py
pwnlib/rop/gadgets.py
pwnlib/shellcraft/templates/arm/linux/egghunter.asm
pwnlib/shellcraft/templates/arm/linux/open_file.asm
```

**Comment by heapcrash** [comment]
Closed with 53ecb27948474c3feb3bd81e8848c246d3baa549

This issue only existed on beta+ so no release needed
