### ISSUE TITLE
Is there a way to retrieve the addresses of symbols from a running `process`?

### ISSUE THREAD

**Issue by clubby789** [Gallopsled/pwntools#1672]
Something like `p = process("./binary"); print(hex(process.sym["main"]));`. It would be useful to be able to automate a fuzzer to find what leaked symbols correspond to, as I currently have to leak several addresses then open GDB and check them by hand.

**Comment by clubby789** [comment]
I've just found `process.libc` which seems to be partially what I want; but is there a way to get the in-ELF resolved symbols too?

**Comment by zachriggle** [comment]
Just instantiate an `ELF` object.  `ELF(p.executable)`.

You may also want to play around with Corefiles, e.g. `p.corefile`.

**Comment by clubby789** [comment]
Will the `p.executable` take PIE into account?

**Comment by Arusekk** [comment]
Nope, but you could use dynelf with `p.leak`. Like `DynELF(p.leak)`. This module is actually great and underrated.
