### ISSUE TITLE
ROP gadget loading fails when it matches "add esp, esi"

### ISSUE THREAD

**Issue by tsheinen** [Gallopsled/pwntools#1684]
I can't successfully load ROP gadgets with pwntools 4.2.1 if the binary contains a gadget with "add esp, esi" in it.  This happens at [rop.py on line 1241](https://github.com/Gallopsled/pwntools/blob/dev/pwnlib/rop/rop.py#L1241) because it tries to parse the capture from the regex "^add [er]sp, (\S+)$" as a hexadecimal integer.  I replaced the regex on my local installation with "^add [er]sp, (0?[xX]?[0-9a-fA-F]+)$" to capture only valid hexadecimal integers and it works/passes all tests.  

This should be reproducible with the following binary/python script 

```c
void invalid() {
	asm("add %esi,%esp");
	asm("pop %rbx");
	asm("ret");
}

int main() {

}
```

```python
from pwn import *
elf = ELF("./a.out")

rop = ROP(elf)
```

**Comment by Arusekk** [comment]
Could you submit a PR with this change? The best would be if you added a test to ensure this never regressing.
