### ISSUE TITLE
socket.socket doesnt have unrecv. bug in udp server

### ISSUE THREAD

**Issue by Raz-B** [Gallopsled/pwntools#1690]
https://github.com/Gallopsled/pwntools/blob/5e279e7993f1f57cba2ba128f6bd8a27c19ea25f/pwnlib/tubes/server.py#L120

as mentioned above this is a bug.

line should be
```python
self.unrecv(data)
```
if its necessary at all

**Comment by Arusekk** [comment]
It could either do this, or use `socket.MSG_PEEK` socket flag. @zachriggle what looks better to you? Leaving the data in a kernel buffer, or in the tube buffer? (certainly the current behavior is a buggy `AttributeError`)

**Comment by zachriggle** [comment]
We should put it back into the tube buffer, `self.unrecv(...)` is correct
