### ISSUE TITLE
ELF.vaddr_to_offset returns invalid results

### ISSUE THREAD

**Issue by peace-maker** [Gallopsled/pwntools#1697]
## Update Pwntools First

Running the latest dev branch version.

## Debug Output

```
>>> from pwn import *
>>> context.log_level = 'debug'
>>> libc = ELF("./libc-2.31.so", checksec=False)
[DEBUG] PLT 0x22040 realloc
[DEBUG] PLT 0x22090 __tls_get_addr
[DEBUG] PLT 0x220d0 memalign
[DEBUG] PLT 0x220e0 _dl_exception_create
[DEBUG] PLT 0x22120 __tunable_get_val
[DEBUG] PLT 0x221e0 _dl_find_dso_for_object
[DEBUG] PLT 0x22220 calloc
[DEBUG] PLT 0x22300 __libpthread_freeres
[DEBUG] PLT 0x22308 malloc
[DEBUG] PLT 0x22310 __libdl_freeres
[DEBUG] PLT 0x22318 free
>>> libc.address
0
>>> hex(libc.symbols.__malloc_hook)
'0x1b99d0'
>>> hex(libc.vaddr_to_offset(libc.symbols.__malloc_hook))
'0x1b89d0'
>>> hex(libc.symbols.__libc_start_main)
'0x23b90'
>>> hex(libc.vaddr_to_offset(libc.symbols.__libc_start_main))
'0x23b90'


>>> libc.address = 0x7f100b0ac000
>>> hex(libc.symbols.__malloc_hook)
'0x7f100b2659d0'
>>> hex(libc.vaddr_to_offset(libc.symbols.__malloc_hook))
'0x1b89d0'
>>> hex(libc.symbols.__libc_start_main)
'0x7f100b0cfb90'
>>> hex(libc.vaddr_to_offset(libc.symbols.__libc_start_main))
'0x23b90'
```

## Description
The logic to retrieve the file offset from a virtual address seems to hit a corner case, when trying to get the file offset of `__malloc_hook` in libc. The raw offset of `0x1b99d0` is the correct value for the given libc, but `0x1b89d0` is returned instead.

I'd expect the value to be the same, if `ELF.address` is set to `0`. Instead it seems `ELF.vaddr_to_offset` subtracts 0x1000 from the value in this case. Other symbols are fine, so it's maybe related to the `.data` segment?

**Comment by zachriggle** [comment]
Can you zip up the offending ELF file and attach it on Github?

**Comment by peace-maker** [comment]
Sure.
[libc-2.31.zip](https://github.com/Gallopsled/pwntools/files/5338796/libc-2.31.zip)

**Comment by peace-maker** [comment]
Ok, after some digging it turns out, that starting with the `.tdata` segment and onwards the file offset and the segment mapping is off by 0x1000 in libc.

`ELF.vaddr_to_offset` is documented as `Translates the specified virtual address to a file offset`, so it seems to do the job correctly. I'm more interested in the offset of the file mapped in memory though.
I'll switch to manually doing `address - libc.address` instead of using `vaddr_to_offset` I guess.

**Comment by zachriggle** [comment]
So the take-away here is that the code works as documented, but does not follow the [principal of "least surprise"](https://softwareengineering.stackexchange.com/questions/187457/what-is-the-principle-of-least-astonishment).

I'd be open to adding a `vaddr_to_memoffset` or similar function that does what you expect it to, but doing the math manually is a good interim step.  We can then add an alias `vaddr_to_offset` to be `vaddr_to_fileoffset` and mark `vaddr_to_offset` as deprecated in the documentation (but keep its existing functionality).
