### ISSUE TITLE
FmtStr - Write only N byte instead of 8

### ISSUE THREAD

**Issue by nicomazz** [Gallopsled/pwntools#1698]
When the arch is set to `amd64`, It would be nice to be able to write a single byte/short/int instead of all the 8 bytes.
A use case for this is when we want to keep the other bytes intact and change only some, or to keep the format string short.

e.g.:  I was trying to do this, but I needed to modify only 4 bytes instead of 8:
```python
fmtstr_payload(7, {0x7ffcc0574698: 4})
```
And resulted to be: 
```python
b'%4c%9$llnaaaabaa\x98FW\xc0\xfc\x7f\x00\x00'
```
With a size of 24, while my buffer had a limit of 20.

A home-made format string, in this case, would have been:
```python
b"1111%8$n\x98FW\xc0\xfc\x7f\x00\x00"
```
with a size of 16 instead of 24. (here, the write modifier is `%n` instead of `%lln` of the previous example).

Maybe this can be implemented with an additional parameter to `fmtstr_payload`, called `bytes_to_change`?

**Comment by peace-maker** [comment]
I'd like to be able to specify the number of bytes to write per write element. So if there are multiple values to write, only truncate one of them and write the full 8 bytes for others.

Maybe `fmtstr_payload(7, {0x123456: {'val': 4, 'width': 2}, 0x789abc: 42})`

The same pattern could be used to change more details like the format specifier to use `int`, `short`, `byte` per write value.

**Comment by nicomazz** [comment]
Yeah, that makes sense. Unfortunately, I don't have time to try to implement this :/

**Comment by Arusekk** [comment]
You can just do a:
```py
>>> fmtstr_payload(7, {0x7ffcc0574698: p32(4)})
b'%4c%8$na\x98FW\xc0\xfc\x7f\x00\x00'
```
or
```py
>>> fmtstr_payload(7, {0x7ffcc0574698: p16(4)})
b'%4c%8$hn\x98FW\xc0\xfc\x7f\x00\x00'
```
instead of the default
```py
>>> fmtstr_payload(7, {0x7ffcc0574698: pack(4)}) # this is what {0x7ffcc0574698: 4} aliases to
b'%4c%9$llnaaaabaa\x98FW\xc0\xfc\x7f\x00\x00'
```
which takes packing size from `context.bytes`, and is the shortest possible for writing full `b'\4\0\0\0\0\0\0\0'` at that address.
