### ISSUE TITLE
Breaks sys.argv with all caps arg

### ISSUE THREAD

**Issue by ghost** [Gallopsled/pwntools#1701]
When I try to pass in any arg that consists of all cap letters, pwntools seems to remove that arg:

```python
#!/usr/bin/env python3

import sys
from pwn import *

print(sys.argv)
```

Examples

```
pwntools@2009c0e007eb:~$ python test.py AAAAAAAAa
['test.py', 'AAAAAAAAa']
pwntools@2009c0e007eb:~$ python test.py AAAAAAAAAA
['test.py']
pwntools@2009c0e007eb:~$ python test.py A         
['test.py']
pwntools@2009c0e007eb:~$ python test.py AAA
['test.py']
pwntools@2009c0e007eb:~$ python test.py AB 
['test.py']
pwntools@2009c0e007eb:~$ python test.py ABCD
['test.py']
pwntools@2009c0e007eb:~$ python test.py ABCDA
['test.py']
pwntools@2009c0e007eb:~$ python test.py ABCDAW
['test.py']
pwntools@2009c0e007eb:~$ python test.py ABCDAWa
['test.py', 'ABCDAWa']
```

Expected behavior would be showing the submitted args.

**Comment by peace-maker** [comment]
That's a feature I guess. You can access them directly using `args.ARGNAME` without the need to parse sys.argv yourself.

**Comment by ghost** [comment]
Ah, that makes sense, I guess. I see the docs now. It's a pain when trying to submit a string to play with if the input string is all caps sometimes but not others. Maybe that loss is worth the availability of using keywords like this. I'll close this.

**Comment by Dramelac** [comment]
Hello,

This "feature" is still removing caps arguments from the `sys.argv` array. 
I understand the use of `args.ARGNAME` but this behavior means we cant use **argparse** with pwntools if we are expecting caps arguments...

**Comment by Arusekk** [comment]
This is intentional, and can be disabled if you import stuff from `pwnlib` instead of `from pwn import *`: https://docs.pwntools.com/en/latest/args.html
