### ISSUE TITLE
ssh python script support python3

### ISSUE THREAD

**Issue by plusls** [Gallopsled/pwntools#1723]
I found that ssh tube script can run in python3, but it force use python or python2

https://github.com/Gallopsled/pwntools/blob/42b060e48a0f2d29d1874cc41b1ba14f26be8575/pwnlib/tubes/ssh.py#L937

https://github.com/Gallopsled/pwntools/blob/42b060e48a0f2d29d1874cc41b1ba14f26be8575/pwnlib/tubes/ssh.py#L1079

I hope can add python3 into L1079

**Comment by Arusekk** [comment]
I ported that script to python 3 already, but thought that wherever `python2` is absent, `python` points to `python3`. This might be a wrong assumption. Feel free to open a pull request.

**Comment by Arusekk** [comment]
Closed by #1746
