### ISSUE TITLE
CR not working in terminal output

### ISSUE THREAD

**Issue by qumusabel** [Gallopsled/pwntools#1728]
`\r` does not work if you import anything from pwntools

example:

```python
for i in range(1, 100):
    print(i, end='\r')
print('as expected')
```
```
as expected
```

```python
from pwn import remote
for i in range(1, 10):
    print(i, end='\r')
print('not as expected')
```
```
123456789not as expected
```
Same using `sys.stdout.write`. I've tried disabling pwntools' output, but it didn't help. This is really annoying. I want to do a bruteforce attack and see what i'm sending, but without `\r` it quickly turns into a mess!

**Comment by qumusabel** [comment]
`pwn.log.progress` works well for this stuff

**Comment by Arusekk** [comment]
You can also try bruteforce / mbruteforce functions, or if it does not suit your needs, use `log.progress()` which is used internally by them for pretty printing.
