### ISSUE TITLE
Docker images no longer provide `python` command

### ISSUE THREAD

**Issue by maybe-sybr** [Gallopsled/pwntools#1774]
Hi all. We've noticed a bunch of failure in our CI because of the recent change to the pwntools base docker image to install python3 instead of python2. In xenial/bionic, the `python3` package doesn't actually provide a `python` command nor does it seem to be able to be set up using `update-alternatives`.

A trivial fix would be to just `ln -s "$(comand- v python3)" /usr/bin/python` after the installation happens. It'd be nicer if we could use the `python-is-python3` (from `what-is-python` [0]) but that's only in groovy or later which would force you to push to focal which might be a larger undertaking.

[0] https://code.launchpad.net/ubuntu/+source/what-is-python

**Comment by zachriggle** [comment]
Would it be sufficient to install BOTH Python2 and Python3? 

I think changing /usr/bin/python is out of scope, and it might be better for your CI pipeline to explicitly invoke `python2` or `python3`, not `python` (since the latter is subject to change and which version of the OS is installed).

**Comment by maybe-sybr** [comment]
Losing python2 is the kick I needed to finally port some of our older stuff. I'm fine with it not being present any more at all, it was just a bit disruptive. We're also more explicit now about which python we want to use (`python3` for anything based on the `pwntools` images) to avoid issues like you suggested. In theory though, our scripts are now all (previously mostly) portable so we don't really care which python they run in.

From my perspective, I don't need any changes since we've elected to port and be explicit about the python version; but I could think of a handful of things that might make life easier for others.

1. Including the python version(s) available in the image as part of the tag
    - e.g. `pwntools:py3-dev`, `pwntools:py2-beta`
2. Provide Python 2+3 images as well which could become the new default images
    - ie. `pwntools:py6` is also tagged as `pwntools:latest`
3. Maybe look at pushing semver tags for your images
    - semver could match your software versioning but then you can't describe environmental stuff like this python 2->3 change
    - or be independent and rely on you pinning versions for your non-rolling image releases but that's a pain in the butt
    - for some of my own projects I do semver on the container image itself with special rolling `development` tags for local dev/CI

All of that seems like it might be a bunch of work and I wouldn't expect you to feel like it's worthwhile though.

**Comment by heapcrash** [comment]
It's easy enough to add Python2 to the Docker images and install PY2 Pwntools, and it solves most of your problems.  I honestly didn't expect that anybody other than me actually *used* the Docker images, so I didn't think of this when making recent changes.

Simple enough to fix for all parties involved is just to add Py2 back into the Dockerfile.

**Comment by maybe-sybr** [comment]
Great, glad I could be a helpful test dummy! Thanks for the quick replies also :)

**Comment by Arusekk** [comment]
I believe this can be closed, can it not?

**Comment by zachriggle** [comment]
@Arusekk not yet, give me some time over the weekend to resolve this

**Comment by heapcrash** [comment]
@maybe-sybr Can you provide commentary on #1786?  It changes how and where Pwntools is installed, adds a `pwntools` user, and uses a checkout from `git`, and does a non-root install (i.e. only affects the `pwntools` user).
