### ISSUE TITLE
There may be a bug in dynelf.py-function"_dynamic_load_dynelf"

### ISSUE THREAD

**Issue by ClarkCh** [Gallopsled/pwntools#1782]
1.I updated the pwntools to the version 4.4.0b1
2.I want to dump libc from remote
d.lookup("system", libc)                 ->       it calls _dynamic_load_dynelf normally
d.dump(libs=True)                         ->      it raise an Exception:'bytes' object has no attribute 'encode'

3.After my debugging found that in dynelf.py line 645, 
-> if libname.encode('utf-8') in name:
libname: bytes or str
when type(libname) == bytes,it will raise exception
i fixed the bug by 
->if isinstance(libname, str):
->    libname = libname.encode("utf-8")
->if libname in name:

**Comment by Arusekk** [comment]
I see, the fix would be to change `libname.encode(...)` to `context._encode(libname)`

**Comment by heapcrash** [comment]
Is there any reason not to use `six.ensure_bytes()`?

**Comment by ClarkCh** [comment]
> I see, the fix would be to change `libname.encode(...)` to `context._encode(libname)`

hhh，I am not familiar with pwntools

**Comment by ClarkCh** [comment]
> 
> 
> Is there any reason not to use `six.ensure_bytes()`?

what is six?

**Comment by Arusekk** [comment]
[`six`](https://six.readthedocs.io/) is a compat library, but I much prefer using UTF-8 over ISO-8859-1 (the one used by six.ensure_bytes), because no one uses it to date, and with the advent of unicode identifiers in programming languages (ever wanted to name a variable π? most likely you can do that) non-ascii stuff will only become more popular. And if you want to explicitly handle only 7-bit chars, use `'ascii'` encoding. And the best is not to use encodings at all and stick to the "bytes is bytes, text is text" principle.

**Comment by heapcrash** [comment]
> And the best is not to use encodings at all and stick to the "bytes is bytes, text is text" principle.

I definitely agree with this, but this is a recurring pain point for our
users.
Do we expose a fiddly bit to set the default encoding to ISO-8859-1?

> ever wanted to name a variable π

You can still name variables whatever you want, even with ISO encoding on a `str` object.  It just can't *contain* that symbol.

It's always been my opinion that six.ensure_bytes() is the most portable / principle of least surprise, but @Arusekk spends more time
maintaining things and did the Python3 rewrite, so I'll defer to him.

However, for this SPECIFIC case, the user *IS* passing in a `bytes` object and it's throwing errors (if I read it correctly).

**Comment by Arusekk** [comment]
it is now called `packing._encode`

**Comment by Arusekk** [comment]
Closed in #1719
