### ISSUE TITLE
Differentiation between positional and keyword arguments in the documentation

### ISSUE THREAD

**Issue by Rairosu** [Gallopsled/pwntools#1799]
- What the feature does
It will allow to distinguish between positional and keyword arguments in the documentation
- Why the feature should exit
It will hopefully make some Issues easier to debug and apart from that will help many starters to learn to use the many functions offered by pwntools
- What tests should be included
None. It is a change to the documentation and not to the code.

---

I'd like to be able to clearly distinguish between the positional and the keyword arguments in the documentation so the functions and arguments are easier to understand for beginners and it is not needed to read the source code to be able to tell which arguments are positional and which are just optional keyword arguments.
![image](https://user-images.githubusercontent.com/48859466/108121129-9747a580-70a2-11eb-928d-0526ccd209ab.png)

**Comment by Arusekk** [comment]
We can use [`functools.wraps`](https://docs.python.org/dev/library/functools.html#functools.wraps) more, since it allows [`inspect`](https://docs.python.org/dev/library/inspect.html) (used by sphinx, our docs auto-generator) to infer more accurate signatures, therefore enhancing the documentation.
Its logic should be purely aesthetic, so it can be introduced without breaking stuff.

**Comment by heapcrash** [comment]
Doing wraps() with LocalContext will add ALL of the context fields. I’m not
sure there is an easy way to do this except maybe making a custom
LocalArch() which only exposes a few of the flags

**Comment by heapcrash** [comment]
It looks like we already use functors.wraps:

https://github.com/Gallopsled/pwntools/blob/15f85de4d8bdbf95124b89add77daf32e662973e/pwnlib/context/__init__.py#L533-L538

**Comment by heapcrash** [comment]
We might be able to use `autodoc-process-signature` to do some stuff for this as well.

**Comment by peace-maker** [comment]
This looks like it was fixed or fixed itself in newer sphinx version?

![grafik](https://github.com/Gallopsled/pwntools/assets/1635147/f9dcb12e-710a-408e-964f-2fb9ef9a94e7)
