### ISSUE TITLE
Discord Server Invite has Expired

### ISSUE THREAD

**Issue by qwe-q** [Gallopsled/pwntools#1800]
Not a pwntools bug, however, the Discord link listed in the README has expired when one attempts to join the server through it. Wanted to talk to someone about some strange behavior I was noticing and discovered this.
Cheers!

**Comment by heapcrash** [comment]
Do you have any tips on how to create a permanent discord invite URL?  I am new to Discord and generally use Slack :(

**Comment by Arusekk** [comment]
Closed in 4e6ccb0da17fb91e43a4f9e95edf4fd83806ba23.

**Comment by heapcrash** [comment]
Figured it out, the new README.md should have a permanent invite link
