### ISSUE TITLE
Suggest adding ~/.local/bin to $PATH where appropriate

### ISSUE THREAD

**Issue by heapcrash** [Gallopsled/pwntools#1801]
In recent years `pip` has learned to be smart enough to invoke the `--user` flag on its own, rather than requiring `sudo pip install ...` or manually specifying `pip install --user ...`.

This means that our command-line helpers are transparently added to `~/.local/bin`, which may not be in the user's `$PATH`.

This happens automagically when you do `pip install pwntools`.  There is no warning message about where to find the command-line tools, the installation just happens transparently and silently.

This leaves `~/.local/bin` holding a bunch of our entry points, which may not already be in the user's `$PATH`:

```
$ ls .local/bin
asm  checksec  common  constgrep  cyclic  debug  disablenx  disasm  elfdiff  elfpatch  errno  hex  main  phd  pwn  pwnstrip  scramble  shellcraft  template  unhex  update  wheel
```

We should detect the scenario when `pwn` is in not `$PATH` and check `~/.local/bin` to see if the scripts are installed there, and offer a suggestion to add it to `$PATH`.

There are some caveats here, we might be running a different Python than the shebang in the script.  For example:

```
$ head -1 .local/bin/pwn
#!/Users/heapcrash/.pyenv/versions/3.8.3/bin/python3.8
```

We also have to consider that there are multiple installations, and when to suggest additions to `$PATH`.

```
$ asm nop
90

$ head -1 $(which asm)
#!/usr/local/opt/python@3.9/bin/python3.9

$ head -1 ~/.local/bin/asm
#!/Users/heapcrash/.pyenv/versions/3.8.3/bin/python3.8
```

I recommend a `log.warn` suggestion to add `~/.local/bin` to `$PATH` if-and-only-iff there is no `pwn` binary in the current `$PATH` and `~/.local/bin/pwn` exists **AND** the interpreter of `~/.local.bin/pwn` is of the same general Python family (e.g. v2 vs v3) as the invocation command.

**Comment by peace-maker** [comment]
`pip` warns in yellow text about the scripts installed in `~/.local/bin` now if that directory is not in the PATH. So we don't have to warn again unless the suggestion here was to print the warning when importing `pwn` instead of on install in `setup.py`.

```
  WARNING: The scripts asm, checksec, common, constgrep, cyclic, debug, disablenx, disasm, elfdiff, elfpatch, errno, hex, libcdb, main, phd, pwn, pwnstrip, scramble, shellcraft, template, unhex, update and version are installed in '/home/peace/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

**Comment by Arusekk** [comment]
I agree pip is a place better suited for such warnings.
