### ISSUE TITLE
'ValueError: non-zero flags not allowed in calls to recv() on <class 'ssl.SSLSocket'>'

### ISSUE THREAD

**Issue by mcw0** [Gallopsled/pwntools#1824]
While using 'can_recv()' and 'ssl=True' with 'remote()'

Possible fix for [sock.py](https://github.com/Gallopsled/pwntools/blob/dev/pwnlib/tubes/sock.py#L39) (working)

[...]
                break
            except ValueError:  # SSL 'can_recv()'
                return ''
            except socket.timeout:
[...]

**Comment by Arusekk** [comment]
This means you use some flags? What do you call to get the error? Some reproducer?

**Comment by mcw0** [comment]
I would like to rename 'fix' to 'workaround'.

Flag set in 'sock.py' [here](https://github.com/Gallopsled/pwntools/blob/dev/pwnlib/tubes/sock.py#L112)

[reproducer]
>>> google = remote('google.com',port=443,ssl=True)
[x] Opening connection to google.com on port 443
[x] Opening connection to google.com on port 443: Trying 216.58.209.14
[+] Opening connection to google.com on port 443: Done
>>> google.can_recv()
False
>>> google.can_recv()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/pwnlib/tubes/tube.py", line 1140, in can_recv
    return bool(self.buffer or self.can_recv_raw(timeout))
  File "/usr/local/lib/python3.9/dist-packages/pwnlib/tubes/sock.py", line 110, in can_recv_raw
    self.recv_raw(1, socket.MSG_PEEK)
  File "/usr/local/lib/python3.9/dist-packages/pwnlib/tubes/sock.py", line 39, in recv_raw
    data = self.sock.recv(numb, *a)
  File "/usr/lib/python3.9/ssl.py", line 1223, in recv
    raise ValueError(
ValueError: non-zero flags not allowed in calls to recv() on <class 'ssl.SSLSocket'>
>>>


/usr/lib/python3.9/ssl.py"
[...]
    def recv(self, buflen=1024, flags=0):
        self._checkClosed()
        if self._sslobj is not None:
            if flags != 0:
                raise ValueError(
                    "non-zero flags not allowed in calls to recv() on %s" %
                    self.__class__)
            return self.read(buflen)
        else:
            return super().recv(buflen, flags)
[...]

**Comment by Arusekk** [comment]
So the try-except should be in sock.py:112 instead, but sure this deserves a fix.

-- 
Wysłane z mojego urządzenia Sailfish

**Comment by mcw0** [comment]
Agree, I've seen many different approaches to the same issue on Google while trying to gain more insight, so it seems not to be anything new really... If I find anything that maybe would be acceptable, I'll share here. But so far what I've noted, the issue is upstream, as the SSL recv() do not accept any flags.

**Comment by mcw0** [comment]
Best workaround I can give you for [sock.py](https://github.com/Gallopsled/pwntools/blob/dev/pwnlib/tubes/sock.py#L115) L115

[...]
        # SSLSocket and Paramiko recv() do not support any flags
        except (ValueError, TypeError):
            # select() said there is data, so pass
            pass
[...]

**Comment by mcw0** [comment]
Thx, opened a pull request.
