### ISSUE TITLE
bug in fit() - python2/python3

### ISSUE THREAD

**Issue by macrl2000** [Gallopsled/pwntools#1829]
Hi,

in latest (today) upgraded pwntools 4.3.1 i think i found following bug

you do:

```
from pwn import *
print(cyclic(32))
payload = fit({'caaa':p32(0x1337BAB3)}, length=32)
print(payload)
```
using python2, you get on output with print (arranged for better visibility)
```
aaaabaaa caaa          daaaeaaafaaagaaahaaa
aaaabaaa \xb3\xba7\x13  aaaeaaafaaagaaahaaa
```
the letter "d" is gone in the replaced output - so there were 5 chars replaced by 4 chars

you do the same with python3 you get

```
b'aaaabaaa caaa          daaaeaaafaaagaaahaaa'
b'aaaabaaa \xb3\xba7\x13 daaaeaaafaaagaaahaaa'
```

Kind regards
 mac

**Comment by heapcrash** [comment]
Instead of `print(payload)` can you do `print(hexdump(payload))`?  Thanks!

**Comment by macrl2000** [comment]
ok - with the hexdump it looks fine for python2/python3 - both have the same ouput
```
00000000  61 61 61 61  62 61 61 61  63 61 61 61  64 61 61 61  │aaaa│baaa│caaa│daaa│
00000010  65 61 61 61  66 61 61 61  67 61 61 61  68 61 61 61  │eaaa│faaa│gaaa│haaa│
00000020
00000000  61 61 61 61  62 61 61 61  b3 ba 37 13  64 61 61 61  │aaaa│baaa│··7·│daaa│
00000010  65 61 61 61  66 61 61 61  67 61 61 61  68 61 61 61  │eaaa│faaa│gaaa│haaa│
00000020
```
i was pretty sure i had also shifted buffers, in fit but - i wll investigate further 
thank you !
