### ISSUE TITLE
should functions, docutils,  beautifulsoup4 be listed as dependencies?

### ISSUE THREAD

**Issue by suliuzh** [Gallopsled/pwntools#1848]
Hi
I am wondering if some dependencies should be listed in requirements.txt or as extra dependencies in sub-folders?
they are 

- functions
- docutils
- beautifulsoup4

_docutils_ is used in pwnlib/internal/dochelper.py.  _beautifulsoup4(bs4)_ is used in pwnlib/data/useragents/download-useragents.py. _functions_ is in pwnlib/data/syscalls/generate.py. And I noticed that  _functions_ is mentioned in comments as _github.com/zachriggle/functions_. So maybe it is necessary to list these dependencies explicitly?

**Comment by heapcrash** [comment]
No, as these are not needed to actually run any portion of pwntools.

Maybe there should be an additional requirements.txt for maintenance of pwntools itself (like docs/requirements.txt) but none of these dependencies are needed to actually run any part of pwntools.
