### ISSUE TITLE
pwn template function name "remote" collision

### ISSUE THREAD

**Issue by martinclauss** [Gallopsled/pwntools#1860]
Hi :)

When using `pwn template` with `--host` and `--port` the template generates a `remote` function:

```python
def remote(argv=[], *a, **kw):
    '''Connect to the process on the remote host'''
    io = connect(host, port)
    if args.GDB:
        gdb.attach(io, gdbscript=gdbscript)
    return io
```
Unfortunately, now it is not possible anymore to use `pwnlib.tubes.remote.remote` because of a name collision.

Maybe the template function should be renamed...

Thanks!

**Comment by Arusekk** [comment]
You can still use it either as: pwnlib.tubes.remote.remote(), or as one of its aliases: connect() or tcp()

Email z Sobota, 10 kwietnia 2021 od martinclauss:
> Hi :)
> 
> When using `pwn template` with `--host` and `--port` the template generates a `remote` function:
> 
> ```python
> def remote(argv=[], *a, **kw):
>     '''Connect to the process on the remote host'''
>     io = connect(host, port)
>     if args.GDB:
>         gdb.attach(io, gdbscript=gdbscript)
>     return io
> ```
> Unfortunately, now it is not possible anymore to use `pwnlib.tubes.remote.remote` because of a name collision.
> 
> Maybe the template function should be renamed...
> 
> Thanks!
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Gallopsled/pwntools/issues/186

-- 
Wysłane z mojego urządzenia Sailfish

**Comment by heapcrash** [comment]
This is a known issue, and definitely a design flaw.  I'm not sure what to name remote other than `remote` but I'm open to suggestions -- we definitely shouldn't overwrite the globals we import from pwnlib.

**Comment by martinclauss** [comment]
I think since `start()` is the proposed starting point (`io = start()`), `remote` and `local` could be renamed to `_remote` and `_local` since they are not called directly from `main()`, at least in the template. Otherwise, `io_remote` and `io_local` would also be reasonable. Another option would be a `tpl_` prefix to indicate that the functions belong to the template (e.g. `tpl_remote`) :) What do you think?

**Comment by heapcrash** [comment]
How about start_local and start_remote?  Would you mind submitting a Pull
Request?

**Comment by martinclauss** [comment]
Yes, no problem :) What do you think about resolving issue #1803 with the same PR?
