### ISSUE TITLE
[Bug] ROP calls insert incorrect padding on i386, hard-coded for amd64

### ISSUE THREAD

**Issue by heapcrash** [Gallopsled/pwntools#1862]
In this chunk of code here:

https://github.com/Gallopsled/pwntools/blob/dev/pwnlib/rop/rop.py#L654-L668

We hard-code the size of a stack slot to be 8 bytes.  It should be pulled from `context.arch`, or even more preferably from the first `ELF` via `ROP.elfs[0].bytes`.

This bug causes incorrect padding during ROP generation on i386.  This code path to insert padding generally isn't used on i386 since the arguments are all on the stack (and the ~only time we insert padding is via ROP.setRegisters) so it's gone unnoticed for a while and doesn't have a lot of impact -- but it's wrong all the same.

**Comment by heapcrash** [comment]
It looks like there is already a function for this, `_slot_len` which should be [1] adopted in ROP generation code linked above and [2] probably be made into a ROP method, since `ROP.elfs[0].bytes` and `context.bytes` may not agree, and the former is a stronger candidate.

**Comment by Arusekk** [comment]
It might be used for x86 syscalls, since they still use register arguments (only eax would matter in our case, since we prefer doing sigreturn to directly calling actual syscalls).

**Comment by Arusekk** [comment]
Not a dup of #1683, that one is broader.
