### ISSUE TITLE
Docker Image Builds are Failing

### ISSUE THREAD

**Issue by heapcrash** [Gallopsled/pwntools#1868]
I'm getting email notifications that our Docker builds are failing.  Here's one example:

https://hub.docker.com/repository/registry-1.docker.io/pwntools/pwntools/builds/2d0652fc-a37a-4cc9-8851-2a1dd2e42e82

Failures look like this:

<details><summary>Docker Hub Failures</summary>

```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4_7.58.0-2ubuntu3.12_amd64.deb 404 Not Found [IP: 91.189.88.142 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/c/curl/curl_7.58.0-2ubuntu3.12_amd64.deb 404 Not Found [IP: 91.189.88.142 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/pygments/python-pygments_2.2.0+dfsg-1ubuntu0.1_all.deb 404 Not Found [IP: 91.189.88.142 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/p/pygments/python3-pygments_2.2.0+dfsg-1ubuntu0.1_all.deb 404 Not Found [IP: 91.189.88.142 80]
```
</details>

I think that the issue is that perhaps the base image is not being updated (or used) so the `apt-get update` isn't running when it should.

**Comment by Arusekk** [comment]
Confirmed, the failing command is `sudo apt-get install -y curl ipython ipython3 lsb-release ssh unzip wget`

**Comment by heapcrash** [comment]
It looks like the failures were transient, there are relatively up-to-date
builds.  I expect there was a server availability issue, or something like
using an old version of the base image.

https://hub.docker.com/repository/docker/pwntools/pwntools/builds

All of the builds are now green except CI, which has never been a working
automated build (gets uploaded manually).

**Comment by heapcrash** [comment]
They appear to be working now, not sure what the issue was.
