### ISSUE TITLE
ValueError in gdb.attach when using tmux terminal

### ISSUE THREAD

**Issue by Gy4n** [Gallopsled/pwntools#1874]
I am using ubuntu 20. I Install the python2 version of pwntools and specify `context.terminal = ["tmux", "splitw", "-h"]`.
when use `gdb.attach(p)`,it throws `ValueError`
The Traceback is below:
```Traceback (most recent call last):
  File "../python/UnsortedBin_otknotebook.py", line 11, in <module>
    gdb.attach(p)
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/context/__init__.py", line 1543, in setter
    return function(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/gdb.py", line 1051, in attach
    gdb_pid = misc.run_in_new_terminal(cmd, preexec_fn = preexec_fn)
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/util/misc.py", line 297, in run_in_new_terminal
    pid = int(out)
```
I downgrade pwntools to 4.4.0,it works!

**Comment by Arusekk** [comment]
Please paste the output of `pwn version`

**Comment by Gy4n** [comment]
> Please paste the output of `pwn version`

`[*] Pwntools v4.5.0`

**Comment by Gy4n** [comment]
> Please paste the output of `pwn version`

`[*] Pwntools v4.5.0`

**Comment by Arusekk** [comment]
Okay, since #1261 you need
```py
context.terminal = ['tmux', 'splitw', '-h', '-F' '#{pane_pid}', '-P']
```
see `pwnlib/util/misc.py` for details.
This is because `tmux splitw -h /path/to/some/script` exists before the script finishes executing, so we can query the pid of the subprocess and wait for it. Too bad `tmux splitw` does not have any `--wait-for-completion` flag.
https://github.com/tmux/tmux/blob/8da45730880467ea5defe010c58ac1ec7ca74c4e/cmd-split-window.c#L189-L191

Treat this as a temporary workaround, since this is an error of us to special-case tmux without extra checks. It may change back to its original behavior. Anyway, you can always just not set context.terminal, but the default tmux new window will appear below, not on the right. You can probably work this around using tmux hooks to place windows around, or move it every time it spawns.

**Comment by Gy4n** [comment]
ok,it finally works. thank u

**Comment by pwndumb** [comment]
> ok,it finally works. thank u
Can you tell me how you  fix that ? I already install `beta` , `stable` and `dev` version. This error remains in `Kali` , `Ubuntu` and `Debian`. 

## script
```python
...
    
context.log_level = 'DEBUG'
context.terminal = ['tmux', 'splitw', '-h', '-F' '#{pane_pid}', '-P']
context.arch = 'amd64'
context.os = 'linux'

``` 

## error open tmux 
```bash
[DEBUG] Launching a new terminal: ['/usr/bin/tmux', 'splitw', '-h', '-F#{pane_pid}', '-P', '-F#{pane_pid}', '-P', '/tmp/tmpz46joucq']
Traceback (most recent call last):
  File "/mnt/hgfs/pwn/Linux Binary/pwn-htb-track/1-jeeves/./asd.py", line 37, in <module>
    main()
  File "/mnt/hgfs/pwn/Linux Binary/pwn-htb-track/1-jeeves/./asd.py", line 26, in main
    gdb.attach(p.pid,'''
  File "/usr/local/lib/python3.9/dist-packages/pwntools-4.6.0b1-py3.9.egg/pwnlib/context/__init__.py", line 1524, in setter
    return function(*a, **kw)
  File "/usr/local/lib/python3.9/dist-packages/pwntools-4.6.0b1-py3.9.egg/pwnlib/gdb.py", line 1046, in attach
    gdb_pid = misc.run_in_new_terminal(cmd, preexec_fn = preexec_fn)
  File "/usr/local/lib/python3.9/dist-packages/pwntools-4.6.0b1-py3.9.egg/pwnlib/util/misc.py", line 303, in run_in_new_terminal
    pid = int(out)
ValueError: invalid literal for int() with base 10: b''
[*] Stopped process '/mnt/hgfs/pwn/Linux Binary/pwn-htb-track/1-jeeves/jeeves' (pid 2861)

``` 

## pwntools version 
```bash
 pwn version              
[*] Pwntools v4.6.0beta1
```

**Comment by heapcrash** [comment]
Looks like you specified '-F#{pane_pid}', '-P' twice.

**Comment by jelly8173** [comment]
Just in case someone still have that error try running your script inside tmux session

**Comment by scraggelz** [comment]
@jelly8173 Is this still the intended workaround? I'm using 4.15.0 and still getting this error inside TMUX even with:
`context.terminal = ['tmux', 'splitw', '-h', '-F' '#{pane_pid}', '-P']`

EDIT: issue was that I was attempting to run pwntools script as sudo. Fix was to make sure that entire tmux session was root then it works fine.
