### ISSUE TITLE
Documentation: Expose `pwnlib.elf.corefile` in top-level tree

### ISSUE THREAD

**Issue by heapcrash** [Gallopsled/pwntools#1880]
It looks like the `pwnlib.elf.Corefile` documentation does not show in the top-level table of contents on docs.pwntools.com.  `pwnlib.elf` does, but `Corefile` should also be exposed.

I expect there are many modules that aren't exposed this way, we should probably have a way to automatically check which modules are / aren't exposed in `index.rst`.

**Comment by peace-maker** [comment]
This was fixed in #1925
