### ISSUE TITLE
ROP gadget verifier does not account for single digit registers

### ISSUE THREAD

**Issue by ghost** [Gallopsled/pwntools#1883]
The regex used to verify pop instructions in rop.py uses this regex `pop   = re.compile(r'^pop (.{3})')` which assumes the register name is any three characters. This misses registers such as `r8`, `r9`, and possibly other 16-bit or 8-bit registers.

A simple fix would be to use the regex `pop   = re.compile(r'^pop (.{2,3})')` to allow for two character or three character register destinations.

**Comment by heapcrash** [comment]
Closed via #1884
