### ISSUE TITLE
Tab-completion for the `pwn` executable

### ISSUE THREAD

**Issue by vulns-are-features-too** [Gallopsled/pwntools#1889]
I'd like to have tab-completion scripts (bash, zsh, fish) for the `pwn` executable. It's just nice to have for everyone.

**Comment by heapcrash** [comment]
I agree this would be nice.

IMHO the best way to achieve this is to rewrite the pwn commands with Click.

It supports autocomplete for bash and zsh, and in general has a neat syntax for what we already do.

An alternative would be to use zargparse or similar, but I've tried it before with Pwntools and it doesn't work well.

**Comment by heapcrash** [comment]
Managed to get `zargparse` to work as long as I manually remove the `pwnstrip` command from the generated completion.

**Comment by heapcrash** [comment]
@ChocolateOverflow can you try the completion I've added in #1903?

**Comment by heapcrash** [comment]
Also check out #1904 for bash

**Comment by vulns-are-features-too** [comment]
@heapcrash I'm using zsh and the completion seems to work fine with a quick test, though `pwnstrip` isn't listed in the initial subcommand as expected.

**Comment by heapcrash** [comment]
For whatever reason the pwnstrip command was aliased to some other command,
so I just removed it.  Works for 99% of the cases though.
