### ISSUE TITLE
Get "BrokenPipeError" while closing process.proc.stdin

### ISSUE THREAD

**Issue by RoderickChan** [Gallopsled/pwntools#1936]
After upgrading pwntools in Ubutnu-18.04. I get a stang `BrokenPipeError` output occurred on `pwnlib/tubes/process.py:786`. I find that only `self.proc.stdin` cannot be closed normally in function `process.close()` after testing source code. I think it's a bug.

simple `test.c`:
```c
int main()
{
    puts("Hello world!");
    return 0;
}
```
`test.py`:
```python
from pwn import *
io = process("./test")
io.interactive()
```
exec `test.py` and get output:
```
[+] Starting local process './test2': pid 12462
[*] Switching to interactive mode
Hello world!
$
[*] Got EOF while reading in interactive
$
[*] Process './test2' stopped with exit code 0 (pid 12462)
[*] Got EOF while sending in interactive
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pwnlib/tubes/process.py", line 786, in close
    fd.close()
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by Twe1v0o** [comment]
I also encountered this problem. so do you have a feasible solution？

**Comment by RoderickChan** [comment]
> I also encountered this problem. so do you have a feasible solution？

use `try..catch..` to catch the exception or add some conditional statements to validate `fd` for current process
