### ISSUE TITLE
recv_regex but it returns captures

### ISSUE THREAD

**Issue by tsheinen** [Gallopsled/pwntools#1962]
A pattern I do a lot when CTFing is "read a blob of data, apply regex, extract data". It's not exactly a huge issue but its still a few extra lines and I feel like it's a common enough pattern to be worth implementing. I'm envisioning a parameter for the recvregex family that will return a tuple of the captures instead of the matched string but i'm not super picky.  I'll see about implementing it myself and making a PR when I can find some time.

**Comment by caprinux** [comment]
Hey I think thats a great idea.

As of know p.recvuntil() only receives until a matched string, but I think it would be a pretty cool and nice feature to have a p.recvregex() that only receives a certain capture group and all the other content prior to the recvregex(). 

As of know that would take an extra line
```py
# example to receive CTF{.+}
p.recvuntil(until string before "CTF")
p.recvuntil(b"}")
# or we could have
p.recvregex("CTF{.+}") # stops receiving upon hitting first match
```

But as for this:

> return a tuple of the captures instead of the matched string

I'm not sure about receiving tuple of the captures, how do you envision it?
how would pwntools know how many captures to receive before terminating?
Are you looking at a p.recvline(), p.recvall() or p.recvuntil()?

Perhaps we could add an argument to all of the existing `recv`, where it first receives the data and regexes it for capture groups.

i.e.
```py
p.recvall("CTF{.+}", regex=True)
```

Great idea though and I look forward to its implementation :)

**Comment by Arusekk** [comment]
We already have recvpred or recvline_pred or what it is called for some use cases.

Email z niedzieli, 12 września 2021 od Elmy:
> Hey I think thats a great idea.
> 
> As of know p.recvuntil() only receives until a matched string, but I think it would be a pretty cool and nice feature to have a p.recvregex() that only receives a certain capture group and all the other content prior to the recvregex(). 
> 
> As of know that would take an extra line
> ```py
> # example to receive CTF{.+}
> p.recvuntil(until string before "CTF")
> p.recvuntil(b"}")
> # or we could have
> p.recvregex("CTF{.+}") # stops receiving upon hitting first match
> ```
> 
> But as for this:
> 
> > return a tuple of the captures instead of the matched string
> 
> I'm not sure about receiving tuple of the captures, how do you envision it?
> how would pwntools know how many captures to receive before terminating?
> Are you looking at a p.recvline(), p.recvall() or p.recvuntil()?
> 
> Perhaps we could add an argument to all of the existing `recv`, where it first receives the data and regexes it for capture groups.
> 
> i.e.
> ```py
> p.recvall("CTF{.+}", regex=True)
> ```
> 
> Great idea though and I look forward to its implementation :) 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Gallopsled/pwntools/issues/1962#issuecomment-91756454

-- 
Wysłane z mojego urządzenia Sailfish

**Comment by tsheinen** [comment]
I don't think the predicate receive functions are quite what I'm looking for because they still just return the entire matched bytes. I want to flatten the workflow of "receive data, apply regex, extract captures" into "provided a recv function a regex with capture groups and receive the captured data once it matches" and I thought it'd be generally convenient enough to be worth contributing back.

**Comment by heapcrash** [comment]
Thanks for the idea but we're way ahead of you!  Check out `recvregex` and its friends here:

https://docs.pwntools.com/en/latest/tubes.html?highlight=recvregex#pwnlib.tubes.tube.tube.recvregex

**Comment by tsheinen** [comment]
I was under the impression that recvregex has essentially the same behavior as recvuntil except it applies a regex instead of a string comparison. What i'm looking for is something like this. 

`The address is 11234123`

And I want something like `r.recvregex("([0-9]+)", capture=True)` which returns `11234123` instead of `The address is 11234123`

**Comment by caprinux** [comment]
Besides is it just me or is the regex slightly broken? `+` and `*` doesnt seem to be working for me 🤔 

```py
>>> from pwn import *
>>> t = tube()
>>> t.recv_raw = lambda n: b"The address is 11234123"
>>> t.recvregex("([0-9]+)")
<stdin>:1: BytesWarning: Text is not bytes; assuming ASCII, no guarantees. See https://docs.pwntools.com/#bytes
b'The address is 1'
```

**Comment by tsheinen** [comment]
That looks correct to me; recv operates byte by byte so as soon as you have one number it matches and returns. You can probably solve it by making it match something after the number. In this case that's difficult but if you had something afterwards you could match that.

**Comment by heapcrash** [comment]
I think it would definitely be useful to have something that does group capture as-a-feature.  

I think we have a few options, the easiest is to check the type of the input to be a `re.Pattern` object (we already transform the input into one) and if the original input was one, return the result of the `Pattern` on the data.

Then the user can just use `.groups(...)` on the result.

This realistically only saves like a line or two vs:

```py
pattern = rb'(0x[A-Fa-f0-9]+)'
data = io.recvregex(pattern)
match = re.search(pattern, data)
```

vs

```py
pattern = re.compile(rb'(0x[A-Fa-f0-9]+)')
match = io.recvregex(pattern)
```

Since the default argument for `exact=False`, the predicate used is `re.search` not `re.match` so `match.group()` should be the full match and `match.groups()` would have any user-defined capture groups.
