### ISSUE TITLE
Bug / Enhancement: Compatibility of `six.pretty.install()` with Pwntools

### ISSUE THREAD

**Issue by heapcrash** [Gallopsled/pwntools#1963]
Rich is a neat Python library for making things color-y and pretty.

If one does this in a REPL, it explodes on pwnlib.args.PwnlibArgs.

```py
>>> from pwn import *
>>> import rich.pretty
>>> rich.pretty.install()
>>> locals()
```

We should fix this so that it works nicely.

**Comment by zachriggle** [comment]
This is a neat idea, and definitely useful locally -- but I don't think it's something we should foist upon all consumers of Pwntools!

Thanks @heapcrash ❤️
