### ISSUE TITLE
pwn.shellcraft.linkat second argument is incorrect

### ISSUE THREAD

**Issue by ConnorNelson** [Gallopsled/pwntools#1964]
https://github.com/Gallopsled/pwntools/blob/bd12d1874f17e1fd6a9b26411ccc7ccd6c31f4cb/pwnlib/shellcraft/templates/common/linux/syscalls/linkat.asm#L30

`from` should be `from_`. The current implementation makes it not possible to pass a string.

**Comment by ConnorNelson** [comment]
I would be happy to create a PR, but it's not clear if something is wrong with some auto-generator (located where?) or if the correct fix is to just directly patch this file.

**Comment by Arusekk** [comment]
I believe it was sth like pwnlib/shellcraft/data/generator.py; I think that the argument name strings should be without the underscore, too, only the python variables conflicting with python keywords
