### ISSUE TITLE
pwnlib.tubes.remote.remote duplicates implementation of socket.create_connection

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#197]
The code [here](https://github.com/Gallopsled/pwntools/blob/master/pwnlib/tubes/remote.py#L106-L129) re-implements the standard library routine [`socket.create_connection`](https://docs.python.org/2/library/socket.html#socket.create_connection).

Outside of the status messages of it trying different IPs, is there another reason to have re-implemented this?

**Comment by IdolfHatler** [comment]
@zachriggle Do you still think we should do this, or can I close it?

**Comment by zachriggle** [comment]
I had an implementation of this locally that I never pushed out.  The general feeling I'd reached was that it wasn't worth it.  You end up with a special case for TCP (create_connection) and just using the same code we have for everything else.

**Comment by zachriggle** [comment]
Also looks like I already actually commited some code so maybe I didn't lose it?

**Comment by zachriggle** [comment]
I can't find out what branch that commit belonged to, hmm
