### ISSUE TITLE
Is there a reason of using EOFError('Not implemented') instead of NotImplementedError in recv_raw and send_raw?

### ISSUE THREAD

**Issue by maple3142** [Gallopsled/pwntools#1970]
Currently, `recv_raw` and `send_raw` in `tube.py` use `EOFError('Not implemented')`: https://github.com/Gallopsled/pwntools/blob/bd12d1874f17e1fd6a9b26411ccc7ccd6c31f4cb/pwnlib/tubes/tube.py#L1293-L1315 
But many other functions uses `NotImplementedError`.

If it is possible, I think it should be changed to `NotImplementedError` so that [pylance can correctly detect unreachable code](microsoft/python-type-stubs#203).

**Comment by Arusekk** [comment]
I believe this was the fail-safe choice in case someone tried receiving on a send-only tube, or sending on a recv-only one.

I don't know whether NotImplementedError would be a better exception, maybe it would.

**Comment by mebeim** [comment]
> I believe this was the fail-safe choice in case someone tried receiving on a send-only tube, or sending on a recv-only one.

That makes sense, but I would argue that `NotImplementedError` is the de-facto standard exception to raise in such a case. `EOFError` has just a logically different meaning. After all, other methods like e.g. `can_recv_raw()` do raise `NotImplementedError` correctly. Would you consider changing this to `NotImplementedError`? I could submit a PR for this and other instances.
