### ISSUE TITLE
AttributeError: module 'pwnlib' has no attribute 'update' after Converting to EXE in pyinstaller

### ISSUE THREAD

**Issue by ycsvenom** [Gallopsled/pwntools#1985]
python Version=3.9.7
pwntools Version=4.6.0
this is my code:
![image](https://user-images.githubusercontent.com/58179412/137147534-3bc8eac4-f80c-425d-81d1-a9b9da2e2625.png)

in the first conversion it gave me `ModuleNotFound`  or `FileNotFoundError` for `pwnlib` and i have replace `datas` in `pyinstaller spec` file to the actual directory as shown:
for more information about that behavior [HERE ](https://stackoverflow.com/questions/69533214/pyinstaller-isnt-converting-or-generate-a-corrupted-exe-when-pwn-package-is-i)
![image](https://user-images.githubusercontent.com/58179412/137147346-0cfac551-7828-4776-b477-ae05acf71f70.png)

and it kind of work but when ever i tried to Convert it, it gives me this error now:
![image](https://user-images.githubusercontent.com/58179412/137148007-f35586ba-cbc3-457f-a06b-bbb4ace57fe0.png)

i even tried to reach it's temp folder to check if `update.py` exists or not by and i found it:
![image](https://user-images.githubusercontent.com/58179412/137148824-0f64a82a-82f0-4eab-ab4a-41cdad81341f.png)

now i really need some help because i tried everything (literally everything, i have fixed some errors by checking some values in `pkg_resources.get_distribution` and `PyInstaller.utils.hooks.collect_all`)
and i really need `pwntools` for my Client-Server project instead of the low level `socket` that i got tired of

**Comment by zachriggle** [comment]
This is almost definitely an unsupported configuration.  I would recommend checking out the environment variable `PYTHONVERBOSE=4` set.

I'm not sure how to do this with Py2Exe, and Pwntools is generally not supported on Windows hosts in the first place.

On my machine, I can do this, for example:

```
$ PYTHONVERBOSE=4 python3 -c 'import pwnlib.update' 2>&1 | grep 'pwnlib.update'
# trying /Users/zachriggle/github.com/pwntools/pwnlib/update.cpython-38-darwin.so
# trying /Users/zachriggle/github.com/pwntools/pwnlib/update.abi3.so
# trying /Users/zachriggle/github.com/pwntools/pwnlib/update.so
# trying /Users/zachriggle/github.com/pwntools/pwnlib/update.py
# /Users/zachriggle/github.com/pwntools/pwnlib/__pycache__/update.cpython-38.pyc matches /Users/zachriggle/github.com/pwntools/pwnlib/update.py
import 'pwnlib.update' # <_frozen_importlib_external.SourceFileLoader object at 0x1042f2d30>
# cleanup[2] removing pwnlib.update
# destroy pwnlib.update
```

**Comment by ycsvenom** [comment]
> This is almost definitely an unsupported configuration. I would recommend checking out the environment variable `PYTHONVERBOSE=4` set.
> 
> I'm not sure how to do this with Py2Exe, and Pwntools is generally not supported on Windows hosts in the first place.
> 
> On my machine, I can do this, for example:
> 
> ```
> $ PYTHONVERBOSE=4 python3 -c 'import pwnlib.update' 2>&1 | grep 'pwnlib.update'
> # trying /Users/zachriggle/github.com/pwntools/pwnlib/update.cpython-38-darwin.so
> # trying /Users/zachriggle/github.com/pwntools/pwnlib/update.abi3.so
> # trying /Users/zachriggle/github.com/pwntools/pwnlib/update.so
> # trying /Users/zachriggle/github.com/pwntools/pwnlib/update.py
> # /Users/zachriggle/github.com/pwntools/pwnlib/__pycache__/update.cpython-38.pyc matches /Users/zachriggle/github.com/pwntools/pwnlib/update.py
> import 'pwnlib.update' # <_frozen_importlib_external.SourceFileLoader object at 0x1042f2d30>
> # cleanup[2] removing pwnlib.update
> # destroy pwnlib.update
> ```

Thanks for Replying
i have actually Succeeded on Converting my program into EXE
my problem was that i have installed `pwnlib` as individual package 
that cause the problem 
and i have added two lines into `pyinstaller spec` file but thanks
