### ISSUE TITLE
Update requirement to use unicorn-engine 1.0.3 or unicorn2

### ISSUE THREAD

**Issue by Qynklee** [Gallopsled/pwntools#1986]
When install pwntools via pip with command: `pip install pwntools` , it requires unicorn-engine >1.0.2rc1 - 1.0.2rc4.
But some other lib use pwntools >=1.0.3 and unicorn-engine will be bump up to unicorn2. I think we need to update :D

**Comment by Arusekk** [comment]
Closed by #1932 
(released in 4.7.0)
