### ISSUE TITLE
Disable fancy terminal stuff for repl.it

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#2001]
It seems that Pwntools works pretty great in repl.it!

Unfortunately, some wonky things happen unless run with `PWNLIB_NOTERM=1` or the value is set before importing pwntools.

We already have some workarounds for Jupyter and other notebooks.  It looks like we should be able to check for the `REPL_ID` environment variable and disable it.

**Comment by peace-maker** [comment]
If there are users of repl.it stumbling on this issue, we can add this easily. Please leave a comment in that case. I'll close this for now, because it seems like a really niche tool to use pwntools on and no further activity on this issue.
