### ISSUE TITLE
STDIN from one process to another one behaves differently when the order changed

### ISSUE THREAD

**Issue by mosheDO** [Gallopsled/pwntools#2008]
So I'm trying to send one process STDOUT to another STDIN.
and I try both snippet of code below but one worked while the other didn't and I couldn't understand why

> Worked

```
In [4]: # %load my_script.py 
   ...: import pwn 
   ...: import glob 
   ...:  
   ...: path = glob.glob('/challenge/embryoio_level*') 
   ...:  
   ...: p = pwn.process(path)   
   ...: cat = pwn.process('cat', stdout=p.stdin) 
   ...: p.interactive()   
``` 
   
 > NOT WORKING DON'T KNOW WHY
```
   In [20]: # %load my_script.py 
    ...: # %load my_script.py 
    ...: import pwn 
    ...: import glob 
    ...:  
    ...: path = glob.glob('/challenge/embryoio_level*') 
    ...:  
    ...: #p = pwn.process(path)   
    ...: cat = pwn.process('cat', close_fds = False) 
    ...: pwn.info("QQQ "+ str(cat.stdout)) # prints [*] QQQ <_io.FileIO name=92 mode='rb+' closefd=True>
    ...: p = pwn.process(path, stdin=cat.stdout)  
    ...: pwn.info("QQQ "+ str(p.stdin))  # prints [*] QQQ None
    ...: p.interactive()     
```

Basically both programs are sending stdout of cat to stdin of the process, but only the dirst one works, Why?

**Comment by Arusekk** [comment]
This is generally not supported the way you tried to do it, while it might work, we do not guarantee anything.  See [`tube1 << tube2`](http://docs.pwntools.com/en/dev/tubes.html#pwnlib.tubes.tube.tube.__lshift__) for more details about connecting tubes inputs and outputs together.  Bonus: this works even for tubes that have no file descriptors whatsoever.
