### ISSUE TITLE
Is linux.execve deprecated?

### ISSUE THREAD

**Issue by A1-exe** [Gallopsled/pwntools#2019]
Hello, I came across some code examples that use `shellcraft.linux.execve` and I was wondering if it has since been deprecated? It still works, but it does not show up anywhere in the documentation, nor when I use `shellcraft --list`.

**Comment by zachriggle** [comment]
It might not have actual documentation, as all of the syscalls are done somewhat dynamically.

You can always look at the docs via `pwn shellcraft`, e.g.

```
$ pwn shellcraft i386.linux.execve -?
execve(path, argv, envp) -> str

Invokes the syscall execve.

See 'man 2 execve' for more information.

Arguments:
    path(char*): path
    argv(char**): argv
    envp(char**): envp
Returns:
    int
```

**Comment by Arusekk** [comment]
It resides under shellcraft.linux.**syscalls**.execve; this is why you might not see it under that name.

-- 
Wysłane z mojego urządzenia Sailfish
