### ISSUE TITLE
Gdb won't work in pwn template

### ISSUE THREAD

**Issue by Antonio-Ciociola** [Gallopsled/pwntools#2030]
It won't open a new terminal with gdb.
Fix add env={} or something with env.

```
def start_local(argv=[], *a, **kw):
    '''Execute the target binary locally'''
    if args.GDB:
        return gdb.debug([exe.path] + argv, gdbscript=gdbscript, *a, **kw)
    else:
        return process([exe.path] + argv, *a, **kw)
```
Doesn't work

```
def start_local(argv=[], *a, **kw):
    '''Execute the target binary locally'''
    if args.GDB:
        return gdb.debug([exe.path] + argv, env={}, gdbscript=gdbscript, *a, **kw)
    else:
        return process([exe.path] + argv, *a, **kw)
```

Works

**Comment by peace-maker** [comment]
This seems to highly depend on the terminal setup you're using. Try setting `context.terminal` to a proper argv array to open a new terminal window in your setup.

**Comment by peace-maker** [comment]
Consider adding special handling for your terminal emulator if it is widely used to [`run_in_new_terminal`](https://github.com/Gallopsled/pwntools/blob/d10c70fb32b7e8db595b24cf7e6d057a44a57191/pwnlib/util/misc.py#L249) please.

With #2257 you can create your own tweaked `pwn template` template which includes the wiped environment as you see it too.
