### ISSUE TITLE
ROP.find_stack_adjustment() is missing a return value

### ISSUE THREAD

**Issue by Mitsuzu** [Gallopsled/pwntools#2032]
```python
def find_stack_adjustment(self, slots):
    self.search(move=slots * context.bytes)
```

`self.search()` just returns a `Gadget` and does not modify the ROP `self`. So the function `find_stack_adjustment()` actually does nothing.

Perhaps a `return` needs to be added.

**Comment by fercevik729** [comment]
I went ahead and added the missing `return` but maybe we should add some docs to this function as well.
