### ISSUE TITLE
Why `tubes.buffer.Buffer` is subclass of Exception?

### ISSUE THREAD

**Issue by tkmikan** [Gallopsled/pwntools#2034]
I am debugging some issue related to tubes, and find calling `str` or `repr` on `Buffer` instance gives confusing result, due to the `Exception` inheritance.

https://github.com/Gallopsled/pwntools/blob/1238fc359eb72313d3f82849b2effdb7063ab429/pwnlib/tubes/buffer.py#L7

**Comment by Arusekk** [comment]
I have honestly no idea, but you can try if the CI still passes without it. If so, it might be just some legacy decision.

**Comment by tkmikan** [comment]
Confirmed that CI passes without it, submitting a PR to remove it
