### ISSUE TITLE
Double decoding in util.packing._need_text

### ISSUE THREAD

**Issue by zupd** [Gallopsled/pwntools#2050]
I noticed that if you send a bytestring to e.g. log.info(), you get an AttributeError:
`AttributeError: 'str' object has no attribute 'decode'`

This is because of the following line:
https://github.com/Gallopsled/pwntools/blob/ef698d4562024802be5cc3e2fa49333c70a96662/pwnlib/util/packing.py#L1051

If the param for _need_text is a bytestring and context.encoding = auto, then it will try to decode the string as seen in https://github.com/Gallopsled/pwntools/blob/ef698d4562024802be5cc3e2fa49333c70a96662/pwnlib/util/packing.py#L1043 
If this is successful it will then try to decode it one more time in the last return statement which will cause an exception. 

If encoding is auto it will iterate over 3 different encodings and try to decode. So the second decode will then use the last encoding that was tried above. However, if all encodings get a UnicodeDecodeError, it will still try to use that last encoding to decode it again in the return statement.

**Comment by zupd** [comment]
Think we can fix it this way #2051

**Comment by Arusekk** [comment]
Fixed by #2051
