### ISSUE TITLE
Add formats for hex

### ISSUE THREAD

**Issue by vulns-are-features-too** [Gallopsled/pwntools#2071]
The current `pwn hex` just outputs the hexadecimal digits. However, I sometimes want hex in different formats like `\x41` and `0x41` and even with spaces between each character.

Possible flags:

- `-x`: appends `\x` to each hex
- `-0`: appends `0x` to each hex
- `-s`: adds spaces between hex chars

Sample output:

```
$ pwn hex -x "ABCD"
\x41\x42\x43\x44

$ pwn hex -0 "ABCD"
0x410x420x430x44

$ pwn hex -s "ABCD"
41 42 43 44

$ pwn hex -sx "ABCD"
\x41 \x42 \x43 \x44

$ pwn hex -s0 "ABCD"
0x41 0x42 0x43 0x44
```

This would be very helpful for working with different languages and crafting hex payloads. The spaces also help with readability for demos and the like.

**Comment by Arusekk** [comment]
Idea: `-c` for commas between hex chars?
