### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by wk253765** [Gallopsled/pwntools#2078]
Hi!
I'm getting this error **ValueError: not enough values to unpack (expected 2, got 1)**
when running this python3 script below:
```
from pwn import *

elf = context.binary = ELF('./vuln-32')
libc= elf.libc
```

Wonder what is the problem and how to fix it？

**Comment by Arusekk** [comment]
What is the full python traceback?  The error message itself does not say anything helpful at all.  What binary are you trying to open?

**Comment by wk253765** [comment]
> What is the full python traceback? The error message itself does not say anything helpful at all. What binary are you trying to open?

Thanks for your reply!
The full traceback is as below:
![traceback](https://user-images.githubusercontent.com/108326119/178262942-fdd58d91-33ee-4c8e-8cd7-311570f57f63.PNG)



and I'm trying to open the binary of libc that it's using.
The other day I used this command `libc = elf.libc` to open another binary file, did not raise an error, don't know if it's the problem of the binary file itself
![noerror](https://user-images.githubusercontent.com/108326119/178264041-c6db87ec-ef69-42a5-a12b-a6a4a67ecbe0.PNG)

**Comment by Arusekk** [comment]
Could you try adding something like print(repr(line)) in pwntools code before this line.split()?  I wonder what is the cause of this line not having any `-` sign.

**Comment by peace-maker** [comment]
We cannot investigate this further without more information. If you're still having this issue please re-open.
