### ISSUE TITLE
Printing string to terminal skips character following certain non-printable characters

### ISSUE THREAD

**Issue by gblomqvist** [Gallopsled/pwntools#2094]
# Description
Printing a string to a terminal after running `from pwn import *` skips any character immediately following certain non-printable characters.

# Example
Run the following:
```sh
$ python -c 'from pwn import *; print("A\x10AB")'
```
Expected output:
```sh
b'A\x10AB'
```
Actual output:
```sh
b'A\x10B'
```

# Identified cause and suggested fix
The function [`parse()` in `pwnlib/term/term.py`](https://github.com/Gallopsled/pwntools/blob/01df19d360566fa1f58c3f8caae15ce25fe32d56/pwnlib/term/term.py#L255) may increment the buffer index `i` twice, first on line 330 and then on line 336. The double increment occurs when line 330 is run and `_graphics_mode` is `False`, because if line 330 is run then `x` is `None`. I suggest the following fix:
```diff
diff --git a/pwnlib/term/term.py b/pwnlib/term/term.py
index b300a5f..575b771 100644
--- a/pwnlib/term/term.py
+++ b/pwnlib/term/term.py
@@ -326,14 +326,14 @@ def parse(s):
         elif c == 0x0d:
             x = (CR, None)
             i += 1
-        else:
-            i += 1
 
-        if _graphics_mode:
-            continue
         if x is None:
             x = (STR, [six.int2byte(c) for c in bytearray(b'\\x%02x' % c)])
             i += 1
+
+        if _graphics_mode:
+            continue
+
         if x[0] == STR and out and out[-1][0] == STR:
             out[-1][1].extend(x[1])
         else:
```
Any thoughts?

**Comment by Arusekk** [comment]
Thanks!
Fun fact: I am starting to use email workflow of Git and it worked to just `|git am` GitHub's auto-sent e-mail report of this issue in mutt. In case you are interested. 😄

**Comment by gblomqvist** [comment]
Oh, cool, how convenient! :smiley:
