### ISSUE TITLE
How to set breakpoint commands from GDB Python API?

### ISSUE THREAD

**Issue by gsingh93** [Gallopsled/pwntools#2096]
I'm able to set breakpoints using the experimental support for the Python GDB API, but I'm not able to set any commands that should be executed when that breakpoint is hit. According to the [docs](https://sourceware.org/gdb/onlinedocs/gdb/Breakpoints-In-Python.html), `Breakpoints.commands` is writable and can be set to the commands you want to run when the breakpoint is hit. I'm trying something like this:
```
b = p.gdb.Breakpoint('main')
b.commands = 'echo commands are working'
p.gdb.continue_nowait()
```

The breakpoint gets hit, but no commands are executed. Am I doing something wrong here, or are we not exposing this functionality for some reason?

I'm using version 4.8.0 on Ubuntu 22.04.

**Comment by Arusekk** [comment]
This should generally work, as this is simple RPyC remote object access.  However, if you have some time to investigate this further, that would be awesome.
