### ISSUE TITLE
Running doctest gives a bunch of warnings

### ISSUE THREAD

**Issue by Idolf** [Gallopsled/pwntools#211]
From Travis CI:

    /home/travis/build/Gallopsled/pwntools/pwnlib/dynelf.py:docstring of pwnlib.dynelf.DynELF:34: ERROR: Unknown target name: "dt_pltgot".
    /home/travis/build/Gallopsled/pwntools/docs/source/index.rst:26: WARNING: toctree glob pattern u'useragents' didn't match any documents
    /home/travis/build/Gallopsled/pwntools/docs/source/install.rst:57: WARNING: Explicit markup ends without a blank line; unexpected unindent.
    /home/travis/build/Gallopsled/pwntools/docs/source/install.rst:57: WARNING: Inline literal start-string without end-string.
    /home/travis/build/Gallopsled/pwntools/docs/source/install.rst:57: WARNING: Inline interpreted text or phrase reference start-string without end-string.
    /home/travis/build/Gallopsled/pwntools/pwnlib/log.py:docstring of pwnlib.log.Logger.progress:12: WARNING: Definition list ends without a blank line; unexpected unindent.
    /home/travis/build/Gallopsled/pwntools/pwnlib/util/packing.py:docstring of pwnlib.util.packing.routine:1: WARNING: Inline strong start-string without end-string.
    /home/travis/build/Gallopsled/pwntools/pwnlib/util/proc.py:docstring of pwnlib.util.proc.pidof:8: WARNING: Bullet list ends without a blank line; unexpected unindent.

**Comment by zachriggle** [comment]
This is no longer true.
