### ISSUE TITLE
Can't receive some output when using `spawn_process`

### ISSUE THREAD

**Issue by Ultimator14** [Gallopsled/pwntools#2131]
When opening a listener, spawning a process and attaching via remote (as explained in the [docs](https://docs.pwntools.com/en/stable/tubes/sockets.html#pwnlib.tubes.listen.listen)), I don't receive all data for certain programs.

## Demo program
This is the smallest program I could make that has this problem.

demo.c
```C
#include <unistd.h>
#include <stdio.h>

int main(void) {
    char msg[14];

    while(1){
	ssize_t r = read(STDIN_FILENO, msg, sizeof msg);

	printf("This message is not displayed\n");
    }
    return 0;
}
```

## Working
When running the program via terminal, I get this output
```
myinput1
This message is not displayed
myinput2
This message is not displayed
...
```

The same thing also works when using `process`.
working.py
```python
from pwn import *

p = process("./demo")
p.interactive()
```
output
```
$ myinput1
[DEBUG] Sent 0x9 bytes:
    b'myinput1\n'
[DEBUG] Received 0x1e bytes:
    b'This message is not displayed\n'
This message is not displayed
$ myinput2
[DEBUG] Sent 0x9 bytes:
    b'myinput2\n'
[DEBUG] Received 0x1e bytes:
    b'This message is not displayed\n'
This message is not displayed
```

## Not working
However when using sockets, the output is not displayed.

not_working.py
```python
from pwn import *

l = listen(port=9999)
l.spawn_process("./demo")

r = remote("127.0.0.1", 9999)

r.interactive()
```
output
```
$ myinput1
[DEBUG] Sent 0x9 bytes:
    b'myinput1\n'
$ myinput2
[DEBUG] Sent 0x9 bytes:
    b'myinput2\n'
...
```

## Verify on Ubuntu
This also happens on ubuntu.

```bash
# On the host
$ docker pull pwntools/pwntools:stable
$ cd <mydir>
$ docker run --tty --interactive --rm -v "$PWD":/workdir -w /workdir pwntools/pwntools:stable

# In the container
$ cd /workdir
$ gcc -o test test.c
$ python3 not_working.py
[+] Trying to bind to :: on port 9999: Done
[+] Waiting for connections on :::9999: Got connection from ::ffff:127.0.0.1 on port 39358
[+] Opening connection to 127.0.0.1 on port 9999: Done
[*] Switching to interactive mode
$ input1
$ input2
...
```

**Comment by peace-maker** [comment]
Try disabling line buffering in libc in your test program.

```c
setbuf(stdin, NULL);
setbuf(stdout, NULL);
setbuf(stderr, NULL);
```

**Comment by Ultimator14** [comment]
> Try disabling line buffering in libc in your test program

This works but can I do this from pwntools when I have no control over the binary?

**Comment by peace-maker** [comment]
No. You need to go the `stdbuf` or `unbuffer` route. You could implement it in pwntools I guess, by starting the process with PTY as stdin and stdout and then forwarding that to your listen socket, but there is nothing prebuilt for that.

**Comment by Ultimator14** [comment]
Thanks I found a solution. The workaround is actually very simple.  
Here is what I did in case someone has the same problem.

## With client and server running in the same program

localhost.py
```python
from pwn import *

l = listen(port=9999)

p = process("./test")
p.connect_both(l)

r = remote("127.0.0.1", 9999)
r.interactive()
```

## In a client-server environment

server.py
```python
from pwn import *

l = listen(port=9999)
l.wait_for_connection()

p = process("./test")
p.connect_both(l)

l.wait_for_close()
```

client.py
```python
from pwn import *

r = remote("127.0.0.1", 9999)
r.interactive()
```
