### ISSUE TITLE
m1 mac can't building binutils from source successfully

### ISSUE THREAD

**Issue by sheldonl3** [Gallopsled/pwntools#2149]
Try to install pwn environment on my m1 mac
Using "brew install binutils-amd64.rb" commend to build binutils from source (the rb file is get from [binutils repo](https://github.com/Gallopsled/pwntools-binutils/).)
But get error like this:
![截屏2022-12-14 15 38 49](https://user-images.githubusercontent.com/44045052/207534518-539f0b0d-8b31-4f62-ad76-fc652ea8ebbb.png)
Have no idea what to do

**Comment by zachriggle** [comment]
I also see this, it only appears to be an issue on M1 recently, as I've installed these recipes before.

That said, Pwntools does not support macOS, on either x86 or on M1.

In the past it has worked and it was a happy coincidence, but that no longer appears to be the case.  We'd gladly accept a pull request that fixes this!

**Comment by sheldonl3** [comment]
> 

Thanks!

**Comment by sheldonl3** [comment]
> I also see this, it only appears to be an issue on M1 recently, as I've installed these recipes before.
> 
> That said, Pwntools does not support macOS, on either x86 or on M1.
> 
> In the past it has worked and it was a happy coincidence, but that no longer appears to be the case. We'd gladly accept a pull request that fixes this!

Thanks!

**Comment by zachriggle** [comment]
I'm not sure why `makeinfo` is causing errors, but I committed https://github.com/Gallopsled/pwntools-binutils/commit/609cc582290cc0b2893d381806f2e9216604c3b1 which fixes the issue.

**Comment by sheldonl3** [comment]
It works! Thanks!
