### ISSUE TITLE
buggy string output in noninteractive mode

### ISSUE THREAD

**Issue by dm248** [Gallopsled/pwntools#2156]
save this to file and run in noninteractive mode

```py
from pwn import *

b = "\x00test"
print(b)             # outputs \x00est  for some reason (first 't' is eaten)
```

-> looks like a bug(??)

**Comment by dm248** [comment]
Seems to be caused by stdout wrapping - it looks to me like a bug there.

**Comment by heapcrash** [comment]
This is intentional, non-printable characters are displayed as hex-escaped when they escape through the wrapped `sys.stdout`.

If you pipe the output into something like a file or another program, you should get the normal behavior.  This escaping only occurs when dumping to the terminal.

```py
$ python3 b.py
\x00est

$ python3 b.py | phd
00000000  00 74 65 73  74 0a                                  │·tes│t·│
00000006
```

**Comment by Arusekk** [comment]
There is one character missing, though, when escaping occurs.  I see that this is a real bug—would you mind investigating a bit further?
