### ISSUE TITLE
gdbinit breaks with the latest kali installation

### ISSUE THREAD

**Issue by AlienX2001** [Gallopsled/pwntools#2164]
Hey,
So I just updated my kali box yesterday. Here are my specifications
![image](https://user-images.githubusercontent.com/64488123/216100967-35a92e5f-c46f-4a15-aa22-d3a44e8be081.png)

And as you can see I can easily import pwntools
![image](https://user-images.githubusercontent.com/64488123/216101077-90085fc3-e4fc-4d65-9d1d-f04bd3189912.png)

But whenever I start gdb, it says it cant find the module "pwnlib"
![image](https://user-images.githubusercontent.com/64488123/216101409-bfcd05f1-4ac8-48f2-af01-4a86c66c3538.png)

But as you can see I can easily import it in python.

**Comment by AlienX2001** [comment]
This seems like a bug in pwndbg rather than pwntools, but since both of these open source tools are involved, I made issues in both the repositories. The link for the same in the pwndbg repositoy is here. https://github.com/pwndbg/pwndbg/issues/1560#issue-1566423849

**Comment by peace-maker** [comment]
gdb uses its own python installation different from the system wide one. You have to install pwntools in gdb's python. Pwndbgs setup.sh might have info on how to install packages.

**Comment by AlienX2001** [comment]
Right, Thanks
