### ISSUE TITLE
M2 mac error with asm function and at install binutils

### ISSUE THREAD

**Issue by bshyuunn** [Gallopsled/pwntools#2168]
<img width="1582" alt="image" src="https://user-images.githubusercontent.com/87067974/217543663-f6d659cf-ec14-41b6-bf6c-35583f6bcfa9.png">

The following error occurs when calling the asm function
To solve this problem, I also tried the commands at the following [site](https://docs.pwntools.com/en/stable/install/binutils.html).
```
$ brew install https://raw.githubusercontent.com/Gallopsled/pwntools-binutils/master/macos/binutils-$ARCH.rb
```

However, errors also occur during the installation process.
<img width="627" alt="image" src="https://user-images.githubusercontent.com/87067974/217544723-305a4daa-c02e-46f3-8991-56a2e94f74bf.png">

Therefore, I tried to clone [binutils repo](https://github.com/Gallopsled/pwntools-binutils/) and install it myself.
![image](https://user-images.githubusercontent.com/87067974/217545669-6ed18b21-3e8d-43b7-baed-d273ab1fc7d2.png)
But it didn't work either. 

In addition, if I insert it into another arch, the error code may change or the error may not pop.
<img width="1582" alt="image" src="https://user-images.githubusercontent.com/87067974/217546092-cd0dddf7-f15a-4e52-8226-11e69a09ebac.png">
<img width="1582" alt="image" src="https://user-images.githubusercontent.com/87067974/217546245-318a615c-c53a-4a2d-97f6-d92d3efd2d8a.png">

How can I solve this problem?

**Comment by zachriggle** [comment]
You need to specify the architecture by replacing `$ARCH` or setting the `ARCH` environment variable.

**Comment by Arusekk** [comment]
Also as for `brew link --overwrite`, you omitted double-dash and used only one (`-overwrite` vs `--overwrite`).  Hope that helps.

**Comment by fercevik729** [comment]
I have been running into a similar issue on my M2. After executing the following command `brew install https://raw.githubusercontent.com/Gallopsled/pwntools-binutils/master/macos/binutils-aarch64.rb` I get this output: ```Error: Non-checksummed download of binutils-aarch64 formula file from an arbitrary URL is unsupported! `brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.``` I am unsure how to proceed.

**Comment by Arusekk** [comment]
@fercevik729 I found a similar issue with a workaround: https://github.com/jhen0409/react-native-debugger/issues/567#issuecomment-756183480
Please inspect the downloaded file of course. :wink:

**Comment by fercevik729** [comment]
Thank you! I had to do some tweaking but I eventually got around the error by grabbing the raw ruby file via `wget` and then running `brew install binutils-$ARCH.rb` which installed it as a cask without a formulae. Unfortunately when I run `pwn disasm <something>` I'm still getting an exception stating `objdump` couldn't be found even though I have it installed on my machine at `/usr/local/objdump`. I also have the newly installed `aarch64-unknown-linux-gnu-objdump` in `/opt/homebrew/bin` but I'm not sure pwn can find it.

**Comment by peace-maker** [comment]
Can you run objdump in your shell directly? You might need to add that path to your PATH environment variable.

**Comment by Arusekk** [comment]
Do you mean `/usr/local/bin/objdump`?

**Comment by fercevik729** [comment]
Sorry I meant `/usr/bin/objdump` and yes I can run objdump directly and have in the past for some CTF challenges. I have also installed `objdump` from pwnlib's binutils at `/opt/homebrew/bin/aarch64-unknown-linux-gnu-objdump` and am able to run that as well. Maybe pwnlib is not able to find it under its current name?
