### ISSUE TITLE
Cannot get output of pwnlib.adb.packages()

### ISSUE THREAD

**Issue by kylemd** [Gallopsled/pwntools#2170]
Sorry if this question is a bit daft, but I'm having some issues trying to work out how to read the output of `pwnlib.adb.packages()`.

Looking at the code it should be returning an array of values, however no matter how I handle it I get the error:

`a bytes-like object is required, not 'str'`

Is anybody able to assist?

**Comment by peace-maker** [comment]
That function appears to have been missed while updating for Python 3 compatiblilty. Would you be willing to fix this in a PR?

**Comment by fercevik729** [comment]
I think this is because the data from `recv_all()` is never decoded to a 'utf-8' string. I have linked a PR.

**Comment by fercevik729** [comment]
In `sock.recv_all()` the code comments assert that it returns a `str`, but the call to the superclass `tube.recv_all` within the method return a byte array which is never decoded.
