### ISSUE TITLE
ROP with custom ABI fails to generate

### ISSUE THREAD

**Issue by bad5ect0r** [Gallopsled/pwntools#2172]
I've defined the following ABI based on a CTF challenge:

```py
    call_conv = abi.ABI("rsp", [], 8, 0)
```

I then create the following ROP chain:

```py
    srop = pwn.ROP(ELF)
    srop.call("write", [ELF.address, 0xf], call_conv)
    srop.raw(0x1)
```

When I run `print(srop.dump())` I expect to see something like this:

```
0x0000:         0x401017 write(0x400000, 15)
0x0008:              0x1 <return address>
0x0010:         0x400000 arg0
0x0018:              0xf arg1
```

But instead pwntools just hangs.

**Comment by Arusekk** [comment]
Where it hangs? Does it show a stack traceback when interrupted?

Email z wtorku, 28 lutego 2023 od bad5ect0ra:
> I've defined the following ABI based on a CTF challenge:
> 
> ```py
>     call_conv = abi.ABI("rsp", [], 4, 0)
> ```
> 
> I then create the following ROP chain:
> 
> ```py
>     srop = pwn.ROP(ELF)
>     srop.call("write", [ELF.address, 0xf], call_conv)
>     srop.raw(0x1)
> ```
> 
> When I run `print(srop.dump())` I expect to see something like this:
> 
> ```
> 0x0000:         0x401017 write(0x400000, 15)
> 0x0008:              0x1 <return address>
> 0x0010:         0x400000 arg0
> 0x0018:              0xf arg1
> ```
> 
> But instead pwntools just hangs.

-- 
Wysłane z mojego urządzenia Sailfish

**Comment by peace-maker** [comment]
Hm, I cannot reproduce. This works fine as far as I can tell, please post more information and/or scripts and binaries where the script hangs.
```py
from pwn import *
program = context.binary = ELF('/bin/sh')

call_conv = pwnlib.abi.ABI("rsp", [], 8, 0)

rop = ROP(program)
rop.call("write", [program.address, 0xf], call_conv)
rop.raw(0x1)
print(rop.dump())
```

```
0x0000:           0x4694 write(0, 15)
0x0008:           0x50d7 <adjust @0x20> pop rbp; pop r12; ret
0x0010:              0x0 arg0
0x0018:              0xf arg1
0x0020:              0x1
```
