### ISSUE TITLE
Stack is no longer executable if missing PT_GNU_STACK

### ISSUE THREAD

**Issue by ghost** [Gallopsled/pwntools#2181]
If the ELF program header `PT_GNU_STACK` is missing, `ELF.execstack` wrongly assumes that the stack is executable because of `READ_IMPLIES_EXEC`, but since [this commit](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9fccc5c0c99f238aa1b0460fccbdb30a887e7036),  `READ_IMPLIES_EXEC` is disabled on x86_64.

**Comment by Arusekk** [comment]
1. Did you encounter an actual binary with missing PT_GNU_STACK on amd64? Can you share where it came from?
2. Would you mind submitting a pull request updating the message to something like `'executable on linux <5.8'`?

**Comment by ghost** [comment]
1. Yes, I encountered 2 binaries missing that header, both of them are `pwnable.kr` challenges specifically [echo1](http://pwnable.kr/bin/echo1) and [echo2](http://pwnable.kr/bin/echo2).
    > on amd64?

    The remote machine is x86, but my machine is amd64.
2. I'm on it. Which message should I update?

**Comment by Arusekk** [comment]
So... the binaries are x86, and their stack is executable even on your machine (see the ia32 column in the table you refer to).

The message to be updated is ELF.execstack / ELF.nx combined with ELF.checksec function printing the info.  See other tristate values (like RELRO = on/off/partial), which should guide you forward with implementation.

**Comment by ghost** [comment]
Yes, the binaries are x86 but the stack is not executable on my machine, the columns in the table I referenced are for the CPU architecture, not the binary architecture.

**Comment by Arusekk** [comment]
That's not correct.  I just checked both `echo1` and `echo2` are amd64 binaries (amd64 = x86-64 = x64 = elf `EM_X86_64` means 64-bit Personal Computer processors instruction set, x86 = 8086, i386, i486, i586, i686 = elf `EM_386` means 32-bit Personal Computer processors instruction set — regardless of whether it is Intel or AMD), they both contain explicit RWX `PT_GNU_STACK` and therefore they both have executable stacks, whether on your machine, on pwnable.kr (which apparently must be 64-bit to run them), or anywhere else.

I think the change you suggested would be useful regardless, but the binaries you provided are not what you tell about them.  Please do a bit more research before submitting your changes to avoid such misunderstandings in the future. :-)

**Comment by ghost** [comment]
You are right about the remote machine and the binaries. I remembered that the stack wasn't executable on my machine, and was on the remote machine, but I failed to remember that the difference originated from the kernel version, not the architecture. Sorry about that.

Running `readelf -l` on the binaries doesn't output `PT_GNU_STACK` but says that `GNU_STACK` is RWE which makes me believe they must have updated them in the passing week, because `GNU_STACK` was missing and the stack wasn't executable. I can contact that about that to make sure if you'd like me to.

**Comment by Arusekk** [comment]
Alright, seems likely, no need to contact them I guess.  It would be best to just start a PR.

**Comment by ghost** [comment]
As it turns out it goes much deeper, the `READ_IMPLIES_EXEC` personality is not added only to ELFs that are missing `PT_GNU_STACK` on amd64 and Linux >= 5.8, there are specific rules for each architecture, for example, on arm, it's added if the version is less than ARMv6.
```c
/*
 * An executable for which elf_read_implies_exec() returns TRUE will
 * have the READ_IMPLIES_EXEC personality flag set automatically.
 *
 * The decision process for determining the results are:
 *
 *                 CPU: | lacks NX*  | has NX     |
 * ELF:                 |            |            |
 * ---------------------|------------|------------|
 * missing PT_GNU_STACK | exec-all   | exec-all   |
 * PT_GNU_STACK == RWX  | exec-all   | exec-stack |
 * PT_GNU_STACK == RW   | exec-all   | exec-none  |
 *
 *  exec-all  : all PROT_READ user mappings are executable, except when
 *              backed by files on a noexec-filesystem.
 *  exec-none : only PROT_EXEC user mappings are executable.
 *  exec-stack: only the stack and PROT_EXEC user mappings are executable.
 *
 *  *this column has no architectural effect: NX markings are ignored by
 *   hardware, but may have behavioral effects when "wants X" collides with
 *   "cannot be X" constraints in memory permission flags, as in
 *   https://lkml.kernel.org/r/20190418055759.GA3155@mellanox.com
 *
 */
int arm_elf_read_implies_exec(int executable_stack)
{
	if (executable_stack == EXSTACK_DEFAULT)
		return 1;
	if (cpu_architecture() < CPU_ARCH_ARMv6)
		return 1;
	return 0;
}
```

Since the `READ_IMPLIES_EXEC` personality depends on the CPU architecture and features, the kernel version, and the binary, it's impossible to determine whether the stack is executable without the context.
The solution that I'm suggesting is:
1. (As @Arusekk proposed) make `ELF.execstack` trinary ("always"/"never"/"read implies exec").
2. Add function `ContextType.read_implies_exec()` that determines whether read permission implies execution permission in the current context.

@Arusekk what do you think?

**Comment by Arusekk** [comment]
I think we can detect all the cases that are known (rwx GNU_STACK = red 'executable stack (explicit)', rw GNU_STACK = green 'NX (explicit)') and others we can detect (red 'executable stack (implicit)').

But for unknown cases we can leave orange/yellow 'unknown (implicit)'.

**Comment by ghost** [comment]
It's possible to detect only ia64 and PowerPC binaries, the reset depends on the hardware or the Linux version.
(to be more accurate, it's possible to detect only binaries that don't target one of the following: x86, amd64, arm, mips).

Here's a summary:
- ia64:
  ```c
  #define elf_read_implies_exec(ex, executable_stack)					\
	  ((executable_stack!=EXSTACK_DISABLE_X) && ((ex).e_flags & EF_IA_64_LINUX_EXECUTABLE_STACK) != 0)
  ```
  https://github.com/torvalds/linux/blob/d06f5a3f7140921ada47d49574ae6fa4de5e2a89/arch/ia64/include/asm/elf.h#L203-L204
- x86:
  ```c
  #define elf_read_implies_exec(ex, executable_stack)	\
	  (mmap_is_ia32() && executable_stack == EXSTACK_DEFAULT)
  ```
  Depends on whether it's running on arm64, ia32 or x86 and was introduced in Linux 5.8.
  https://github.com/torvalds/linux/blob/d06f5a3f7140921ada47d49574ae6fa4de5e2a89/arch/x86/include/asm/elf.h#L288-L289
- arm:
  ```c
  int arm_elf_read_implies_exec(int executable_stack)
  {
  	if (executable_stack == EXSTACK_DEFAULT)
  		return 1;
  	if (cpu_architecture() < CPU_ARCH_ARMv6)
  		return 1;
  	return 0;
  }
  ```
  Depends on the CPU version.
  https://github.com/torvalds/linux/blob/d06f5a3f7140921ada47d49574ae6fa4de5e2a89/arch/arm/kernel/elf.c#L104-L111
- mips:
  ```c
  int mips_elf_read_implies_exec(void *elf_ex, int exstack)
  {
  	/*
  	 * Set READ_IMPLIES_EXEC only on non-NX systems that
  	 * do not request a specific state via PT_GNU_STACK.
  	 */
  	return (!cpu_has_rixi && exstack == EXSTACK_DEFAULT);
  }
  ```
  Depends on the CPU features.
  https://github.com/torvalds/linux/blob/d06f5a3f7140921ada47d49574ae6fa4de5e2a89/arch/mips/kernel/elf.c#L329-L336
- powerpc:
  ```c
  #ifdef __powerpc64__
  ...
  # define elf_read_implies_exec(ex, exec_stk) (is_32bit_task() ? \
  		(exec_stk == EXSTACK_DEFAULT) : 0)
  #else 
  # define elf_read_implies_exec(ex, exec_stk) (exec_stk == EXSTACK_DEFAULT)
  #endif /* __powerpc64__ */
  ```
  https://github.com/torvalds/linux/blob/d06f5a3f7140921ada47d49574ae6fa4de5e2a89/arch/powerpc/include/asm/elf.h#L82-L108

**Comment by Arusekk** [comment]
Related #1919.
Please make an initial PR with at least red 'executable stack (explicit)', green 'NX enabled (explicit)' and yellow/orange 'GNU_STACK missing (implicit)'.
The differences between architectures are an implementation detail we can consider a bit later.
