### ISSUE TITLE
New Docker hub release

### ISSUE THREAD

**Issue by ZetaTwo** [Gallopsled/pwntools#2187]
Would it be possible to publish a new updated release to https://hub.docker.com/r/pwntools/pwntools ?

**Comment by Arusekk** [comment]
Docker Hub has ended its automated build feature, so we would need to add a GH Actions workflow building images and submitting them to Docker Hub.  And to ghcr.io, just in case Docker.io folks behave unpredictably again.

If you want to try working on that, I would really appreciate it.  It could even be made to only launch on successful tests pass in the ci.yml file.

**Comment by ZetaTwo** [comment]
I see. Yeah I could look into that. I have a few hectic weeks right now but after that I'll gladly take a stab at it.
