### ISSUE TITLE
starting up a process using setarch 

### ISSUE THREAD

**Issue by jstaursky** [Gallopsled/pwntools#2190]
I am trying to use pwntools to mimic the cmdline sequence:
` setarch $(uname -m) -R ./output $(perl -e 'print "AAAABBBB|" . "%p"x174 . "|%p|"')`

where `output` is a compiled c program that is
```c
#include <stdio.h>
#include <string.h>

int target = 0;

void vuln(char *string)
{
    printf(string);

    if (target)
    {
        printf("you have modified the target :)\n");
        printf("target is now: %d\n", target);
    }
}


int main(int argc, char *argv[])
{
    vuln(argv[1]);
    return 0;
}
```
and here is how I have tried to accomplish this
```python
#!/usr/bin/env python3

from pwn import *
import platform

context.arch = "x86_64" 

fmtstring = "AAAABBBB|" + "%p" * 174 + "|%p|"

# Start the program with setarch (this is how we perform "setarch $(uname -m) -R ./output <args>")
io = process(["setarch", "-R", platform.machine(), "./output", fmtstring])

s = io.recvall(2)

print(s)
```

However when I run the python script I am not seeing the same output as when I run the command manually. Now since `setarch -R` has the effect of disabling ASLR, I should be seeing the same output. What am I doing wrong?

**Comment by jstaursky** [comment]
More I think about it, I'm guessing there is probably no easy way for pwntools to intercept the execve call that setarch is probably performing internally after its sets the `personality()` system call to disable ASLR. So there might be nothing that can be done.

**Comment by Arusekk** [comment]
Just specify aslr=False, as the docs say: http://docs.pwntools.com/en/latest/tubes/processes.html#pwnlib.tubes.process.process

It even mentions `setarch -R` explicitly ;)
