### ISSUE TITLE
'pip install -e <source code>' Get metadata error

### ISSUE THREAD

**Issue by M0r41** [Gallopsled/pwntools#2207]
When i use 'pip install -e' to install the latest pwntools, i got 
```
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
```
Then i tried 'pip install pwntools', i got
```
Collecting intervaltree>=3.0 (from pwntools)
  Using cached intervaltree-3.1.0.tar.gz (32 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
```
Finnally i use pycharm to install it, it can be installed successfully, but due to the libffi version, i got  import error
```
ModuleNotFoundError: No module named '_ctypes'
```
I use arch linux, and my python version is 3.10.7, i have installed libffi, its version 8.1.2.

**Comment by Arusekk** [comment]
This is most likely a problem with intervaltree, not pwntools, then. Try to install the one package from distro (e.g. pacman or AUR).

Email z poniedziałku 19 czerwca 2023 od M0r41:
> When i use 'pip install -e' to install the latest pwntools, i got 
> ```
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ```
> Then i tried 'pip install pwntools', i got
> ```
> Collecting intervaltree>=3.0 (from pwntools)
>   Using cached intervaltree-3.1.0.tar.gz (32 kB)
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
> ```
> Finnally i use pycharm to install it, it can be installed successfully, but due to the libffi version, i got  import error
> ```
> ModuleNotFoundError: No module named '_ctypes'
> ```
> I use arch linux, and my python version is 3.10.7, i have installed libffi, its version 8.1.2.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/Gallopsled/pwntools/issues/2207
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***

-- 
Wysłane z mojego urządzenia Sailfish

**Comment by Arusekk** [comment]
This looks like a broken Python installation.  We are unfortunately unable to help more without more information, like full installation logs.
