### ISSUE TITLE
CI: Python 2 runner image removed

### ISSUE THREAD

**Issue by peace-maker** [Gallopsled/pwntools#2209]
Python 2 tests are broken atm. Switch tests to a container?

https://github.com/actions/setup-python/issues/672#issuecomment-1589120020

**Comment by Arusekk** [comment]
+1 for a container ([should be quite easy](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-docker-hub-action) / [method 2](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-running-a-job-within-a-container))

**Comment by Arusekk** [comment]
did not go exactly as well as I planned... https://github.com/Gallopsled/pwntools/actions/runs/5361559647/jobs/9727631250

**Comment by peace-maker** [comment]
Hm, what's the difference? https://github.com/peace-maker/pwntools/actions/runs/5357828539/jobs/9719257773#step:12:59

**Comment by peace-maker** [comment]
Ah, it's something with the pyproject.toml change? Is this fine now after https://github.com/Gallopsled/pwntools/commit/b9cc118a15f409d1ca94e3e2809fa36f18ac0c5b?

**Comment by Arusekk** [comment]
Yes I think that solved the issue (however hacky it might be).  Python from setup-python provided writable global site-packages directory, while Ubuntu's python2.7 obviously did not.  So I made it the same.  It works for CI workflow, and ultimately we will have to get rid of the maintenance burden of supporting py2.7.  But first (at least to me), ghidra/ida/Jython/IronPython must officially support py3.
