### ISSUE TITLE
Waiting for debugger

### ISSUE THREAD

**Issue by Buba98** [Gallopsled/pwntools#2255]
I want to run a script after attaching the process

```python
    if not os.path.exists("logs"):
        os.makedirs("logs")

    timestamp = time.strftime("%Y%m%d_%H%M%S")

    filename = "logs/gdb_log_{now}.txt".format(now = timestamp)
    
    r = process("program")
    gdb.attach(r,gdbscript= """
            start
            set logging file {filename}
            source .gdbinit
               """.format(filename = filename))
```

This script would take a while to execute since the it will iterate for every step of the code

```sh
set logging redirect on
set logging debugredirect on

start

set $_exitcode = -999
set height 0
handle SIGTERM nostop print pass
handle SIGPIPE nostop
define hook-stop
    if $_exitcode != -999
        quit
    end
end

while(1)
    set logging enabled on
    print $sp
    set logging enabled off

    s
end
```

So basically my code is printing on file the stack pointer at every step of the program
I tried to do this directly with the API but it was unclear how to proceed using them following the documentation

After 15 seconds of execution the output will be

```sh
[-] Waiting for debugger: Debugger did not attach to pid 86157 within 15 seconds
```

Now gdb will keep on running the script, the python program will instead keep the run normally.

I haven't found any way to eliminate the timeout.
Is there a way already implemented?

Moreover i would like to know if there is a way to do this process through the APIs of gdb

Thanks in advance

**Comment by peace-maker** [comment]
Have a look at the gdb api example, maybe that gets you started. 
https://github.com/Gallopsled/pwntools/blob/dev/examples/gdb_api.py
That together with the [Python GDB API documentation](https://sourceware.org/gdb/onlinedocs/gdb/Python-API.html#Python-API) should get you a long way. You're welcome to join the [pwntools discord server](https://discord.gg/96VA2zvjCB) for more help!
