### ISSUE TITLE
Pwntools cannot work with pyelftools-0.30

### ISSUE THREAD

**Issue by sces60107** [Gallopsled/pwntools#2260]
I just installed pwntools in my new VM. But I encountered some problems.
```python
/usr/local/lib/python3.10/dist-packages/pwnlib/elf/corefile.py in <module>
     77 
     78 import elftools
---> 79 from elftools.common.py3compat import bytes2str
     80 from elftools.common.utils import roundup
     81 from elftools.common.utils import struct_parse
```
Afterwards, I found that pyelftools just released 0.30 version and it refactors out py3compat.
Therefore, this line won't work anymore.
https://github.com/Gallopsled/pwntools/blob/dev/pwnlib/elf/corefile.py#L79
```python
from elftools.common.py3compat import bytes2str
```

**Comment by sces60107** [comment]
btw, `bytes2str` is moved to `elftools.common.utils`

https://github.com/eliben/pyelftools/blob/v0.30/elftools/common/utils.py#L22

**Comment by peace-maker** [comment]
pyelftools 0.3 removed support for python 2, so we can't update as long as we support python 2 ourselves.

But removing usage of that wrapper is fine either way.

**Comment by swoosh-THU** [comment]
> 我刚刚在我的新虚拟机中安装了 pwntools。但我遇到了一些问题。
> 
> ```python
> /usr/local/lib/python3.10/dist-packages/pwnlib/elf/corefile.py in <module>
>      77 
>      78 import elftools
> ---> 79 from elftools.common.py3compat import bytes2str
>      80 from elftools.common.utils import roundup
>      81 from elftools.common.utils import struct_parse
> ```
> 
> 后来发现pyelftools刚刚发布了0.30版本，并且重构了py3compat。 因此，这条线将不再起作用。 https://github.com/Gallopsled/pwntools/blob/dev/pwnlib/elf/corefile.py#L79
> 
> ```python
> from elftools.common.py3compat import bytes2str
> ```

Yes,  I met the same problem yesterday, then I just changed "elftools.common.py3compat import bytes2str " into "elftools.common.utils.import bytes2str", and work out the problem.

**Comment by peace-maker** [comment]
You can roll back to the previous pyelftools version too until #2261 is merged and we get a new release out.
`pip install pyelftools==0.29`
