### ISSUE TITLE
install 

### ISSUE THREAD

**Issue by yzcmf** [Gallopsled/pwntools#2262]
File "/root/tutorial-env/lib/python3.11/site-packages/pwnlib/elf/corefile.py", line 79, in <module>
 from elftools.common.py3compat import bytes2str
ModuleNotFoundError: No module named 'elftools.common.py3compat'

solution 
-> from elftools.common.py3compat not exists anymore and the bytes2str is now moving into elftools.common.utils
-> change '/root/tutorial-env/lib/python3.11/site-packages/pwnlib/elf/corefile.py' line 79 -> from elftools.common.utils import bytes2str

**Comment by peace-maker** [comment]
Thank you for your report! You can follow the fix in #2261.
Duplicate of #2260
