### ISSUE TITLE
Mixed usage of p_memsz and p_filesz in ELF.search() #2266

### ISSUE THREAD

**Issue by gordiig** [Gallopsled/pwntools#2269]
Check out for the original [issue](https://github.com/Gallopsled/pwntools/issues/2266)
Originally, I though this wasn't a bug, but now I am concerned that it is, indeed, a bug (and I can't change label for the original issue).
I am sorry for issue spamming, but I think bug-labeled issues are more likely to be taken for work sooner

**Comment by Arusekk** [comment]
Would you mind trying to submit a PR fixing the issue?

**Comment by gordiig** [comment]
> Would you mind trying to submit a PR fixing the issue?

Opened #2281
