### ISSUE TITLE
When working with the get_section function!

### ISSUE THREAD

**Issue by TotallyNotAHaxxer** [Gallopsled/pwntools#2278]
I was running a basic script for pwntools which is shown below and got some weird output and I am not sure if I was doing something wrong or not.

```python
from pwn import *


binary = ELF('./main')
section_name = '.text'
section_data = binary.get_section(section_name).data()
with open(f'{section_name}.dump', 'wb') as f:
    f.write(section_data)
log.info(f"'{section_name}' section dumped to '{section_name}.dump'")

```

## output

```
[*] '/home/totallynotahaxxer/Desktop/metasoft/py/main'
    Arch:     amd64-64-little
    RELRO:    Partial RELRO
    Stack:    No canary found
    NX:       NX enabled
    PIE:      PIE enabled
Traceback (most recent call last):
  File "/home/totallynotahaxxer/Desktop/metasoft/py/ex2.py", line 6, in <module>
    section_data = binary.get_section(section_name).data()
  File "/home/totallynotahaxxer/.local/lib/python3.9/site-packages/elftools/elf/elffile.py", line 140, in get_section
    section_header = self._get_section_header(n)
  File "/home/totallynotahaxxer/.local/lib/python3.9/site-packages/elftools/elf/elffile.py", line 614, in _get_section_header
    stream_pos = self._section_offset(n)
  File "/home/totallynotahaxxer/.local/lib/python3.9/site-packages/elftools/elf/elffile.py", line 590, in _section_offset
    return self['e_shoff'] + n * self['e_shentsize']
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

Am I missing something? Or is this an issue on the backend of the library?

**Comment by Arusekk** [comment]
get_section accepts an integer iirc, but you can check the docs and the source code to be sure.

Email z poniedziałku 25 września 2023 od Totally_Not_A_Haxxera:
> I was running a basic script for pwntools which is shown below and got some weird output and I am not sure if I was doing something wrong or not.
> 
> ```python
> from pwn import *
> 
> 
> binary = ELF('./main')
> section_name = '.text'
> section_data = binary.get_section(section_name).data()
> with open(f'{section_name}.dump', 'wb') as f:
>     f.write(section_data)
> log.info(f"'{section_name}' section dumped to '{section_name}.dump'")
> 
> ```
> 
> ## output
> 
> ```
> [*] '/home/totallynotahaxxer/Desktop/metasoft/py/main'
>     Arch:     amd64-64-little
>     RELRO:    Partial RELRO
>     Stack:    No canary found
>     NX:       NX enabled
>     PIE:      PIE enabled
> Traceback (most recent call last):
>   File "/home/totallynotahaxxer/Desktop/metasoft/py/ex2.py", line 6, in <module>
>     section_data = binary.get_section(section_name).data()
>   File "/home/totallynotahaxxer/.local/lib/python3.9/site-packages/elftools/elf/elffile.py", line 140, in get_section
>     section_header = self._get_section_header(n)
>   File "/home/totallynotahaxxer/.local/lib/python3.9/site-packages/elftools/elf/elffile.py", line 614, in _get_section_header
>     stream_pos = self._section_offset(n)
>   File "/home/totallynotahaxxer/.local/lib/python3.9/site-packages/elftools/elf/elffile.py", line 590, in _section_offset
>     return self['e_shoff'] + n * self['e_shentsize']
> TypeError: unsupported operand type(s) for +: 'int' and 'str'
> ```
> 
> Am I missing something? Or is this an issue on the backend of the library?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/Gallopsled/pwntools/issues/2278
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***

-- 
Wysłane z mojego urządzenia Sailfish
