### ISSUE TITLE
CET Shadow stack reporting in checksec.

### ISSUE THREAD

**Issue by nobodyisnobody** [Gallopsled/pwntools#2288]
It would be nice if `checksec` could display if the binary use shadow stack & IBT.

according to this kernel doc:  [Control-flow Enforcement Technology (CET) Shadow Stack](https://kernel.org/doc/html/next/arch/x86/shstk.html)

![](https://imgur.com/PBz7SAj.png)

that can be verified on a binary compiled with `gcc  -mshstk -fcf-protection=full` 
with readelf -n prog:
```sh
root@locahost:/host# readelf -n libc.so.6 

Displaying notes found in: .note.gnu.property
  Owner                Data size 	Description
  GNU                  0x00000040	NT_GNU_PROPERTY_TYPE_0
      Properties: x86 feature: IBT, SHSTK
	x86 ISA needed: x86-64-baseline
```

so checksec could report IBT & SHSTK flags presence in elf file.

**Comment by Arusekk** [comment]
I would love to see this too. Would you mind contributing a PR for that?
