### ISSUE TITLE
use checksec command hava a warning ,What should i do?

### ISSUE THREAD

**Issue by Sunlazys** [Gallopsled/pwntools#2303]
When I use the pwntools checksec command to check the protection of an executable, my checksec gives me a warning. What should I do?
![image](https://github.com/Gallopsled/pwntools/assets/105783737/298845c4-92f4-4fa2-8f9b-d7e30ec2990f)

In particular, the protection fails when I compile a source file with the following command.
![image](https://github.com/Gallopsled/pwntools/assets/105783737/aa3d7dfb-4b62-4e7b-88c1-ce7e7cbf1269)

**Comment by Sunlazys** [comment]
My pwntools‘s version is latest 4.11.0,but it look happen some question.

**Comment by peace-maker** [comment]
What `unicorn` version do you have installed? `pip show unicorn`
Try updating unicorn for you `pip install --upgrade unicorn`

**Comment by Sunlazys** [comment]
> What `unicorn` version do you have installed? `pip show unicorn` Try updating unicorn for you `pip install --upgrade unicorn`
My unicorn --version is v5.5.3, My pwntools three days ago use version v4.11.0, but i switch pwntools version to 4.8.0,the error hava been solve.

**Comment by Sunlazys** [comment]
My unicorn --version is v5.5.3, My pwntools three days ago use version v4.11.0, but i switch pwntools version to 4.8.0,the error hava been solve.

**Comment by peace-maker** [comment]
The latest unicorn version is 2.0.1.post1, so v5 must be from some other package
https://github.com/unicorn-engine/unicorn

I'm assuming you have an older version installed which doesn't have riscv support. We need to bump our minimum requirement it seems @Arusekk ?
