### ISSUE TITLE
Some binary files cause `context.quiet` to affect the global scope.

### ISSUE THREAD

**Issue by the-soloist** [Gallopsled/pwntools#2304]
The tested libc is download from https://github.com/niklasb/libc-database

## Update Pwntools First

using latest commit

<img width="690" alt="image" src="https://github.com/Gallopsled/pwntools/assets/46804083/7dce65f8-5ae0-446d-8e9c-3c574ea65d0a">

## Debug Output

DEBUG output:
<img width="1029" alt="image" src="https://github.com/Gallopsled/pwntools/assets/46804083/a1ff1be6-bf69-4a88-9b61-e1784e7cdecb">

But when not using DEBUG, use ELF() load the target libc causes `context.quiet` to affect the global scope.
<img width="1037" alt="image" src="https://github.com/Gallopsled/pwntools/assets/46804083/76f7153b-099e-4ad3-9455-8379b2608bcf">

## Test Code

testing on the following code

```py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from pwn import *
import ipdb

safe = "./libc6_2.13-20ubuntu5.2_i386.so"
target = "./libc6-x32_2.30-0ubuntu2_i386.so"

# load target libc
print("[test0] context.log_level: ", context.log_level)
ELF(target, checksec=False)
print("[test0] context.log_level: ", context.log_level)

# load safe libc in context.quiet
print("[test1] context.log_level: ", context.log_level)
with context.quiet:
    ELF(safe, checksec=False)
print("[test1] context.log_level: ", context.log_level)

# load target libc in context.quiet
print("[test2] context.log_level: ", context.log_level)
with context.quiet:
    ELF(target, checksec=False)
print("[test2] context.log_level: ", context.log_level)
```

## Example File

[attachment.zip](https://github.com/Gallopsled/pwntools/files/13455763/attachment.zip)

**Comment by peace-maker** [comment]
Thank you for the great test case!
