### ISSUE TITLE
unordlist returns a string, not a bytestring

### ISSUE THREAD

**Issue by TethysSvensson** [Gallopsled/pwntools#2320]

**Comment by peace-maker** [comment]
I never used that function but it is documented to return a string. Why do you want to change it?

**Comment by TethysSvensson** [comment]
I guess that might make sense. It was one of my go-to functions back in python2 where bytes/strings didn't really matter. I primarily use it as a variant of `flat` with a word size of 8.

**Comment by peace-maker** [comment]
I guess your usecase could simply be solved by using `bytes` instead of `unordlist`?

**Comment by TethysSvensson** [comment]
Yes, it can. Duh. I really need to get used to python as it looks today instead of being stuck in the past.

Thanks for helping me clarify.
