### ISSUE TITLE
Only download debug symbols if ELF does not contain them already

### ISSUE THREAD

**Issue by peace-maker** [Gallopsled/pwntools#2324]
Currently the `libcdb.unstrip_libc` function always looks for debug symbols online and tries to merge them into the libc. This is unnecessary and adding some `ELF.debuginfo` property to know if an ELF contains debug info would help.

**Comment by sswastik02** [comment]
Hi @peace-maker,
I would like to contribute to this project, if this issue is still relevant, I would like to work on it.

Thank you

**Comment by sswastik02** [comment]
Here are my proposed changes for the same,
1. Before seeking debug info online in the [unstrip_libc](https://github.com/Gallopsled/pwntools/blob/14c0d73f89d285717b3d976d5c2eba5965996ae9/pwnlib/libcdb.py#L295) function, include a check for the existence of debug info using [ELF.debuginfo](https://github.com/Gallopsled/pwntools/blob/14c0d73f89d285717b3d976d5c2eba5965996ae9/pwnlib/elf/elf.py#L2013).

Could you please provide clarification on how we could leverage the `ELF.stripped` functionality in this case?
Also, If you agree with the proposed changes, please assign the issue to me for implementation.

Thank you.

**Comment by peace-maker** [comment]
I don't think the .stripped property is useful here. Just checking for debuginfo seems enough.

**Comment by sswastik02** [comment]
Thank you @peace-maker !
Can you also clarify if addressing this requires the creation of additional tests?

**Comment by peace-maker** [comment]
Would be great, but I don't know how when this is fully transparent inside the unstrip function.

**Comment by sswastik02** [comment]
> Would be great, but I don't know how when this is fully transparent inside the unstrip function.

@peace-maker, Indeed, the feature operates transparently within the unstrip function, making it challenging to verify.
