### ISSUE TITLE
Get address of stack, heap, binary in memory of process

### ISSUE THREAD

**Issue by k4lizen** [Gallopsled/pwntools#2369]
The same way there is a way to get the address of shared libraries: [process.libs()](https://docs.pwntools.com/en/stable/tubes/processes.html#pwnlib.tubes.process.process.libs), which is currently implemented by inspecting `/proc/<pid>/maps` [as linked in the docs](https://github.com/Gallopsled/pwntools/blob/f046fdd93e/pwnlib/tubes/process.py#L826-L861), it should be possible to find the base address of the binary, stack and heap, even when ASLR is on.

This would be quite handy in some cases (like easily calculating offsets locally, which can then be used on remote processes).

**Comment by k4lizen** [comment]
Along with this, a `process.maps()` (which would returned a parsed `/proc/<pid>/maps`) could be implemented, and .libc/libs/stack/heap/whatever would just use that.
Also returning the size along with the address would be useful.

**Comment by k4lizen** [comment]
I would be willing to work on this PR if the feature is approved.

**Comment by peace-maker** [comment]
Sure, this sounds useful! Next to the hardcoded properties, having a shortcut to receive the base address of any mapping without having to filter the .libs() result manually would be great too.
