### ISSUE TITLE
`xor` function raises `TypeError: pop expected at least 1 argument, got 0`

### ISSUE THREAD

**Issue by marinelay** [Gallopsled/pwntools#2390]
https://github.com/Gallopsled/pwntools/blob/5981c7290dd5190733c1f2e9ccf08633869f8b31/pwnlib/util/fiddling.py#L306-L330

At line 330, it raises the type error `TypeError: pop expected at least 1 argument, got 0` because `pop` method cannot be used without arguments.

I believe that it should be fixed to report proper error message.

**Comment by Arusekk** [comment]
The code looks as if the intention was always to use [`popitem`](https://docs.python.org/dev/library/stdtypes.html#dict.popitem); anyway, when we finally drop py2 support, we could finally use keyword-only arguments here to get rid of all of this boilerplate.

Have you spotted more such uses throughout the code?

**Comment by marinelay** [comment]
I couldn't find any other occurrences for `dict.pop` like this issue
