### ISSUE TITLE
[docs bug] Many "links to the source" in the docs just link to the file (and not the line)

### ISSUE THREAD

**Issue by k4lizen** [Gallopsled/pwntools#2401]
Some examples:
https://docs.pwntools.com/en/dev/elf/elf.html#pwnlib.elf.elf.ELF.library
https://docs.pwntools.com/en/dev/elf/elf.html#pwnlib.elf.elf.ELF.linker
https://docs.pwntools.com/en/dev/elf/elf.html#pwnlib.elf.elf.ELF.maps
Click/hover the `[source]` button and see that they all link to: https://github.com/Gallopsled/pwntools/blob/fe560c9835/pwnlib/elf/elf.py
This is true for both dev as well as stable.

### Expected
For example, I would expect `.maps` to link to:
https://github.com/Gallopsled/pwntools/blob/fe560c9835/pwnlib/elf/elf.py#L714

**Comment by Arusekk** [comment]
Note: we should use inspect.getsource and friends instead of this complicated logic (it does the same things under the hood). I was not even aware that we generate the links manually. (cc: @peace-maker )

**Comment by Arusekk** [comment]
(The nice side effect is that functions decorated with functools.wraps will also be handled.)

**Comment by Arusekk** [comment]
Oh so we do it already. Maybe we could loosen the criterion a bit, to avoid an unnecessary whitelist.

**Comment by peace-maker** [comment]
I'm not sure I understand what you're suggesting but feel free to clean this up of course! 😅
