### ISSUE TITLE
Pwntools setup on Mac OS

### ISSUE THREAD

**Issue by evatiwari** [Gallopsled/pwntools#2408]
I am new to CTF and want to currently experiment with pwntools, but when I run `brew install pwntools` and try to execute a script importing pwntools like so: `from pwn import *`, I get the following error: `ModuleNotFoundError: No module named 'pwn'`.
I have also gone through the installation guides at https://docs.pwntools.com/ and followed the steps,  but to no avail. 
Can someone point me to the possible reason behind this?

**Comment by peace-maker** [comment]
I believe that homebrew recipe is created by someone else. Try using pip to install pwntools as documented in the install instructions. You might need to install the binutils through homebrew though.

**Comment by peace-maker** [comment]
Were you able to get it working? Were there any additional undocumented steps necessary?

**Comment by peace-maker** [comment]
Please reopen if this issue is persisting.
