### ISSUE TITLE
remote should not overwrite server_hostname

### ISSUE THREAD

**Issue by MrQubo** [Gallopsled/pwntools#2425]
```python
import ssl
from pwn import *

io = remote('172.22.0.2', 9090, ssl=True, ssl_args={ 'server_hostname': 'example.com' })
...
```

In the above code `server_hostname` will be overwritten with `'172.22.0.2'`.

**Comment by Arusekk** [comment]
You can change assignments to setdefault probably.

**Comment by MrQubo** [comment]
Should I create PR to `dev` or `stable`?

**Comment by MrQubo** [comment]
I think we should jest error if 'server_hostname' is set in ssl_args and `sni` is not False.
