### ISSUE TITLE
Undocumented behaviour of sni kwarg of remote()

### ISSUE THREAD

**Issue by MrQubo** [Gallopsled/pwntools#2426]
In `remote()` 'server_hostname' ssl arg can be set like this:
```python
remote('172.22.0.2', 9090, ssl=True, sni='example.com')
```
This behaviour of `sni` kwarg is undocumented. Currently only behaviour of passing a bool in documented.

**Comment by peace-maker** [comment]
Would you be willing to improve the documentation in a pull request please?

**Comment by MrQubo** [comment]
I made an issue cause I'm not sure how to document it. xd
I'll ask ppl for some input.
