### ISSUE TITLE
'int' object is not callable when `import pwn`

### ISSUE THREAD

**Issue by Dilrevx** [Gallopsled/pwntools#2456]
It seems `termcap.get` expects a param `default` in kwargs, while caller passed a param 8 in the form`termcap.get('colors', 8)`, breaking the import process.

Has commit 4879590  fixed this issue?

**Comment by peace-maker** [comment]
Yes, that commit fixes it. An easy workaround is to use the beta which includes the commit. This is only a problem on Windows which we don't 100% support yet and don't have CI to catch issues like this :( I'm planning to do a patch release, but wanted to wait for other issues to creep up first after the last stable release.

`pip install --upgrade --pre pwntools`

**Comment by Dilrevx** [comment]
Many thx
