### ISSUE TITLE
ELF.plt['unlink'] is not work for the provided binary

### ISSUE THREAD

**Issue by AWdong** [Gallopsled/pwntools#2473]
> English is not my native language; please excuse typing errors.

When I was going to go to use elf.plt[‘unlink’] to complete the challenge, it had a problem.

`[!] Could not populate PLT: Invalid argument (UC_ERR_ARG)`

I tried to fix this problem in goole but I didn't find a valid solution.Here's my full error message.

![屏幕截图 2024-09-28 143212](https://github.com/user-attachments/assets/0d615fd3-8bf1-416f-941c-d30fbb193b05)

### **My environment is ubuntu 22.04 on wsl2.** This below are some of my code snippets.
![屏幕截图 2024-09-28 145638](https://github.com/user-attachments/assets/8faf04e6-7266-4c59-8aef-f681d0d60f45)

**Comment by Arusekk** [comment]
What is your version of pwntools? (Try `pwn version` to see that.) What is your version of unicorn?
(Also please make sure that the binary really has an entry for `puts` in its PLT.)

Please check if #2466 solves your issue, thanks.

**Comment by AWdong** [comment]
My pwntools version is v4.13.0 and my unicorn version is 2.1.1.
 In the meantime, I'm pretty sure I have the plt of puts in my elf file.

This is the plt content I output using the **objdump** command
![屏幕截图 2024-09-28 160327](https://github.com/user-attachments/assets/8d5c5c10-45bb-42cd-8fe5-2ca2f3a59af4)

**Comment by peace-maker** [comment]
> Please check if #2466 solves your issue, thanks.

Yes, that's the error that fixes

**Comment by AWdong** [comment]
so the problems is due to unicorn version(2.1.1) too high.just now, I solved this problem by using the following command successfully. 
`pip install unicorn==2.0.1`

Thanks for the answer, to solve this problem I even reinstalled again the ubuntu system in wsl2.

**Comment by Arusekk** [comment]
(We should release 4.13.1 soon.)
