### ISSUE TITLE
An error occurred when I tried to use asm

### ISSUE THREAD

**Issue by ArmandRay** [Gallopsled/pwntools#2475]
When I use shellcraft, I get the following error message, and I don't know how to fix it.
![image](https://github.com/user-attachments/assets/5e573eb6-e331-4508-9154-810e1b709c64)

**Comment by peace-maker** [comment]
Try installing the build-essential package if you're on Debian/Ubuntu to install binutils and GCC. You're welcome to join our discord for quicker turnaround of such questions!

**Comment by ArmandRay** [comment]
> Try installing the build-essential package if you're on Debian/Ubuntu to install binutils and GCC. You're welcome to join our discord for quicker turnaround of such questions!

Thank you very much for your help, I have successfully solved the problem after installing GCC.
