### ISSUE TITLE
2 doctests in proc fail on debian

### ISSUE THREAD

**Issue by kristoff3r** [Gallopsled/pwntools#250]
We have some tests that assume pid 1 is init , and they fail on debian versions that use systemd. I can't really think of tests that are less platform-specific, any suggestions?

**Comment by IdolfHatler** [comment]
@zachriggle ping?

**Comment by zachriggle** [comment]
I did have those changes, then 31c3 happened and I nuked everything.  I no longer have this info, but I can recreate real quick.

**Comment by zachriggle** [comment]
@kristoff3r Can you verify the fix in #282?
