### ISSUE TITLE
fmtstr_payload write_size argument only works for multiple bytes

### ISSUE THREAD

**Issue by Legoclones** [Gallopsled/pwntools#2500]
When specifying the `write_size` argument for `fmtstr_payload()`, the different identifiers (`hhn`, `hn`, or `n`) are only present if there's multiple bytes/shorts/ints to write. For example, take these 3 format strings:

```python
>>> fmtstr_payload(1, {0x0: 0x1}, write_size='byte')
b'c%3$naaa\x00\x00\x00\x00'
>>> fmtstr_payload(1, {0x0: 0x1}, write_size='int')
b'c%3$naaa\x00\x00\x00\x00'
>>> fmtstr_payload(1, {0x0: 0x1}, write_size='short')
b'c%3$naaa\x00\x00\x00\x00'
```

Even though the `write_size` is specified for them all, they all have the same payload, which will overwrite all 8 bytes and not just the 1/2/4 that you want. 

It wasn't until I found https://github.com/Gallopsled/pwntools/issues/1698 that I realized `write_size` didn't actually control the number of bytes written *in total*, but only the size written in each pass ("byte by byte, short by short" as stated by the documentation). 

The issue recommends doing `p64(value)`, `p32(value)`, etc. for limiting the total number of bytes written, which was not intuitive to me. I think this was really just a misunderstanding of the pwntools documentation for the `writes` argument. I figured that `fmtstr_payload(1, {0x0: 0x00000001}, write_size='byte')` would only write a single byte, but instead `0x1` is converted into 8 bytes and all 8 bytes are written byte by byte.

I think the best fix would be to update the documentation for `writes` to specify that the dictionary `{address: value}` should be `{int: bytes}` and not `{int: int}`, and that the number of bytes in the value is the number of bytes written, and that if you just provide an `int` for the value, it will automatically be expanded to 8 bytes. I think including a statement similar to that above would help clarify for other people also how to limit the number of bytes written and that `write_size` **won't** do it for them.

**Comment by Arusekk** [comment]
Please open a PR with some initial suggestion. See #2499 for explanation.
