### ISSUE TITLE
Documentation for Ubuntu binutils installation

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#272]
There should be documentation on how to actually use the PPAs.

See https://github.com/Gallopsled/pwntools/issues/105#issuecomment-67780775 in #105

**Comment by zachriggle** [comment]
Is this satisfactory? I've made updates to the `pwntools-binutils` repo which contains instructions on how to perform the installation.

https://github.com/zachriggle/pwntools-binutils

If these instructions are okay (specifically some variant on [this script](https://github.com/zachriggle/pwntools-binutils/blob/master/ubuntu/install.sh)) I'll open a Pull Request to modify `docs/source/install.rst`.

**Comment by zachriggle** [comment]
Pinging @IdolfHatler @br0ns @RobertLarsen for input

**Comment by IdolfHatler** [comment]
:+1:
