### ISSUE TITLE
Documentation for building binutils from source

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#273]
There were a few one-liners posted in `#gallopsled` for building binutils.

These should be added to the documentation somewhere, preferably under `docs/` rather than in `README.md`.

See https://github.com/Gallopsled/pwntools/issues/105#issuecomment-67780775 for more information

**Comment by IdolfHatler** [comment]
Isn't this basically done?

http://pwntools.readthedocs.org/en/latest/install/binutils.html
