### ISSUE TITLE
Do cycle detection as part of the Travis testing

### ISSUE THREAD

**Issue by Idolf** [Gallopsled/pwntools#286]
I have a working (but quite ugly) script for this. I think we should run that as a part of the testing suite.

    #!/usr/bin/env python2.7
    # Run with sfood $PWNTOOLS_DIR -i | ./cycle_detect.py 
    
    import sys
    from pwnlib.util import safeeval
    from collections import defaultdict
    
    paths = defaultdict(lambda: defaultdict(lambda: None))
    nodes = set()
    
    for line in sys.stdin.read().strip().split('\n'):
        a, b = safeeval.const(line)
        if b == (None, None):
            continue
    
        paths[a][b] = []
        nodes.add(a)
        nodes.add(b)
    
    tested = set()
    found = False
    
    def recurse(path, cur):
        global found
    
        if cur in path:
            print 
    
    # floyd warshall
    for k in nodes:
        for i in nodes:
            for j in nodes:
                pathij = paths[i][j]
                pathik = paths[i][k]
                pathkj = paths[k][j]
    
                distij = len(pathij) if pathij != None else float('inf')
                distik = len(pathik) if pathik != None else float('inf')
                distkj = len(pathkj) if pathkj != None else float('inf')
    
                if distij > distik + distkj:
                    paths[i][j] = pathik + [k] + pathkj
    
    cycles = {}
    
    for k in nodes:
        if paths[k][k] != None:
            combined = [k] + paths[k][k] + [k]
            cycles[frozenset(combined)] = [b for a, b in combined]
    
    for cycle in cycles.values():
        print ' -> '.join(cycle)

**Comment by IdolfHatler** [comment]
Currently we have a single cycle, `context -> timeout -> context`. This should be removed.

**Comment by Idolf** [comment]
This is unlikely to be achievable without a large rewrite. Closing.

It was an interesting script to run though, and it helped my create #637. For future reference, this was the output the script resulted in:

```
pwnlib/asm.py -> pwnlib/context -> pwnlib/elf -> pwnlib/elf/elf.py -> pwnlib/asm.py
pwnlib/util/fiddling.py -> pwnlib/log.py -> pwnlib/util/fiddling.py
pwnlib/tubes/ssh.py -> pwnlib/elf -> pwnlib/elf/elf.py -> pwnlib/adb.py -> pwnlib/tubes -> pwnlib/tubes/ssh.py
pwnlib/tubes/sock.py -> pwnlib/log.py -> pwnlib/context -> pwnlib/elf -> pwnlib/elf/elf.py -> pwnlib/adb.py -> pwnlib/tubes -> pwnlib/tubes/sock.py
pwnlib/util/misc.py -> pwnlib/context -> pwnlib/elf -> pwnlib/elf/elf.py -> pwnlib/util/misc.py
pwnlib/tubes/serialtube.py -> pwnlib/context -> pwnlib/elf -> pwnlib/elf/elf.py -> pwnlib/adb.py -> pwnlib/tubes -> pwnlib/tubes/serialtube.py
pwnlib/tubes/remote.py -> pwnlib/log.py -> pwnlib/context -> pwnlib/elf -> pwnlib/elf/elf.py -> pwnlib/adb.py -> pwnlib/tubes -> pwnlib/tubes/remote.py
pwnlib/elf -> pwnlib/elf/elf.py -> pwnlib/tubes/process.py -> pwnlib/elf
pwnlib/context -> pwnlib/elf -> pwnlib/elf/elf.py -> pwnlib/context
pwnlib/tubes -> pwnlib/tubes/process.py -> pwnlib/elf/corefile.py -> pwnlib/elf/elf.py -> pwnlib/adb.py -> pwnlib/tubes
pwnlib/constants -> pwnlib/context -> pwnlib/elf -> pwnlib/elf/elf.py -> pwnlib/asm.py -> pwnlib/shellcraft -> pwnlib/constants
pwnlib/atexit.py -> pwnlib/context -> pwnlib/elf -> pwnlib/elf/elf.py -> pwnlib/adb.py -> pwnlib/atexit.py
pwnlib/adb.py -> pwnlib/context -> pwnlib/elf -> pwnlib/elf/elf.py -> pwnlib/adb.py
pwnlib/util/iters.py -> pwnlib/log.py -> pwnlib/util/fiddling.py -> pwnlib/util/packing.py -> pwnlib/util/iters.py
pwnlib/tubes/tube.py -> pwnlib/context -> pwnlib/elf -> pwnlib/elf/corefile.py -> pwnlib/tubes/tube.py
pwnlib/util/packing.py -> pwnlib/util/cyclic.py -> pwnlib/util/packing.py
pwnlib/tubes/process.py -> pwnlib/elf/corefile.py -> pwnlib/elf/elf.py -> pwnlib/tubes/process.py
pwnlib/shellcraft/registers.py -> pwnlib/context -> pwnlib/elf -> pwnlib/elf/elf.py -> pwnlib/asm.py -> pwnlib/shellcraft -> pwnlib/shellcraft/registers.py
pwnlib/shellcraft -> pwnlib/context -> pwnlib/elf -> pwnlib/elf/elf.py -> pwnlib/asm.py -> pwnlib/shellcraft
pwnlib/encoders/arm/alphanumeric/builder.py -> pwnlib/encoders/arm/alphanumeric/builder.py
pwnlib/tubes/listen.py -> pwnlib/context -> pwnlib/elf -> pwnlib/elf/elf.py -> pwnlib/adb.py -> pwnlib/tubes -> pwnlib/tubes/listen.py
pwnlib/qemu.py -> pwnlib/context -> pwnlib/elf -> pwnlib/elf/elf.py -> pwnlib/qemu.py
```
