### ISSUE TITLE
recvn does not work(timeout related)

### ISSUE THREAD

**Issue by kokjo** [Gallopsled/pwntools#303]
opening a remote and calling recvn returns None immediately without waiting to timeout or anything.
recv_raw from sock works...

**Comment by kokjo** [comment]
did git bisect:

5b45bd957bc69f1d1ab236cd3a8623c997a93e63 is the first bad commit
commit 5b45bd957bc69f1d1ab236cd3a8623c997a93e63
Author: Zach Riggle <zach@riggle.me>
Date:   Sat Dec 27 01:02:04 2014 -0500

    Fix regressions and get performance back up

:040000 040000 cd34b7cb7d42a7df8b97be00553fd224d0185ba2 b7ca15ddda85ce019487416379e8085b772fb9a0 M	docs
:040000 040000 224a8ac821bbe0dd23ee5bfd32ee9b58aa26b88c 269641612356cef1e069cb880c6b2babb291ac27 M	pwnlib

**Comment by kokjo** [comment]
Working:
from pwn import *
r = remote("pwnies.dk", 4372)
print `r.recvn(5)`

Not working:
from pwn import *
r = remote("pwnies.dk", 4372, timeout=500)
print `r.recvn(5)`

**Comment by zachriggle** [comment]
The issue was two things:

- recvn() was not passing the timeout to _fillbuffer (24942e01e7b230c8b45f542ede33a2544eb2d34d)
- recvn() was recently changed from polling self.timeout to self.countdown_active(), which was implemented wrong (c23d42e939340cf5a168a9db7e0b208723179dc3)
