### ISSUE TITLE
Old Binutils Doesn't Work

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#336]
We should find out what the minimum version of Binutils is that works with `shellcraft`, and warn the user if they have an outdated version when calling `pwlib.asm.asm`.

The main `binutils` repo on gnu.org does't have accurate timestamps.  We know per https://github.com/Gallopsled/pwntools/issues/263#issuecomment-68638125 that Binutils 2.15 (released in 2004) does not work.

We should find out the minimum version.  Ubuntu 12.04 LTS ships with 2.21 and is [now up to 2.22](https://launchpad.net/ubuntu/precise/amd64/binutils), so I think that's a reasonable version to support.

At a minimum, we must require 2.19, since that's when `-msyntax=intel` was added (Jan 2009).  There may be additional things that we use which require newer versions still.

**Comment by zachriggle** [comment]
@IdolfHatler: Can you verify that the changes implemented by #348 actually throws a warning for the old OpenBSD version of `binutils`?  Then we can close this.

**Comment by IdolfHatler** [comment]
It does!
