### ISSUE TITLE
pwnlib.tubes.sock never returns on .wait_for_close()

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#344]
There's no inspection as to the state of the socket, only a dictionary which is only updated on `.shutdown`, generally called on failure for `.recv_raw` or `.send_raw`, or directly via `.close`.

```
from pwn import *
l = listen()
r = remote('localhost', l.lport)
l.wait_for_connection().close()
r.wait_for_close()
```

**Comment by zachriggle** [comment]
I think we can get away with fixing this via select.poll() and POLLHUP.

**Comment by zachriggle** [comment]
Alternate solution seems to be `r.sock.recv(1, socket.MSG_PEEK | socket.MSG_DONTWAIT)`

**Comment by zachriggle** [comment]
Or we could do some weird registration between `sock` objects and a SIGPIPE handler.

**Comment by zachriggle** [comment]
Does anyone have a preference as to how this is fixed?  @IdolfHatler @br0ns?

`recv_raw` and `connected` do not not seem like a hot code paths, so it should not have a big performance hit to implement any of the above.

**Comment by br0ns** [comment]
I have no strong opinions regarding this.
