### ISSUE TITLE
Pwntools 2.2 release on PyPI

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#346]
As there are no more issues for Milestone 2.2, I have created a tag: https://github.com/Gallopsled/pwntools/releases/tag/2.2

I don't have access to the PyPI repo.  We should update it so that `pip install pwntools` pulls down 2.2.

**Comment by zachriggle** [comment]
Ignore all of the mentions above this, I had typed an issue number wrong.

**Comment by kristoff3r** [comment]
We moved the 2.2 tag to the current HEAD of master in order to finish up the release, so you might need to do git fetch --tags for your tags to be correct.

**Comment by zachriggle** [comment]
I think this is done now?
