### ISSUE TITLE
i386.linux.syscall does not accept a 7 argument

### ISSUE THREAD

**Issue by kokjo** [Gallopsled/pwntools#351]
as man syscall: ebp is the seventh arguemnt to syscalls on x86, however this is not implementet in i386.linux.syscall.

**Comment by IdolfHatler** [comment]
I do not think the manpage is correct. See e.g. http://syscalls.kernelgrok.com/

**Comment by IdolfHatler** [comment]
It was my clear understanding there is no way to do a call to mmap without spilling to the stack. Was I wrong?

**Comment by kristoff3r** [comment]
After looking around a bit it seems that kernelgrok is wrong (it simply fails for all syscall that uses 6 registers), and that Jonas is correct. See for example mmap_pgoff and futex, both of which are defined with syscall_define6.
