### ISSUE TITLE
`pwnlib.util.fiddling.hexdump()` is slow for some input

### ISSUE THREAD

**Issue by br0ns** [Gallopsled/pwntools#359]
Looks like it has to do with de Bruijn sequence detection.  Compare:
```
hexdump(randoms(1000))
```
and
```
hexdump('A' * 1000)
```

**Comment by zachriggle** [comment]
Do you think there's a way to do the detection more quickly?  I'm not opposed to ripping that out if it can't be done, you seem to be better at optimizing than I am.

**Comment by br0ns** [comment]
I'm not the expert on de Bruijn sequences... @IdolfHatler.

**Comment by IdolfHatler** [comment]
There is a TODO in cyclic.py for how to do faster lookup, but I have not read it.
