### ISSUE TITLE
log.indented not perfect

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#360]
When re-implementing the logging subsystem, I took a liberty to make `log.indented` work for the normal level of indentation.  This means its works for `[+]` and similar prefixes, but not for `[DEBUG]` or `[ERROR]`.

Do we care enough to fix this?  The fix would require determining the length of the prefix which belongs to the log level passed in.

**Comment by br0ns** [comment]
Maybe we should just remove `log.indented` entirely;  When we do e.g. `log.debug` and then `log.indented` we introduce a race condition.

**Comment by zachriggle** [comment]
The idea is that `log.indented` has a `level=` parameter which we should make use of, in determining the level of indentation.

**Comment by br0ns** [comment]
If we agree to keep `log.indented` we should get the formatting right, agreed.  But then we should also introduce a lock so related calls to e.g. `log.debug` and then `log.indented` can be grouped together.  I'm not sure it's worth the extra complexity and effort.
