### ISSUE TITLE
Indentation of multiline log messages not perfect

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#361]
Multiple-line log messages are wrapped on newlines, and indented with a constant number of characters.  This works for `[+]` and similar prefixes, but not for `[ERROR]`.

Do we care enough to fix this?

Related: #360

**Comment by br0ns** [comment]
This is quite easy to fix, and I think we should do it.  I have a big commit regarding logging coming up, so please hold your horses for a few hours.
