### ISSUE TITLE
Linuxbrew for Linux installation of binutils

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#370]
Looks like Linuxbrew is a thing?

https://github.com/Homebrew/linuxbrew

**Comment by IdolfHatler** [comment]
I really don't think that's a good idea.

**Comment by zachriggle** [comment]
It doesn't actually require us to make any changes, just add a link in the docs.  The `homebrew` recipes work verbatim for `linuxbrew`.

**Comment by zachriggle** [comment]
Closing this since anybody who already uses Homebrew should know this.
