### ISSUE TITLE
log.status symbol changed from '*' to 'x'

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#379]
Was this intentional?  Just checking to make sure it wasnt a typo.  It makes it seem like an error.

```
>>> from pwn import *
>>> w = log.waitfor('Demo')
[x] Demo
>>> w.status('Wow')
[x] Demo: Wow
>>> w.success('Woo!')
[+] Demo: Woo!
```

**Comment by br0ns** [comment]
Yes, it's intentional.  Sorry, I forgot to mention it in #365.  When you have many status updates I find it much easier to track them visually when they use a different symbol (also I changed the color to magenta).

**Comment by zachriggle** [comment]
So it's a reddish color, and it's an `x`, but not an error? :stuck_out_tongue:
