### ISSUE TITLE
A log handler should not be installed in lib-mode

### ISSUE THREAD

**Issue by br0ns** [Gallopsled/pwntools#392]
According to the [logging labrary's documenation](https://docs.python.org/2/howto/logging.html#configuring-logging-for-a-library) a library should not install any log handlers (except [`NullHandler`](https://docs.python.org/2/library/logging.handlers.html#logging.NullHandler)).

I suggest we move installation of our log handler and setting the `'pwnlib'` logger's level to `pwn.__init__`.  That way we should also be able to get rid of a [circular reference and hack](https://github.com/Gallopsled/pwntools/blob/master/pwnlib/term/__init__.py#L74-L76).

**Comment by IdolfHatler** [comment]
I agree this is a good idea. Should I do it in #391?

**Comment by br0ns** [comment]
Let's keep it separate, no?
