### ISSUE TITLE
pwnlib.util.fiddling.bits is broken for negative numbers

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#437]
```
>>> bits(-1)
<never returns>
```

**Comment by sam-b** [comment]
So this never returns due to the while loop being used in bits - what is the ideal response though? An empty array or the two's compliment representation of the value? (or something else?)

**Comment by zachriggle** [comment]
Probably the twos complement, to the nearest whole byte size.

**Comment by Idolf** [comment]
Seems to work now. Probably after #636.
