### ISSUE TITLE
pwnlib.util.safeeval.const can't handle True and False

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#443]
```
>>> safeeval.const('True')                                                                                                                 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-20c42fabd25b> in <module>()
----> 1 safeeval.const('True')

/home/user/pwntools/pwnlib/util/safeeval.pyc in const(expr)
     78     """
     79 
---> 80     c = test_expr(expr, _const_codes)
     81     return eval(c)
     82 

/home/user/pwntools/pwnlib/util/safeeval.pyc in test_expr(expr, allowed_codes)
     54     for code in codes:
     55         if code not in allowed_codes:
---> 56             raise ValueError("opcode %s not allowed" % dis.opname[code])
     57     return c
     58 

ValueError: opcode LOAD_NAME not allowed
```

**Comment by IdolfHatler** [comment]
Hmm, this seems like it is a weird quirk in python, because True and False are actually just variables defined in `__builtins__`.

`safeeval.expr` and `safeeval.values` are not working either.

I am not sure I see a good way of resolving it. Perhaps we could allow `LOAD_NAME`, as long as the only names are `True` and `False`?

**Comment by zachriggle** [comment]
Sounds good to me.  I worked around the issue for now, but I also thought
it was kind of strange and worth reporting.

**Comment by Idolf** [comment]
I think we should just close this, or possibly update the documentation. It is not clear to me that this is an important enough special-case for us to want to fix it.

**Comment by zachriggle** [comment]
Agreed.
