### ISSUE TITLE
Default documentation should be latest

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#449]
`pwntools.readthedocs.org` pulls up documentation for `2.2`, while the `latest` documentation is generally better.  Usually, this is just through enhancements to documentation vs. documentation of new features.

It seems that having `latest` be the default documentation isn't a horrible idea.

**Comment by zachriggle** [comment]
Related to #602?

**Comment by Idolf** [comment]
Assuming we do a release every 2 months, I disagree. In any case, the docs are so out of date that it should definitely be latest until we are closer to that goal.

For now, I will set latest as the default. I might change it back later.
