### ISSUE TITLE
ssh set_working_directory permissions

### ISSUE THREAD

**Issue by ebeip90** [Gallopsled/pwntools#454]
The directory created by `ssh.set_working_directory` is set `0700`.  This is problematic when a setuid binary needs to access a file that we create.

Recommendation: Set the permissions to `0711` or `0755` on the working directory.

**Comment by zachriggle** [comment]
This was fixed here:
https://github.com/binjitsu/binjitsu/commit/7e829db170015b30c7a8800bab8b3712665b31e3

**Comment by zachriggle** [comment]
This is fixed in the current `master` and can be closed.
