### ISSUE TITLE
`make doctest` does weird things with stderr

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#458]
This happens on `master`, and goes away if run as `PWNLIB_NOTERM=1 make doctest`.

![screenshot from 2015-01-31 20 33 33](https://cloud.githubusercontent.com/assets/111640/5991051/a8dc6f02-a9a1-11e4-9deb-581ee82cfa47.png)

**Comment by kristoff3r** [comment]
Calling `from pwn import *` is pretty fragile, as it tries to detect whether or not you are in a python interpreter, a terminal, or in the background. I'm pretty sure that it should work in principle, but that it is currently broken.

It should be possible to bisect and try to find the cause, but another question is if the unit tests should just do specific imports?

**Comment by Idolf** [comment]
I have no idea whether this is fixed, since I not able to run doctest locally.

@zachriggle, did you fix this in binjitsu?

**Comment by zachriggle** [comment]
The fix was to fix the NOTERM option.  There were some weird initialization-order things which were fixed with pwnlib/args.py.

Anyhow, tldr "PWNLIB_NOTERM=1 make" now functions properly.
