### ISSUE TITLE
Install Capstone dependency

### ISSUE THREAD

**Issue by aquynh** [Gallopsled/pwntools#462]
according to https://github.com/Gallopsled/pwntools/blob/master/docs/source/install/capstone.rst, Capstone 2.1.2 is required for Pwntools, but later in the same doc Brew would install the latest version 3.0.1 instead. this is inconsistent.

another issue is that the instruction is only for Ubuntu/Debian, but ignore other Linux distros.

since (recently released) v3.0.1, our PyPi package `capstone` at https://pypi.python.org/pypi/capstone/3.0.1 would build & install the core at the same time, so *no external dependency on the core is needed anymore*.

so i would propose a change here: on any environment (be it Linux or OSX, or even Windows), use `"pip install capstone"` is enough to install everything - including the core & Python module.

(on Windows you would need to setup MSVC compiler to compile the core anyway. to avoid that, you can use `capstone-windows` package at https://pypi.python.org/pypi/capstone-windows. see more info at http://capstone-engine.org/documentation.html, section `2.5`)

thanks.

**Comment by zachriggle** [comment]
Windows is entirely unsupported as a host OS for pwntools.

**Comment by aquynh** [comment]
ok. now you should update the docs at https://github.com/Gallopsled/pwntools/blob/master/docs/source/install/capstone.rst accordingly.

thanks.

**Comment by zachriggle** [comment]
It would be super awesome if `capstone` was distributed in the `wheel` format (i.e., pre-built binaries), at least for Ubuntu 12.04 and 14.04.

Building Capstone increases the runtime for Travis CI jobs by about 100% (1 minute 30 seconds).

**Comment by aquynh** [comment]
that is a good idea. feel free to fix that and send us PR on Github, i would merge.

thanks.

**Comment by zachriggle** [comment]
There's nothing to pull request, the maintainer just has to build it and upload.  The uploaded packages can be cryptographically signed, as well.

http://wheel.readthedocs.org/en/latest/
http://pythonwheels.com/

> when you'd normally run `python setup.py sdist upload`, 
> run instead `python setup.py sdist bdist_wheel upload`

However, it looks like I was misinformed about availability of platform-specific wheels for Linux.  It is not currently available.

Instead, a binary distribution / `.deb` file for `3.0.1` would be really, truly useful.

Does the `3.0.1.` installer check to see if a system version of `libcapstone` is already installed before building the native extension?

**Comment by zachriggle** [comment]
It looks like the `capstone` bindings for Python do some custom things for `sdist`, so normal usage of `bdist` is broken.

**Comment by aquynh** [comment]
yes, i would love to have Deb package for 3.0.1, too. actually Capstone has version 2.1.2 available in official repo of Debian & Ubuntu, but the maintainer is too busy to update that. at the moment, i am not sure when he is back to work on this. so if anybody here is good at Deb packaging that can help to update current Deb package to support 3.0.1, please ping me.

on PyPi package of 3.0.1, the core `libcapstone.so` is always built & installed just for Python module, but not system-wide, so there is no check to see if `libcapstone.so` is externally available.

see https://github.com/aquynh/capstone/blob/master/bindings/python/setup.py if you are interested.

**Comment by aquynh** [comment]
if you see anything that can be improved in the current `setup.py` of Capstone, feel free to send us a PR.

thanks.

**Comment by zachriggle** [comment]
> but the maintainer is too busy to update that

It could still be hosted on capstone-engine.org :)

**Comment by aquynh** [comment]
surely yes, but i mean he is not available to upgrade the Deb package, and i am not an expert on this area.

again, if somebody can help on Debian package, here is the link of 2.1.2 version: http://anonscm.debian.org/cgit/collab-maint/capstone.git/

**Comment by aquynh** [comment]
we now have all the packages for Capstone 3.0.2 for Ubuntu 14.04:

    http://capstone-engine.org/download/3.0.2/ubuntu-14.04/

hope this can be helpful for your project.

thanks.

**Comment by zachriggle** [comment]
This is fixed in master as of a long time ago, and can be closed.

**Comment by aquynh** [comment]
closed, thanks

**Comment by evandrix** [comment]
in that case, is there a suitable alternative to `pwntools` for Windows 7 then?
