### ISSUE TITLE
vma in asm function does not work.

### ISSUE THREAD

**Issue by kokjo** [Gallopsled/pwntools#489]
asm("jmp $", vma=0x41410000)

it seems like its trying to make a 0x41410000 bytes big file.

**Comment by Idolf** [comment]
I am not sure the gnu assembler actually supports this feature.

**Comment by kokjo** [comment]
So this means that if we still wants to support this feature we need to link it to that address, right?

**Comment by zachriggle** [comment]
Apparently this is a high-traffic issue (100+ unique visitors per month) so it's worth stating that this is now fixed.
