### ISSUE TITLE
`gdb.attach` does not remove temporary files

### ISSUE THREAD

**Issue by br0ns** [Gallopsled/pwntools#519]
My `/tmp` is filled with `pwnXXXXXX.gdb` -files.

**Comment by zachriggle** [comment]
I don't think there's a nice way to guarantee these get deleted, but I agree we should probably remove them.  My vote is to delete them only once the child process spawned by `run_in_new_terminal` exits.

Sometimes things are broken and I need to inspect those files.

There's not a way to do this from GDB (i.e. an on-gdb-exit handler), but we should just be able to install a SIGCHLD handler.

**Comment by br0ns** [comment]
Why is it a simple ``atexit.register(os.unlink, tmp.name)`` won't work again?
