### ISSUE TITLE
pwnlib.tube.recv() does not respect numb

### ISSUE THREAD

**Issue by pwntester** [Gallopsled/pwntools#526]
If more than 4096 are sent and recv() call specifies the correct number of bytes to read (eg: conn.recv(8000)), still only 4096 bytes are returned.

This is happening with socket connections.

Let me know if you need a testcase

Thanks

**Comment by zachriggle** [comment]
This is related to packet sizes and MTUs.  IMO this is working as intended.  Tube.recv should return immediately if any quantity of data is available, up to the amount specified.

I suggest you try the same thing with raw sockets (e.g. socket.create_connextion) and see if you get the same behavior.

**Comment by pwntester** [comment]
thanks for the prompt response. raw sockets return the 8000 bytes.
Is there a way to make recv() wait until timeout for the specified number of bytes?

**Comment by zachriggle** [comment]
Recvn does this

**Comment by pwntester** [comment]
you are right, sorry for wasting your time :(

**Comment by zachriggle** [comment]
No time wasted at all!  Please do file more bug reports in the future if you think something is broken.  We also have a mailing list if you like that better :smile: 

https://groups.google.com/forum/#!forum/pwntools-users

**Comment by pwntester** [comment]
will do, this library is AWESOME!
