### ISSUE TITLE
DynELF GNU Build ID

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#527]
We should add functionality to fetch Build IDs from the remote end in order to permit identification of LIBC while leaking less bytes and not needing to walk the entire ELF structure over the wire.

This, combined with a repository of standard libc.so files, indexed by build ID, should allow us to speed up the lookup process.

**Comment by kokjo** [comment]
DynELF is far superior to this approach.

**Comment by zachriggle** [comment]
This uses DynELF to retrieve the values.  The difference is that, in some cases, you can take a much shorter path than full remote resolution.  As an added bonus, once you do it that *one* time, you never need to do it again for that target because you have a local copy of libc.

It doesn't break or disable DynELF, and if there is no Build Id in the remote binary it requires exactly one DWORD lookup extra.  If there is a Build Id it adds four more DWORD lookups.

**Comment by Idolf** [comment]
I assume this was fixed by #528. Correct, @zachriggle ?
