### ISSUE TITLE
Python3 Support

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#529]
Is this something that we have any interest in implementing?  There are a lot of things that I want to use pwntools for, which have Python3 embedded in them (e.g. default GDB on Ubuntu).

**Comment by Idolf** [comment]
I tried earlier, and found it close to impossible to support python2 and python3 at the same time for our codebase.

**Comment by arthaud** [comment]
I wrote python3-pwntools: https://github.com/arthaud/python3-pwntools
We could probably merge it in a branch "python3".

**Comment by zachriggle** [comment]
Is it bi-compatible (i.e. works with Python2 *and* Python3 with the same codebase)?

**Comment by arthaud** [comment]
Unfortunately, no. It's python 3 only. I think it's too hard to support both with only one codebase.

**Comment by zachriggle** [comment]
You can check out the `futurized` branch of binjitsu for an example of what that'd start to look like.

https://github.com/binjitsu/binjitsu/tree/futurized

**Comment by zachriggle** [comment]
Bumping this.  This is something I can do with beer, since I'll need to be drunk.

I just need buy-in from @br0ns to help explain the TTY stuff.  I expect as long as we write the same Python3 **bytes** as we currently do Python2 **strings** then everything should work.

**Comment by lflare** [comment]
@zachriggle, is this issue considered abandoned?

**Comment by wangray** [comment]
@zachriggle name your price

**Comment by zachriggle** [comment]
A bottle of Pappy Van 20yr would do it 🥃

**Comment by wangray** [comment]
But seriously, what would this take as of right now? @fortenforge and I would like to help in our spare time.

**Comment by zachriggle** [comment]
In theory, this is a large-scale project that we have an entry for at in the [Projects](https://github.com/Gallopsled/pwntools/projects) tab.

The best starting point is probably the [`futurized` branch](https://github.com/zachriggle/pwntools/tree/futurized), which was based on version `2.2.0`.  Most things work on Python2 (I think the old tests passed, even).  Many of the things work on Python3, but the TTY module is one which very much does not work.

Ultimately, the work has a few real phases:

## Syntax Compatibility

- Getting the code to be parsed as valid Python3 without raising `SyntaxError`s
  - [`libfuturize`](http://python-future.org) is super useful for this
  - All references to `basestring`,  `unicode`, `long`, and `xrange` (etc.) need to be changed
- Getting the code to *also* be parsed as valid Python2 without raising `SyntaxError`s
  - This is pretty much a manual process.
- Now that it's Python2/Python3-compatible syntax, make the tests work again on Python2

## Python2 `bytes` vs. `unicode`

So we've got code that is at least valid Python3 syntax, and also is valid Python2 syntax and the tests all pass.

We should probably enable...

```
from __future__ import unicode_literals
from future.builtins import bytes
from future.builtins import str
from future.builtins import open # For where open() is used
```

...since this mirrors some Python3 behaviors.  Because Python2 is so flexible with `unicode` to `str` to `bytes` transformations, there might not be anything that breaks.

The easiest way to see shit blow up will be to do something like:

```py
data = ''.join(chr(i) for i in range(256)) # Get a buffer of all 256 bytes
io = remote('google.com', 80)
io.sendline(data)
```

This is because of stupid encoding bullshit.  Ultimately, the explodey bit is `b'\x80' + u'\n'`.

We would need to change e.g. the source of `sendline` to append `b'\n'`.

## Python3 `bytes` vs Python2 `bytes`

In Python3, the `bytes` type is a separate type from `str`.  On Python2 they are just aliases to eachother.

This means we can do easy byte manipulation on Python2 with `str`.  On Python3, you can't do this, since `str` is an encoded string.

As a first-pass, we have to identify all of the places we intend to manipulate `bytes` and prefix all of the initializers with `b`, e.g.:

```
buffer = b''
```

However, we don't really want to change the interface to anything in Pwntools, and we want everything to be as easy as possible.  A Python3 Pwntools user should still be able to do `tube.send("This is technically unicode text, not a byte string")` and the "right thing" happens.

There are a few ways to do this:

1. Always convert everything to a `bytearray` and use `bytearray` when manipulating binary data internal to pwntools.  When returning data to the user, give them a `bytes` object.
  - This is a larger rewrite, but might end up being more clean, since it removes any ambiguity
2. On Python3 only, convert all strings to `latin-1` encoding, then to a `bytes` object.  This has exactly 256 code-points which map identically to their binary representation.  
  - `bytes('foo\xff\x00', 'latin-1')` gives `b'foo\xff\x00'` on Python3.
    - This is exposed as `futurize.utils.tobytes`
  - On Python2, do nothing, since we already already have a `bytes` object (because `str is bytes`).  No performance impact for Py27.

I think that the best way to achieve either of these is with decorators on **EVERY** public API (i.e. anything which doesn't start with an underscore).

**Comment by anthraxx** [comment]
This would be awesome, python2 is slowly facing itsdefinitive EOL :boom:

**Comment by kupiakos** [comment]
I disagree that `tube.send` should work with a Python 3 `str`. If I'm writing bytes, I'll write bytes.

**Comment by summershrimp** [comment]
Ubuntu 18.04 no longer install python2 as default.

**Comment by zachriggle** [comment]
Thanks for the info, @summershrimp!

**Comment by zachriggle** [comment]
Given that Python2 is marked end-of-life on January 1, 2020, we may not need to keep backward compatibility, and just make Pwntools 3.x a legacy branch that supports Python2, and Pwntools 4.x as the Python3-only new release.

I *do* believe that we should be as accommodatingly compatible as possible to make script porting trivial (e.g. tubes *should* work with strings-as-bytes, via opportunistic `latin-1` encoding).  We can make this behavior default-off and toggle-able via e.g. `context.python2_compatibility=True`.

I do regret the unfortunate version numbering, that Pwntools 3 == Python2, and Python3 == Pwntools 4.

I do not currently have any cycles to spend on this effort, so it will have to be something that is community-supported.  We can probably do something like creating a `dev3` branch to support this.

Thoughts, @Idolf?

**Comment by SecT0uch** [comment]
That's a fantastic idea! Looking forward to it.

**Comment by summershrimp** [comment]
Python3 == Pwntools 5 should avoid the mess of version numbering LOL.

**Comment by zachriggle** [comment]
Looks like there's some stuff going on in @Mic92's fork: 2b493c64ef758d0f58054c1e9e34055e373ab502

**Comment by Mic92** [comment]
Take that with a grain of salt. I just ported enough code to python3 to get corefile/elf running as I need this for my research. I will not do a complete port though.

**Comment by Mic92** [comment]
I cleaned the code I did last night, you might want to still rethink some decisions as I sometimes took shortcuts and always used bytes where strings might make more sense just to have rewrite less: https://github.com/Mic92/pwntools/commit/478947aefc7b8430f3517e0bfd543294c6bcd491

**Comment by Arusekk** [comment]
I've also done an experimental python3 support to pwntools on https://github.com/Arusekk/pwntools/tree/full-3-compat , it mostly works (even the CLI!), and passes the tests (with minor differences, like differences in random seeds or printing `b'blah'` instead of `'blah'` and dict reorderings).

The reason why I haven't submitted a pull request is that I still have to clean the commits up a bit.

**Comment by Mic92** [comment]
Great, too bad I did know this earlier. I guess I will switch to your version.

**Comment by Mic92** [comment]
Great, too bad I did know this earlier. I guess I will switch to your version.

**Comment by trupples** [comment]
Considering the python2 end of life date is getting closer and closer, is there any progress on an official python3 branch/port ?

**Comment by Mic92** [comment]
~~I toughed the idea was to get pwned away by open python CVEs, while using pwntools~~ Just kidding.

**Comment by EvanCarroll** [comment]
As a side note, Python3-Pwntools hasn't been maintained since July 27, 2018. So the status of Python2 and Python3 with Pwntools can use some clarification.

https://github.com/arthaud/python3-pwntools/issues/9#issuecomment-408456474

**Comment by kupiakos** [comment]
FWIW, python3-pwntools has a [utility function](https://github.com/arthaud/python3-pwntools/blob/7519197918a0ca4155b184f3dd12b9686a3d2f55/pwnlib/util/misc.py) to encode an input unicode str as UTF-8 in many use-cases, whose usage could be used as a guide to figure out where problematic functions are.

If work is actually begun on this, is it "official" that the branch can drop Python 2 support? That would make the port 10x easier.

**Comment by arthaud** [comment]
I would also like to know the status of the python 3 support.
Are there people from Gallopsled working on this?

I could possibly work on this since I have a lot of spare time right now (thanks the government shutdown..).
Are you interested in supporting python 3 only, or do you want to support both python 2 and 3?

What would be the best way for an external contributor to help you with this? I don't want to create another python3-pwntools that never gets merged.

**Comment by Mic92** [comment]
You can probably help out @Arusekk. As far as I understood there are no plans to support python2 after that.

**Comment by zachriggle** [comment]
> Are there people from Gallopsled working on this?

No, it's very much a skeleton crew.  I'm the only maintainer at the moment, and barely have enough time to manage pull requests and cut releases.

> Are you interested in supporting python 3 only, or do you want to support both python 2 and 3?

Ideally we could support both with `six` / `futurize` / etc.  I have a `futurized` branch on my GitHub fork, but it's several years old.  Most of the tests passed: https://github.com/zachriggle/pwntools/tree/futurized

There are a few pull requests moving Pwntools to be *more compatible* with Python3 that might help in the process either way.

I'm not opposed to supporting Python3 exclusively, but **all tests** must pass before we can cut a release.

> What would be the best way for an external contributor to help you with this? I don't want to create another python3-pwntools that never gets merged.

You can contribute easiest by working on the `dev` branch to enable `python3` to...

1. Just be valid Python3 syntax
2. Not raise an exception when doing `from pwn import *` 
3. Basic tubes (process, remote, listen) 
4. ELF and Corefile modules work
4. Shellcraft modules can be assembled

There's always more, but those are a bunch of starting points.  Bullets 1 and 2 are obviously pre-requisites for anything else.

Pull request #1224 from @Arusekk has made some good progress

**Comment by disconnect3d** [comment]
Just to make sure we know what is still needed here - I looked through some issues and it seems that those issues/PRs are related:
* https://github.com/Gallopsled/pwntools/pull/1282
* https://github.com/Gallopsled/pwntools/issues/1253
* https://github.com/Gallopsled/pwntools/issues/1276

**Comment by ZetaTwo** [comment]
I would very much like to contribute to the Python 3 port efforts but I'm very unsure where to start as I haven't touched the pwntools codebase and don't know what others are already working on. Could anyone maybe point me in the right direction?

**Comment by Arusekk** [comment]
A good starting point is the current dev3 branch; the project has been idle lately due to developers' lack of time, so any help is welcome :)

**Comment by ZetaTwo** [comment]
I've been running the dev3 branch for the last ~8 months and I think the two biggest issues I've found are:

* decoding/encoding when working with the tubes module
* tubes.interactive() crashes if there are non-printable characters in the buffer

I'm thinking about doing the following:

* Add an "encoding" to context
* Add an optional named argument "encoding" to all sending tubes method
* In the tubes module, if the argument is of type "str" use the encoding argument (or context encoding) to encode the argument.

Does this sound like an ok approach?

**Comment by ZetaTwo** [comment]
I have opened an initial attempt in this PR: https://github.com/Gallopsled/pwntools/pull/1349

**Comment by zachriggle** [comment]
Can we close this out, or link to the beta?

**Comment by Arusekk** [comment]
Sure. To me, the new beta is ready to be deployed as stable in a few weeks' time.

**Comment by kpcyrd** [comment]
Any updates? We have everything setup to ship pwntools in arch as soon as we have a stable python3 release.

**Comment by TethysSvensson** [comment]
@kpcyrd We used to let beta releases sit for at 6 weeks before shipping as stable, but ultimately that decision is up the current maintainers.

**Comment by Arusekk** [comment]
Closing this as Python 3 is now supported officially, and use individual issues for this.

**Comment by blshkv** [comment]
@Arusekk setup.py does not reflect that support. Could you update it please?

https://github.com/Gallopsled/pwntools/blob/dev/setup.py#L1
https://github.com/Gallopsled/pwntools/blob/dev/setup.py#L119
