### ISSUE TITLE
Override context.arch when it makes sense?

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#536]
There are a few circumstances where `context.arch` does not make sense, and we should not respect it.  The ones that come to mind are:

- ROP generation
- Debugging

In particular, if `ROP(...)` is given some 32-bit `arm` binaries, but `context.arch` is `amd64`, what is the ideal behavior?  Realistically the user just needs to do `context.arch = 'arm'` or even `context.local(...)`, but sometimes that's not apparent.

The same thing occurs for debugging binaries.  For example `gdb.debug('./eliza-v2-arm')` -- it's an ARM binary, and even if the context is set to something else, GDB won't do anything useful without the correct context information.

In these circumstances, would it be better to do the "convenient thing", or should we continue to do  "strictly what the user says, even if it's not what they want"?

**Comment by eQu1NoX** [comment]
If context.arch is "amd64" and the user tries to do ROP(...) of an ARM binary, wouldn't raising an exception and informing the user of context.local be more useful(and less complicated)?

**Comment by zachriggle** [comment]
One `log.warn_once` is probably good for informing the user of the problem, but it's no less complicated since we have to perform all the same detection.

**Comment by zachriggle** [comment]
This effectively becomes a user error.  It's the user's responsibility to set things to the correct values.
