### ISSUE TITLE
license information incorrect in user-agent data

### ISSUE THREAD

**Issue by psifertex** [Gallopsled/pwntools#547]
[LICENSE.txt](pwntools/blob/master/pwnlib/data/useragents/LICENSE.txt) mentions that the last list (http://techpatterns.com/downloads/firefox/useragentswitcher.xml) is covered by GPL because of the package it is referenced from, but if you read the actual file, at the bottom it says it is explicitly `License: BSD 2 Clause`.

**Comment by br0ns** [comment]
I have no idea what "BSD 2 Clause" is... is this better? https://github.com/Gallopsled/pwntools/pull/548

**Comment by psifertex** [comment]
BSD-2-Clause is just a simplified form of the BSD license (which freebsd, openbsd, openssh, etc, are licensed under): http://opensource.org/licenses/BSD-2-Clause

As to the change itself, I wouldn't even mention the GPL at all if it were me since it's not relevant -- the one file included is BSD licensed, that's all that's important from the licensing perspective of pwntools. That said, it's certainly not wrong the way it's described now.

Thanks for the quick fix!
