### ISSUE TITLE
easy_install sandbox violation with release 2.2.0

### ISSUE THREAD

**Issue by triggerk** [Gallopsled/pwntools#549]
release 2.1.3 installs fine though, thanks!

---

ubuntu 14.04
sudo python setup.py install

ar: creating ./libcapstone.a                                                                           
  GEN     capstone.pc                                                                                  
error: Setup script exited with error: SandboxViolation: mkdir('/usr/lib/python2.7/dist-packages/capstone', 511) {}                                                                                           
                                                                                                       
The package setup script has attempted to modify files on your system                                  
that are not within the EasyInstall build area, and has been aborted.                                  
                                                                                                       
This package cannot be safely installed by EasyInstall, and may not                                    
support alternate installation locations even if you run its setup                                     
script by hand.  Please inform the package's author and the EasyInstall                                
maintainers to find out if a fix or workaround is available.

**Comment by zachriggle** [comment]
This is not a pwntools problem.  File a bug with capstone: https://github.com/aquynh/capstone/issues

**Comment by RobertLarsen** [comment]
If this is still a problem try `pip2 install -r requirements.txt`
That will install the requirements using pip2 instead of EasyInstall and that seems to work.
After that you can install pwntools with `python setup.py install`

**Comment by zachriggle** [comment]
python setup.py install should install all of the requirements.  In fact,
requirements.txt only references setup.py.

**Comment by RobertLarsen** [comment]
It does, however it uses easyinstall which fails when installing capstone.
If you use pip/pip2 then the dependencies are installed and pwntools can be installed afterwards.

**Comment by zachriggle** [comment]
Closing as this isn't a pwntools problem.
