### ISSUE TITLE
using tubes to connect to a tty

### ISSUE THREAD

**Issue by antoniobianchi333** [Gallopsled/pwntools#575]
It would be useful to have a specific "tubes" to connect to a remote tty (or alternative a pair of pipes connected to a process).

This can be useful , for instance, if you want to connected a script using pwntools to a process debugged by gdb.
In fact, you can debug a process in gdb and redirect its input/output to a tty (command: tty <tty filepath>).
In this way you can have gdb debug output in one shell, the debugged process connected to a different tty, and the script using pwntools interacting with the debugged process using the "ad-hoc" tty.

If you are interested in this feature, I can work on implementing it.

**Comment by zachriggle** [comment]
Or you can just use the `gdb` module?

```py
from pwn import *

io = gdb.debug('/bin/bash', '''
break main
continue
''')
```

```py
from pwn import *

io = process('/bin/bash')
gdb.attach(io, '''
break memcpy
continue
''')
```
