### ISSUE TITLE
Process.close() doesn't close file descriptors

### ISSUE THREAD

**Issue by gsingh93** [Gallopsled/pwntools#582]
Running the following program shows the number of used file descriptors going up, even though the process has been killed.

```
#!/usr/bin/env python2

from pwn import *

for i in range(1000):
    p = process('/bin/ls')
    p.close()
    print len(os.listdir('/proc/self/fd'))
```

Using `Process.shutdown()` with both 'send' and 'recv' fixes this problem, but `close` should also take care of this. This problem doesn't occur with [binjitsu](https://github.com/binjitsu/binjitsu/).

**Comment by br0ns** [comment]
I believe this was fixed by #576.  In any case I can't reproduce:

```
$ cat foo.py 
from pwn import *
context.log_level = 'ERROR'
while True:
    p = process('/bin/ls')
    p.close()
    print os.listdir('/proc/self/fd')
$ python foo.py 
['0', '1', '2', '3', '7', '12']
['0', '1', '2', '3', '7', '12']
['0', '1', '2', '3', '7', '12']
['0', '1', '2', '3', '7', '12']
['0', '1', '2', '3', '7', '12']
['0', '1', '2', '3', '7', '12']
['0', '1', '2', '3', '7', '12']
['0', '1', '2', '3', '7', '12']
...
```

**Comment by br0ns** [comment]
@gsingh93, can you confirm that this issue has been fixed?

**Comment by gsingh93** [comment]
Yea, I've been using an outdated version of pwntools, this is fixed. Thanks.
