### ISSUE TITLE
`proc.pid_by_inode()` was removed

### ISSUE THREAD

**Issue by br0ns** [Gallopsled/pwntools#591]
The function is used by `gdb.attach()` when attaching to a GDB server.  It seems to have been removed in commit c55273c52aea17b192d9d54fc79ae530a8fcea58 ([diff](https://github.com/Gallopsled/pwntools/commit/c55273c52aea17b192d9d54fc79ae530a8fcea58#diff-984cc92cf4d6ba16297ec45ccdc82cecL66)).

**Comment by zachriggle** [comment]
Yeah, need to put this back in.  I'll get on this soon.

**Comment by Idolf** [comment]
Is this fixed by, @zachriggle ?

**Comment by zachriggle** [comment]
Added a PR to fix this
