### ISSUE TITLE
Docs links are broken

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#602]
For whatever reason, https://docs.pwntools.com/ doesn't work anymore.
The normal link works: https://pwntools.readthedocs.org/en/latest/

Nothing has changed on my end.   I expect this is due to a change in how ReadTheDocs handles domain forwarding, or the settings on RTD for pwntools (which I do not control).

<img width="1057" alt="screen shot 2016-03-16 at 10 15 28 am" src="https://cloud.githubusercontent.com/assets/111640/13815211/0f58ffba-eb60-11e5-8913-9c8831bbdb19.png">

I just set up docs.binjit.su to use the same settings as docs.pwntools.com on CloudFlare, and it appears to work correctly.

**Comment by zachriggle** [comment]
FWIW https://docs.binjit.su/ works

**Comment by zachriggle** [comment]
Looks like #449 is not related, because this also doesn't work: https://docs.pwntools.com/en/2.2/

**Comment by zachriggle** [comment]
It looks like the docs are still down.  Ping?

**Comment by Idolf** [comment]
Fixed.
