### ISSUE TITLE
Docs Builds Are Broken

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#603]
Looks like the pwntools docs have been broken for like 7 months because of the manner in which Capstone is installed.

https://readthedocs.org/projects/pwntools/builds/

Since it works for Binjitsu, I assume this is something that can be fixed by changing the `requirements.txt`.  Because of some changes to the way RTD performs the setup, we can no longer perform command injection to get multiple requirements files, so [Binjitsu copied all normal requirements into docs/requirements.txt](https://github.com/binjitsu/binjitsu/blob/master/docs/requirements.txt).

I've attached a PDF printout of the current settings for Binjitsu's RTD settings, in case it helps:
[Edit Advanced Project Settings _ Read the Docs.pdf](https://github.com/Gallopsled/pwntools/files/176229/Edit.Advanced.Project.Settings._.Read.the.Docs.pdf)

**Comment by zachriggle** [comment]
It looks like the docs are still down.  Ping?

**Comment by Idolf** [comment]
This is indeed fixed after #636.
