### ISSUE TITLE
Some little bugs find when read source of pwntools

### ISSUE THREAD

**Issue by zh-explorer** [Gallopsled/pwntools#609]
First place is in pwnlib/tubes/tube.py at line 706
It use dumplog and log together. It make me confused.But whatever,it seem work well.So I don't know it a just a bug or have other mean

Second place is in pwnlib/log.py at line 330
```
    def warn_once(self, *args, **kwargs):
        """Alias for :meth:`warning_once`."""
        return self.warning(*args, **kwargs)
```
jsut a little bug

**Comment by zachriggle** [comment]
Fixed in #610
