### ISSUE TITLE
pip install without python-dev fails with unfriendly errors

### ISSUE THREAD

**Issue by mkow** [Gallopsled/pwntools#611]
"pip install pwntools" on Ubuntu x64 without python-dev installed throws an unfriendly error:
```
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_VERSION=410 -I/usr/include/python2.7 -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_linux.o
psutil/_psutil_linux.c:12:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
It would be better to check if python-dev is installed and print a message before compilation, or at least mention it on the main github page (https://github.com/Gallopsled/pwntools, "Installation" section).

Thanks in advance!

**Comment by zachriggle** [comment]
Right where you suggest we put the additional installation information, there is a link to additional installation information.

<img width="926" alt="screen shot 2016-03-29 at 8 38 13 pm" src="https://cloud.githubusercontent.com/assets/111640/14128379/60fb9006-f5ee-11e5-8a8c-04ac91417206.png">

**Comment by zachriggle** [comment]
Separately, that compilation error comes from the `psutil` project.  While this is a dependency of `pwntools`, any checks would be performed by that project.

**Comment by mkow** [comment]
"complete installation instructions here" link is placed right after a sentence about non-Python dependencies, so I thought it's not related to the compilation error about missing Python.h ;)

IMO it would be nice to ping psutil devs about the issue, it gives bad impression on newcomers (that it doesn't install out-of-the-box).

**Comment by zachriggle** [comment]
`python-dev` is a non-Python dependency.

**Comment by zachriggle** [comment]
I recommend adding your opinion to this discussion here:
http://stackoverflow.com/a/21341666
