### ISSUE TITLE
cyclic_find() int not working

### ISSUE THREAD

**Issue by push0ebp** [Gallopsled/pwntools#623]
cyclic_find(0x61616162)
Traceback (most recent call last):
File "", line 1, in
File "pwnlib/util/cyclic.py", line 101, in cyclic_find
if any(c not in alphabet for c in subseq):
TypeError: 'int' object is not iterable

**Comment by zachriggle** [comment]
Does this repro on Binjitsu?

**Comment by zachriggle** [comment]
This works fine in [Binjitsu](http://binjit.su).

```
>>> cyclic_find(0x61616162)
4
```

**Comment by bert88sta** [comment]
I think this only works if it isn't in the pattern

**Comment by Idolf** [comment]
This was fixed by #636. Closing.
