### ISSUE TITLE
serialtube.py not using arguments when creating serial.Serial object.

### ISSUE THREAD

**Issue by Vigeant** [Gallopsled/pwntools#624]
The serialtube.py is currently ignoring most of the arguments when creating the serial.Serial object. The fix is simple and should simply map the arguments to the serial.Serial object.

**Comment by zachriggle** [comment]
Fixed in binjitsu@21fc7759e0b7229edac774b2b71417d450c777c4

**Comment by Idolf** [comment]
Which means that it was fixed by #636.
