### ISSUE TITLE
tubes.remote quite mode

### ISSUE THREAD

**Issue by push0ebp** [Gallopsled/pwntools#627]
[x] Opening connection to u on port 1111
[x] Opening connection to u on port 1111: Trying x.x.x.x 
[+] Opening connection to u on port 1111: Done

it is verbose.
I want to remove this messages
please add quite mode. 

class pwnlib.tubes.remote.remote():

r = remote('x.x.x.x',1111, quite=True) (default False)
r = remote('x.x.x.x',1111, verbose=False) (default True)

**Comment by zachriggle** [comment]
See the documentation for [`context.log_level`](http://docs.binjit.su/context.html#pwnlib.context.ContextType.log_level).

[Binjitsu](https://github.com/binjitsu/binjitsu/), a fork of pwntools, has more fine-grained support, including functionality similar to your request (i.e. `remote(..., level='debug')` or `remote(..., level='error'`)

**Comment by push0ebp** [comment]
thank you so much
2016. 5. 22. 오후 5:49에 "Zach Riggle" <notifications@github.com>님이 작성:
