### ISSUE TITLE
can pwntools add the function of ignoring signal when debugging locally?

### ISSUE THREAD

**Issue by shenyuan123** [Gallopsled/pwntools#634]
Sometimes, the SIGALRM signal is annoying. I know that process of pwntools is based on subprocess, and subprocess has the function of ignoring signal by passing "preexec_fn" argument, So I wonder if it's possible to achieve it.

**Comment by zachriggle** [comment]
Yep, just pas in a preexec_fn that does what you want. We honor preexec_fn.

**Comment by shenyuan123** [comment]
> Yep, just pas in a preexec_fn that does what you want. We honor preexec_fn.
I see. I install pwntools by `pip install pwntools `, and the pwntools in pypi is updated on 2015.1, so I missed the feature.

**Comment by zachriggle** [comment]
It may be binjitsu-specific (http://binjit.su)

**Comment by zachriggle** [comment]
In any case, if you're *debugging* locally, you can just tell GDB to ignore it.

```
handle SIGALRM nostop print nopass
```

**Comment by zachriggle** [comment]
Closing since the `preexec_fn` recommendation is a correct solution, and is now available in master.
