### ISSUE TITLE
Update our twitter handle

### ISSUE THREAD

**Issue by Idolf** [Gallopsled/pwntools#639]
Our twitter handle in README.md does not exist. We should either remove it or change it to something that does (Gallopsled?)

**Comment by Idolf** [comment]
Fixed in #638.

**Comment by zachriggle** [comment]
I own the "pwntools" Twitter account. This was a mistake from replacing
binjitsu with pwntools globally.

**Comment by Idolf** [comment]
Make sense. I will update #638 then.

**Comment by zachriggle** [comment]
This was merged already?

**Comment by Idolf** [comment]
Yes, this was fixed in #638.
