### ISSUE TITLE
Next Release Meta-Bug

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#658]
What's left to do in order to cut a new release?  Can we enumerate those in bugs and add them here?

@Idolf @kokjo @RobertLarsen?

**Comment by zachriggle** [comment]
Ping! @Idolf @kokjo @RobertLarsen

**Comment by Idolf** [comment]
I will add a few issues I think we need to fix here.

**Comment by Idolf** [comment]
Nice to have:

- [ ] #406 / #642 
- [ ] #455 
- [ ] #591 
- [ ] #626 
- A bunch of simple PRs by @zachriggle 

Need to have:
- [ ] #518 / #652 
- [ ] #641 

(Not yet done)

**Comment by zachriggle** [comment]
#652 should be merge-able

**Comment by Idolf** [comment]
I would rather handle this with milestones.
