### ISSUE TITLE
Command-Line Tool Refactor

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#660]
We have a lot of command-line tools that nobody knows about unless they go and read the documentation.  Additionally, when using the command-line tools, it's not apparent where they come from (e.g. "What is that `asm` command you used?")

I suggeset refactoring all of the tools to have a single entry point, a la `git`.  Instead of `asm foo` we will have e.g. `pwn asm foo`.

This also resolves some other issues with naming conflicts with e.g. Arch linux in #573.

In order to maintain backward compatibility, we will also provide a command-line option to `setup.py` to install the fully-named tools, which can be passed to `pip install` via `--install-option`.

I also recommend that in addition to the short `pwn`, that we also have an entry point with the full name `pwntools`.

Finally, to go with #659, I recommend a new entry point so that `pwn update` and `pwntools update` just magically works, and grabs the latest released-or-tagged version directly from Pip or Github, and does The Right Thing.

**Comment by anthraxx** [comment]
sounds awesome... just a tiny side note aka feature request:

It would be gorgeous if the ```update``` command of ```pwn``` could be bound to a simple bool somewhere in the python module, so a distro package maintainer could simply ```sed``` it to False to deactivate it. This would be useful if packaged through the distro rather the directly via ```pip``` or a git checkout :smile_cat:
