### ISSUE TITLE
demo.pwntools.com update

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#687]
Each release, [demo.pwntools.com](http://demo.pwntools.com) should be updated.

**Comment by zachriggle** [comment]
I've manually updated this for 3.0.1, but we should figure some way to automate it in the future.

**Comment by TethysSvensson** [comment]
Sounds like a good idea. I have no idea where demo.pwntools.com is even hosted.

**Comment by zachriggle** [comment]
Actually, this is something that we can probably automate as a post-deploy step with Travis.  We can have every commit / update to `stable` auto-kick this.

**Comment by zachriggle** [comment]
Using `$ travis encrypt` we can make this work.

**Comment by zachriggle** [comment]
This was fixed with 041c665185374727ec5d8f7ccb9dd0418aa05639 hopefully
