### ISSUE TITLE
Missing support for memfd_create syscall

### ISSUE THREAD

**Issue by HarryR** [Gallopsled/pwntools#691]
I'd quite like to use `memfd_create` with pwntools because it would let me implement things like: https://github.com/HarryR/netelf/blob/master/client_memfd.c - executing an ELF from memory via `/proc/self/fd/%d` without using `/dev/shm`.

I don't have access to all the platforms, nor do I know if the syscalls are auto-generated or manually setup, or if there's an easier way for adding extra syscalls across supported Linux architectures.

**Comment by zachriggle** [comment]
The syscall templates were generated from 14.04 man pages.  `memfd_create` is too recent to be on that kernel.

You can still use the `syscall` wrapper, which works identically.

```
>>> print shellcraft.syscall(1,2,3,4)
    /* call syscall(1, 2, 3, 4) */
    push 1
    pop eax
    push 2
    pop ebx
    push 3
    pop ecx
    push 4
    pop edx
    int 0x80
```

**Comment by zachriggle** [comment]
It also looks like this syscall is missing from the libc headers we parse for syscall constants.  This is effectively blocked on #672 and #685

**Comment by HarryR** [comment]
Awesome, thankyou :D
