### ISSUE TITLE
Regression in CLI tool `phd`

### ISSUE THREAD

**Issue by br0ns** [Gallopsled/pwntools#710]
It seems commit c9e5a01605ef3e60e4f8692fee185034219baeeb has been lost at some point.  It looks like it can just be merged as-is.

**Comment by zachriggle** [comment]
I added some comments directly to that commit: https://github.com/Gallopsled/pwntools/commit/c9e5a01605ef3e60e4f8692fee185034219baeeb
- The code is 6-levels-of-indentation-deep, has no comments, and uses one- or two-character variable names.
- It seems that using regular expressions with `re.DOTALL` would be easier for highlighting than requiring double-escapes and custom escapes.

**Comment by br0ns** [comment]
I agree that the code could be cleaner but I'm not sure how you would use regular expressions.  I'll clean up the code a do a PR.

**Comment by TethysSvensson** [comment]
@br0ns: Do you expect this is something you want backported into stable? If so, could you do the PR directly against that branch?

**Comment by zachriggle** [comment]
Since `beta` is becoming stable soon, backports don't matter anymore and this can be closed.
