### ISSUE TITLE
Tests for the update mechanism

### ISSUE THREAD

**Issue by TethysSvensson** [Gallopsled/pwntools#723]
Currently we don't test update.py at all. It is not trivial to figure out how to do so.

One possiblity would be to add a doctest to assert that no update is needed. However this would mean that the tests for older releases would start breaking once we do a new release. This sucks, however it is still better than not testing at all.

Alternatively we could monkey-patch ourselves. Something along the lines of this would probablu work:

```
>>> import pwnlib.update, pkg_resources
>>> current_version = pwnlib.update.current_version
>>> pwnlib.update.current_version = pkg_resources.parse_version("0.0.0")
>>> perform_check().startswith('pip install')
True
>>> perform_check(prerelease = True).startswith('pip install')
True
>>> pwnlib.update.current_version = pkg_resources.parse_version("999.999.999")
>>> perform_check() == None
True
>>> perform_check(prerelease = True) == None
True
>>> pwnlib.update.current_version = available_on_github(prerelease = False)
>>> perform_check() == None
True
>>> perform_check(prerelease = True).startswith('pip install')
True
>>> pwnlib.update.current_version = available_on_github(prerelease = True)
>>> perform_check() == None
True
>>> perform_check(prerelease = True) == None
True
pwnlib.update.current_version = current_version
```

This should test all the edge cases I can think of and still work even in older releases. It is a bit ugly though.

@zachriggle: Does this seem like a reasonable level of testing to you?

**Comment by zachriggle** [comment]
Line 4/5 will break in the time between a tag being created and it being uploaded to pypi

**Comment by TethysSvensson** [comment]
I am not sure I understand why it would break?

**Comment by zachriggle** [comment]
The tagged version from github will be higher and will be used instead

**Comment by TethysSvensson** [comment]
That should still start with `pip install`?
