### ISSUE TITLE
Current `dev` branch tests are broken

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#741]
It appears that Github is rate-throttling Travis CI hosts, causing our unit tests to fail.

Not sure how to handle this.  @Idolf?

**Comment by zachriggle** [comment]
On further investigation, it looks like something is broken with binutils?

**Comment by zachriggle** [comment]
The test to start causing the failures is 5924c0f340707e15e812fa08a0ade07d881c040f which doesn't make sense :(

**Comment by zachriggle** [comment]
Nuked all Travis caches and re-started the `dev` build

**Comment by zachriggle** [comment]
Looks like a caching issue where `usr/bin` already exists so we don't set up binutils.

**Comment by zachriggle** [comment]
I don't understand how the cache is still present.  I deleted it on Travis but...

<img width="800" alt="screen shot 2016-09-16 at 3 53 09 pm" src="https://cloud.githubusercontent.com/assets/111640/18603380/bddb134c-7c25-11e6-8254-fece2139b34b.png">

**Comment by zachriggle** [comment]
Re-running the most recent CI for the `stable` branch, which passed.

If it failed, this implies there's an error with the CI itself (or something it depends on) rather than an actual "pwntools library" problem.

**Comment by zachriggle** [comment]
The `stable` re-run failed, which means that something outside of the repository is broken or has changed.

**Comment by TethysSvensson** [comment]
Fixed in #743 / #744.
