### ISSUE TITLE
`MemLeak` doesn't work for negative addresses

### ISSUE THREAD

**Issue by br0ns** [Gallopsled/pwntools#758]
Leaking memory at a negative address with `MemLeak` always returns `None` because of the check at https://github.com/Gallopsled/pwntools/blob/dev/pwnlib/memleak.py#L156.

At first glance that check seems reasonable; negative addresses doesn't exist.  But what if my information leak takes addresses relative to some offset like, say, the stack pointer.

I see two obvious solutions: 1) just remove the check or 2) add a flag to the `MemLeak` constructor where you can specify whether addresses are relative or absolute and then only enforce the check in case of absolute addresses.

Ps. I know that I was the one putting in the check in the first place.  I now think that I was wrong.

**Comment by zachriggle** [comment]
See #601 for why this was put in place.  If you can make everything work while allowing negative values, sounds good to me.  It hadn't ever occurred to me to use MemLeak for relative leaks before 😮

**Comment by zachriggle** [comment]
Ping, added a Pull Request to fix this.  I'd like @br0ns to review it.
