### ISSUE TITLE
The shellcraft bash completition does not work

### ISSUE THREAD

**Issue by TethysSvensson** [Gallopsled/pwntools#767]
Typing shellcraft and pressing tab results in this:

```
dev:~/git/pwntools> shellcraft 
...         checksec    cyclic      elfdiff     errno       hex         pwn         scramble    unhex       usage:      
asm         constgrep   disasm      elfpatch    [-h]        phd         pwnstrip    shellcraft  update
```

**Comment by zachriggle** [comment]
The only time it was ever modified after its addition was 66e41bd8623e9ebdc45c8ca2d429256095a3ce41.  I've never used it, I'm unsure if it works.  It looks like the bash completion now requires use of `pwn shellcraft <tab>`.  Feel free to make changes as you see fit to resolve it.

**Comment by zachriggle** [comment]
For what it's worth, we should probably be using `argcomplete` for completion scripts anyway.

**Comment by zachriggle** [comment]
It looks like `genzshcomp` also exists for `zsh` users.

**Comment by bstub** [comment]
What about using the cmd module?

https://wiki.python.org/moin/CmdModule

(follow-up: after closer inspection, the auto-complete functionality seems to only work when the cli have been launched)

**Comment by zachriggle** [comment]
The `cmd` module is for _implementing_ a command-line, with completion -- not for generating `bash`\- or `zsh`-compatible completion files.
