### ISSUE TITLE
Python3: Term Design

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#779]
The `term` module is currently unmaintained, and I haven't ever had enough time to figure it out.

If I recall correctly, @br0ns is the original author for most of it.

I've never been able to make it work under Python3 in particular, even though I did a bunch of work on it a year ago (I resorted to using NOTERM): https://github.com/binjitsu/binjitsu/commits/futurized

I think that the ultimate issue is that the `term` module needs to write raw non-printable **bytes** to stdout/stderr, but Python3 makes them TextIO/StringIO modules, which expect `str` objects which have their unicode encoding set.  I think we can avoid this by using `latin-1` encoding for printing and `bytearray` objects for manipulation.

While we're going back through all of this, do we want to re-work the `term` module?  Are there any extra gotchas to be aware of?

Currently, the `term` module has no tests.  It'd be nice to have some tests added to the Python2 version, which we can verify in Python3.

**Comment by Ferdi265** [comment]
Python3 has the possibility of writing to `sys.stdout.buffer` which accepts bytes/bytearrays.

The only caveat here is that `stdout` and `stdout.buffer` are individually buffered in default python, so it's best to flush both to stop weird ordering issues between them.

**Comment by Arusekk** [comment]
This is quite fixed in the current dev branch.
