### ISSUE TITLE
import problems

### ISSUE THREAD

**Issue by legendpawn** [Gallopsled/pwntools#791]
I have a strange problem,it may be stupid.....
when i run python in terminal，I can import pwn and do everying
But when i use pwntools in other python IDE even IDLE,i can not import pwn,beause it error....
It was  knotty...Please Help～～～
![2016-11-19 01-26-01](https://cloud.githubusercontent.com/assets/19665430/20439783/e19cedbc-ad82-11e6-96ff-0d4a3bec06e9.png)

**Comment by zachriggle** [comment]
It looks like you have several different installations of Python on your
system, but only one of them has Pwntools installed.

**Comment by legendpawn** [comment]
![image](https://cloud.githubusercontent.com/assets/19665430/20440090/26021706-ad84-11e6-8037-479d1c146e00.png)
How Can I fix it?

**Comment by zachriggle** [comment]
I'd recommend taking up the issue with your IDE vendor, or taking some time to learn about PYTHONPATH, site-packages, and how multiple installations work.
