### ISSUE TITLE
term.readline clears log output

### ISSUE THREAD

**Issue by rickyz** [Gallopsled/pwntools#792]
`term/term.py`'s `init` function replaces `sys.stdout` with a wrapped version that uses its own internal `write` implementation. `term` does not appear to play well with other code writing directly to unwrapped `sys.stdout`. Specifically, `term.readline.clear()` appears to clear text written to unwrapped `sys.stout`. Since https://github.com/Gallopsled/pwntools/commit/f9133b16800f088d380e8cbdff9f051676ff5654, `context.log_console` is the unwrapped `sys.stdout`, since it is set in `context/__init__.py` before `term.init` is called (before that, it would be set to the wrapped version in `log.install_default_handler`). As a result, log messages are cleared on the next `raw_input()` call.

```python
#!/usr/bin/env python
from sys import stdout
from pwn import *
#print 'unwrapped:', context.log_console.write
#print 'wrapped:', sys.stdout.write
# Write to unwrapped stdout
stdout.write('AAAA\n')
# Alternatively:
#log.warn('AAAA')
raw_input()
```

**Comment by rickyz** [comment]
(Just to clarify, I don't believe this affects the stable branch, as it hasn't picked up f9133b1 yet.)

**Comment by zachriggle** [comment]
The `term` module scares the daylights out of me :(

I'll see if I can figure it out :)

**Comment by zachriggle** [comment]
Does this fix the issue?

```patch
index a66cc73..a313211 100644
--- a/pwnlib/term/term.py
+++ b/pwnlib/term/term.py
@@ -21,6 +21,7 @@ import termios
 import threading
 import traceback

+from ..context import ContextType
 from . import termcap

 settings = None
@@ -127,6 +128,11 @@ def init():
         sys.stdout = Wrapper(sys.stdout)
     if sys.stderr.isatty():
         sys.stderr = Wrapper(sys.stderr)
+
+    console = ContextType.defaults['log_console']
+    if console.isatty():
+        ContextType.defaults['log_console'] = Wrapper(console)
+
     # freeze all cells if an exception is thrown
     orig_hook = sys.excepthook
     def hook(*args):
```

**Comment by rickyz** [comment]
Yup, that fixes it for me (using log.warn instead of stdout.write in my example no longer results in the log being cleared).
