### ISSUE TITLE
fmtstr utilize existing pointers on stack

### ISSUE THREAD

**Issue by bannsec** [Gallopsled/pwntools#795]
This is more of an enhancement I guess, however it is currently possible (or future possible) to allow the auto-format string tool to record what addresses it can see on the stack and allow the user to use those addresses to read or write? This is in the event that the input to the format string is not readily available on the stack itself, however useful pointers still may exist.

The question would likely arise as to how deep to enumerate the stack/pointers, and perhaps that could have a default value but selectable by the user?

**Comment by zachriggle** [comment]
The `FmtStr` module is pretty small at the moment, and is not scoped for this.

At some point, #682 will be completed, which will replace the current module with `libformatstr` ([github.com/hellman/libformatstr](github.com/hellman/libformatstr))

The requested feature is not currently possible, and the FmtStr module is EOL.  I recommend making a pull request against `libformatstr`.
