### ISSUE TITLE
pip install --upgrade pwntools installs v3.4.0b2

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#844]
On a pristine Ubuntu 12.04 docker image, "pip install --upgrade pwntools" installs v3.4.

It should be v3.3.

**Comment by zachriggle** [comment]
If I do it on my Mac, it installs the correct version.

**Comment by zachriggle** [comment]
Looks like this is related to using an old version of `pip`, which does not recognize the pre-release status.

**Comment by TethysSvensson** [comment]
I don't think there is anything we can do about this.
