### ISSUE TITLE
Misusing syscall register in amd64.linux.execve

### ISSUE THREAD

**Issue by david942j** [Gallopsled/pwntools#856]
In `pwnlib/shellcraft/amd64/linux/execve.asm`
https://github.com/Gallopsled/pwntools/blob/dev/pwnlib/shellcraft/templates/amd64/linux/execve.asm#L39
https://github.com/Gallopsled/pwntools/blob/dev/pwnlib/shellcraft/templates/amd64/linux/execve.asm#L43
The two `abi.register_arguments` indexes are incorrect

Should use
```
args_reg = abi.register_arguments[2]
env_reg  = abi.register_arguments[3]
```
instead, which are declared variables but not being used.

This also leads to redundant assembly code of `shellcraft.sh()`, which will call `syscall('SYS_execve', 'rsp', 'rdx', 0)`, make an unnecessary instruction `mov rsi, rdx` in the end of assembly.

**Comment by zachriggle** [comment]
It looks like this pattern also exists on i386 and MIPS.

The total impact is that an extra instruction is generated, the code still works fine.  The fix will go into `dev`.
