### ISSUE TITLE
Inconsistent use of sh_prepare

### ISSUE THREAD

**Issue by fortenforge** [Gallopsled/pwntools#870]
Line 97 of `pwnlib/tubes/ssh.py` isn't consistent with line 424 of `pwnlib/util/sh_string.py`. Namely the latter expects the environment variables as a dict while the former passes them as two different arguments. 

This causes an error when I try to do something like `shell.run('./foo', env={"bar": "test"})`.

**Comment by zachriggle** [comment]
Ping @Idolf since you did all of the `sh_command_with` stuff

**Comment by zachriggle** [comment]
Also, IIRC we don't actually need `sh_command_with` anymore since the most recent rewrite of `sh_string`.

**Comment by TethysSvensson** [comment]
I haven't studied the code in detail recently, but I agree. We should not need to use `sh_command_with` anymore. I propose we keep it anyways for API compatibility but stop using it internally. WDYT?

I will prepare a PR to this effect.

**Comment by zachriggle** [comment]
Closed via #892
