### ISSUE TITLE
Readthedocs is failing

### ISSUE THREAD

**Issue by TethysSvensson** [Gallopsled/pwntools#902]
Currently readthedocs throws an error when building. See https://readthedocs.org/projects/pwntools/builds/5022322/.

**Comment by kristoff3r** [comment]
Looks like [this](https://github.com/rtfd/readthedocs.org/issues/2642) which links to [this](https://github.com/rtfd/readthedocs.org/issues/2640). It looks like it should be fixed if we rebuild now.

**Comment by TethysSvensson** [comment]
That seemed to fix it.
