### ISSUE TITLE
`raw_input` does not strip trailing newlines

### ISSUE THREAD

**Issue by jonasbb** [Gallopsled/pwntools#906]
The `raw_input` method is supposed to strip the trailing newline. However, this does not always happen.
I am using version `3.4.0` which is the newest available in pip.

Test case:

```python
#!/usr/bin/env python
from pwn import *
s = raw_input("> ")
print repr(s)
```

Actual output:

```
$ env PWNLIB_DEBUG=1 ./test.py
> Hi
'Hi\n'
```

**Comment by zachriggle** [comment]
?
