### ISSUE TITLE
Release bus number is 1

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#915]
Currently, @Idolf cuts our releases each time, and has some scripts to help him do it in a consistent fashion.  It'd be useful if these scripts could be checked into source control, so that if he gets hit by a bus, we can still do releases in a similar fashion.

**Comment by TethysSvensson** [comment]
I don't actually have scripts. I have a file with some commands that serves to remind me of what to do.

I should have scripts. I am keeping this bug open for me to create scripts and include them in the repo. This would both mean less work for me and increase the bus factor.

Basically the process is:

- Get git into a state that would be okay to do a release from. This will at least include updating `README.md` (for stable releases), `CHANGELOG.md`, `pwnlib/version.py` and `setup.py`. It will likely also include doing a merge.
- Once a candidate-commit is ready for release I push it to `stable-staging` or `beta-staging` to test it.
- I check that the `CHANGELOG.md` looks correct when rendered on github.
- While the test is running I do my local tests. I these tests are run by hand based on a small file I copy-paste from to remind me. The current version of this file is at the bottom of this post. **For the most part** that could readily be turned into a script, however there are a few parts that would need some small modifications:
  - Some of the commands are run multiple times (e.g. the `time` command)
  - Some of the commands are inspected manually (e.g. the `time` command, `phd`, `shellcraft`)
- If everything passes (local tests and the `*-staging` branch), then I push to the `stable`/`beta` branch.
- I do a new release on github, pypi.
- Afterwards I always forward-merge to `beta` and `dev` after release to maintain the invariant that `dev` always contains all of `beta` and `beta` always contains all of `stable.`
- I then announce it on irc (and in the future on twitter as well)

If I am doing both a stable and a beta release, I do almost all of these steps twice with no modification. Only the last two steps are altered slightly (I don't do two announcements, I don't do two forward-merges to dev).

Here is the file I copy-paste from:

```
sudo rm -rf *.egg-info dist
git clean -fxd
sudo python setup.py sdist -q
sudo rm -rf /usr/local/lib/python2.7/dist-packages/pwntools*
sudo rm -rf /usr/local/lib/python2.7/dist-packages/pwnlib*
sudo sed -i '/pwntools/d' /usr/local/lib/python2.7/dist-packages/easy-install.pth
sudo -H pip install -q pwntools
sudo -H pip uninstall -q -y pwntools
shellcraft # should give error
sudo -H pip install -q dist/* # Should only be one file, previous have been deleted
sudo -H pip uninstall -q -y pwntools
sudo -H pip install -q dist/* # Should only be one file, previous have been deleted
shellcraft # should not give error
head -c 128 /bin/sh | phd # show not give an error
time python -c 'import pwn' 
sudo -H pip uninstall -q -y pwntools
sudo -H pip install -q -e . 
[do git stuff]
sudo python setup.py -q sdist upload -r https://pypi.python.org/pypi
[do version number and changelog stuff] 
[bump version number in dev README as well]
[do a new release on github]
[update irc]
```

**Comment by zachriggle** [comment]
Note that the `sdist upload` command is deprecated.

```
$ python setup.py -q sdist upload -r https://pypi.python.org/pypi
...
WARNING: Uploading via this command is deprecated, use twine to upload instead (https://pypi.org/p/twine/)
error: <urlopen error [Errno 32] Broken pipe>
```

The new command looks like:

```
$ python setup.py -q sdist
$ twine upload -u USERNAME -p PASSWORD dist/pwntools-VERSION.tar.gz
```

**Comment by heapcrash** [comment]
Release bus number is now 2
