### ISSUE TITLE
ROP arch when no context() call

### ISSUE THREAD

**Issue by bannsec** [Gallopsled/pwntools#927]
Perhaps this is another design decision, but I've noticed that without a context() call, the ROP.call method will default to 32-bit calling convention. It would be neat in my opinion if the rop class would pick up the relevant information that the ELF class already loaded.

Example:
```python
In [1]: from pwn import *

In [2]: elf = ELF("./main")
[*] '/home/user/tmp/main/main'
    Arch:     amd64-64-little
    RELRO:    Partial RELRO
    Stack:    No canary found
    NX:       NX enabled
    PIE:      No PIE

In [3]: rop = ROP(elf)
[*] Loading gadgets for '/home/user/tmp/main/main'

In [4]: rop.call(0x1234,(0x1234,))

In [5]: print(rop.dump())
0x0000:           0x1234 0x1234(4660)
0x0004:           'baaa' <pad>
0x0008:           0x1234 arg0
```

The ELF call figured out it's amd64-little, but the ROP class appears to still believe it should use 32-bit calling conventions.

**Comment by zachriggle** [comment]
ROP knows nothing at all about any calling convention except i386.

**Comment by zachriggle** [comment]
But in any case, yes, you must set the context.

It's doing exactly what you're asking if it.

**Comment by zachriggle** [comment]
This isn't quite true.  It was able to do very, very basic `amd64` ROP, as long as you had perfect `pop rdi; ret`-style gadgets for every register that was required.

Since #1019 landed, things are a bit better and we can also do some slightly more complex things.

```
>>> e=ELF.from_assembly('pop rsi; pop r15; pop rdi; ret; pop rax; pop rdx; add rsp, 0x10; ret')
[*] '/tmp/pwntools/pwn-asm-2YCsXP/step3'
    Arch:     amd64-64-little
    RELRO:    No RELRO
    Stack:    No canary found
    NX:       NX disabled
    PIE:      No PIE (0x10000000)
    RWX:      Has RWX segments
>>> r=ROP(e)
[*] Loading gadgets for '/tmp/pwntools/pwn-asm-2YCsXP/step3'
>>> r.call(0xdeadbeef, [1,2, 3])
>>> print r.dump()
0x0000:       0x10000000 pop rsi; pop r15; pop rdi; ret
0x0008:              0x2 [arg1] rsi = 2
0x0010:       'eaaafaaa' <pad r15>
0x0018:              0x1 [arg0] rdi = 1
0x0020:       0x10000006 pop rdx; add rsp, 0x10; ret
0x0028:              0x3 [arg2] rdx = 3
0x0030:       'maaanaaa' <pad 0x10>
0x0038:       'oaaapaaa' <pad 0x8>
0x0040:       0xdeadbeef
```
