### ISSUE TITLE
Reverse Constant Lookup

### ISSUE THREAD

**Issue by bannsec** [Gallopsled/pwntools#929]
I find myself often looking up a constant value either through online documentation or .h files.

Is this something pwntools can do? I've found i can use the following line to help with this task:

```python
[x[0] for x in inspect.getmembers(constants.linux) if x[1] == 0xe]
```

Obviously, replacing 0xe with whatever the constant i'm looking for is, and constants.linux with any other OS if need be.

**Comment by zachriggle** [comment]
Yes, there is a command-line tool for this, "constgrep"

**Comment by bannsec** [comment]
Interesting. I can only get it to go from string -> constant. not the other way:

```bash
$ constgrep -i segv
#define SIGSEGV 11
```

```bash
$ constgrep -e 11
11
```

**Comment by zachriggle** [comment]
A quick hack is "constgrep | grep 11"

**Comment by zachriggle** [comment]
I had a prototype for this, but ended up rewriting all of `constgrep`, which is probably a bad plan.

**Comment by Arusekk** [comment]
This seems to work now.

An example:

```sh
$ constgrep ^SIG 11
#define SIGSEGV 11
```

To find everything, just pass an empty regular expression, like `^` alone.
