### ISSUE TITLE
Can fmtstr_payload control the number of bytes to overwrite at specific position?

### ISSUE THREAD

**Issue by skysider** [Gallopsled/pwntools#935]
I notice the 'writes' parameter in 
`fmtstr_payload(offset, writes, numbwritten=0, write_size='byte'):`
is a dict and the value of the key is always 4 or 8 bytes depending on the arch. But in some occasion (for example, the printf buffer is not big enough  or we don't know the high bytes of some address), we only need to overwrite 1 or 2 bytes at specific position, so I think it's necessary to specify how many bytes you overwrite at specifiy position, for example, writes={0xf7123456:(0x66,1)}, and it can be achieved by adding judgement by the type of the value in key-value structure which doesn't effect previous function.

**Comment by zachriggle** [comment]
Not in its current form.  I have some work-in-progress in #827 which would make this possible.

**Comment by Arusekk** [comment]
Yes it is!
Thanks to #1216 (and probably even before that), you can now do:
```py
writes = {
    0xcafebabe: b'aa',
    0xdeadbeef: b'abc',
    0x1337f00f: p16(4001),
}
```
and leave the rest of your code the same.
