### ISSUE TITLE
Help needed: Passing a result of a function as an argument in ROP

### ISSUE THREAD

**Issue by mkravchik** [Gallopsled/pwntools#936]
Hi,

I've spent some time trying stuff and searching and, once not found, finally turn to the source :-)
I'm building a ROP chain that calls a function and then passes its result as an argument to the next one.
Something like:
fd = open("/tmp/bla", O_RDWR)
write(fd, data, len)

How do I do it with ROP? I have found gadgets that push rax and pop rdi (I'm on amd64), but how do I use these together with the ROP class and its shortcuts? 

Thanks a lot!

**Comment by zachriggle** [comment]
There is no mechanism for this.  You're much better off making a reasonable assumption about the return value.  File descriptors are sequential and easy to predict.
