### ISSUE TITLE
https://demo.pwntools.com/ Suceptabile to Bash Injection #pwned

### ISSUE THREAD

**Issue by jiachen247** [Gallopsled/pwntools#942]
Demo link in the README.md exposes a limited shell on the server.

Import os;
os.system("/bin/sh");
$

![img_20170406_121032](https://cloud.githubusercontent.com/assets/17170991/24737789/fd1fe2ca-1ac3-11e7-9ca1-e0bf5d8e329f.jpg)

pls fix thanks

**Comment by zachriggle** [comment]
I think you entirely missed the point.
