### ISSUE TITLE
Add option to select custom template for generation

### ISSUE THREAD

**Issue by reu-res** [Gallopsled/pwntools#955]
Currently only the base template is available. For example, I want a template that doesn't use an ssh connection, or use my own template.

**Comment by zachriggle** [comment]
The template does all of the permutations of tubes.  It does not require you to use e.g. SSH.

I do not intend to add functionality to extend the template, as the logic is pretty well tied into the current template.

If you'd like to make additions or changes to the current template / template tool, Pull Requests are encouraged.
