### ISSUE TITLE
Radare2 integration

### ISSUE THREAD

**Issue by XVilka** [Gallopsled/pwntools#965]
Using r2pipe, seems that can substitute many things...

**Comment by zachriggle** [comment]
Specific suggestions are recommended, as is im closing this. Thanks!

**Comment by XVilka** [comment]
@zachriggle interestingly enough you're not closing this... https://github.com/Gallopsled/pwntools/issues/707

**Comment by zachriggle** [comment]
Yes, because that one has specific examples. Yours isn't even a complete
sentence.
