### ISSUE TITLE
DynELF libcdb feature requrests

### ISSUE THREAD

**Issue by TethysSvensson** [Gallopsled/pwntools#983]
- The ability to turn downloading off and use in-memory resolving exclusively (should ignore the cache as well)
- Update in the docs to show that the libcs are cached to find the downloaded libc.
- Negative caching: If we cannot download a libc (bug, gitlab is down, the libc does not exist), this should be cached. At *least* an in memory negative cache, but I would prefer if we put something time-limited in /tmp as well.
- The local libc should be tried before using libcdb
- Some of the hashes are broken, e.g. https://gitlab.com/libcdb/libcdb/raw/master/hashes/build_id/ca5c6cfe528af541c3c2c15cee4b3c74da4e2fb4. Could we add a test to make sure that all the links are working?

**Comment by zachriggle** [comment]
Most of these are doable, with the exception of "Could we add a test to make sure that all the links are working?".  There's no way to automate this externally, it'd have to be something done on the libcdb side.

**Comment by TethysSvensson** [comment]
Sure, I should have filed that on the libcdb repo.

**Comment by zachriggle** [comment]
Closed via #986

**Comment by TethysSvensson** [comment]
There are still a few things from the above list missing:

- The negative caching should time-limited (since libcdb might introduce more/fix broken symlinks)
- The local libc should be tried

**Comment by zachriggle** [comment]
Good catch, thanks!

**Comment by peace-maker** [comment]
The last two open items from the list are implemented now.
